### ISSUE TITLE
Help Wanted: Screenshots in README are out of date

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jira#1003]
The screenshot in https://github.com/mattermost/mattermost-plugin-jira#what-are-notifications shows that the ticket creation option is accessible via the three-dot menu. That is not true any longer. That option has moved under the "Message actions" menu.

![Screenshot from 2023-12-11 13-26-52](https://github.com/mattermost/mattermost-plugin-jira/assets/16541325/069f1c8f-78ae-44f0-ba1b-438ae7344b4c)

**Comment by hanzei** [comment]
cc @cwarnermm

**Comment by chriswachira** [comment]
Hi @cwarnermm. I'd like to take up this ticket.

**Comment by cwarnermm** [comment]
Thank you, @chriswachira, for your help with this update! Very much appreciated. Let me know if you have any questions or concerns.

**Comment by chriswachira** [comment]
@cwarnermm I've created a PR, kindly review
