### ISSUE TITLE
The user is getting multiple notifications in the channel or DM/GM on MM for a event on Jira when duplicate subscriptions are created.

### ISSUE THREAD

**Issue by arush-vashishtha** [mattermost/mattermost-plugin-jira#1011]
### Summary
The user can create duplicate subscription for an existing subscription and it results in generating same notification the number of times the subscription is duplicated.
### Steps to reproduce
1. Create a subscription using the `/jira subscribe edit` slash command in any desired channel or DM/GM on MM.
2. Create a duplicate subscription for the above added subscription using the `/jira subscribe edit` slash command in the same desired channel or DM/GM on MM.
3. Create the event on Jira for which the above subscriptions were created in the desired channel or DM/GM on MM.
### Expected behavior
The user should get only one notification for the event in the desired channel or DM/GM on MM.
### Actual behavior
The user is getting N number of notifications for the event in the desired channel or DM/GM where N is the number of subscriptions created for that event on MM.
### Screenshots
![image](https://github.com/mattermost/mattermost-plugin-jira/assets/145128655/34f6d652-4757-44cd-9949-ab63e8a44b5a)

**Comment by mkddostro** [comment]
Not sure if this is related but after issues with the settings (in Jira, webhook and app permissions) I set up a new app in Jira and deleted the old one. Since then I am receiving duplicate notifications for every action I am subscribed to.

**Comment by raghavaggarwal2308** [comment]
> Not sure if this is related but after issues with the settings (in Jira, webhook and app permissions) I set up a new app in Jira and deleted the old one. Since then I am receiving duplicate notifications for every action I am subscribed to.

@mkddostro Did create new subscriptions after setting up the new app?
