### ISSUE TITLE
Jira link tooltip: Font is blurry compared to MM post text

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#1019]
![CleanShot 2024-01-10 at 16 12 48](https://github.com/mattermost/mattermost-plugin-jira/assets/6913320/0f5019b4-95b3-4186-90a4-f8c3b4fbf90d)

**Comment by raghavaggarwal2308** [comment]
@mickmister This might be some possible reason:
- There is a lot of load on the system.
- The Zoom level of the tab is not appropriate.

This is not getting reproduced on my local. Also, the screenshot you attached in #1018 is looking fine.

My local:
![tooltip_wrap](https://github.com/mattermost/mattermost-plugin-jira/assets/55234496/7213aac5-684d-449e-a98e-90df8598a20b)
