### ISSUE TITLE
Jira link tooltip: Project icon looks off on dark theme

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#1021]
In the top right corner of link tooltip, the icon for the given Jira project is shown. In a Mattermost dark theme, this icon can look a little too transparent.

If this proves difficult to style to fit any theme, I'm thinking we can remove the icon. Also, I think the project prefix in the issue key is enough to identify the project.

<img width="520" alt="CleanShot 2024-01-12 at 13 37 41@2x" src="https://github.com/mattermost/mattermost-plugin-jira/assets/6913320/3b3d7a5e-146a-4541-bb03-747c6136924e">

**Comment by mickmister** [comment]
@raghavaggarwal2308 What are your thoughts on this?

**Comment by raghavaggarwal2308** [comment]
@mickmister I will look into it. If it is easy enough to do. Otherwise, we can remove the icon.
