### ISSUE TITLE
Doc link in plugin settings page point to non existing GitBook

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jira#1029]
The links from the settings page (https://github.com/mattermost/mattermost-plugin-jira/blob/8a1f5b54b59e5c526f90727e914949ef2b1b5343/plugin.json#L23-L24) point to GitBook, which is not longer used. They should point to the README instead.

**Comment by hanzei** [comment]
@mattermost/contractor-brightscout Can you please take a look? cc @mickmister

**Comment by cwarnermm** [comment]
@mickmister - Permalinks are used in-product for docs/web links. Plugins and integrations can use direct links to README content in repositories.
