### ISSUE TITLE
Support case where issue reporter is blank for new issue creation event

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#1032]
An issue is occurring when no `Reporter` field is present on a newly created issue. According to the customer, the `reporter` field is hidden in the field setting scheme in JIRA. The issue is happening here:
https://github.com/mattermost/mattermost-plugin-jira/blob/d08f7f746aadebf079871f5611b03e62b16bd172/server/issue_parser.go#L28

We'll also want to make sure we are defensive with other instances of the `Reporter` field, as possibly look into other potential cases of missing fields in the codebase.

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/dmfgg5ndmirptniaq9fn4irtew) *by @hanzei*._

**Comment by raghavaggarwal2308** [comment]
@hanzei @mickmister Just for clarification:
- On what action the issue is being caused? Is the user trying to create an issue using the MM interface?

**Comment by hanzei** [comment]
@raghavaggarwal2308 Yes, the bug happens when a user creates an issue via the MM UI.
