### ISSUE TITLE
Link tooltip title could have a hover text for issue titles that are too long

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#1077]
The title in the link tooltip can be a certain length where the words are cut off. I'm thinking there are two opportunities for improvement here:

- Show `...` at the end of the title when it is too long
- Hovering over the title could show the whole title in a "hover text". I think this can be done by setting the element's `title` attribute

---

<img width="593" alt="image" src="https://github.com/mattermost/mattermost-plugin-jira/assets/6913320/cd80b5be-269b-43b3-9acf-d9732627ca7e">

**Comment by shwetd19** [comment]
Hey there 👋,

I stumbled upon issue #1077 about improving link tooltips for long issue titles in the Mattermost Jira plugin. It seems like a neat challenge that could enhance usability significantly. With my background in full-stack dev, I'd love to dive in and help refine this feature. My recent projects have involved enhancing user interactions, which I believe could bring value to this issue. Would it be possible to let me tackle this? 

Excited to contribute!
Cheers,
@shwetd19

**Comment by mickmister** [comment]
Hi @shwetd19 👋 

Absolutely, I'll assign you to the ticket. Let me know if you have any questions about the plugin or the feature. Thanks @shwetd19!
