### ISSUE TITLE
Notifications showing markdown incorrectly

### ISSUE THREAD

**Issue by matthewbirtch** [mattermost/mattermost-plugin-jira#1096]
I'm getting some formatting issues with the notifications that come from Jira Bot. 

For [this ticket](https://mattermost.atlassian.net/browse/MM-58292), bulleted list items are showing as headings.

**How it shows in Mattermost**
<img width="1023" alt="image" src="https://github.com/mattermost/mattermost-plugin-jira/assets/2040554/27771248-e6ae-4ef2-a43a-f21582063910">

**How it shows in Jira**
<img width="1027" alt="image" src="https://github.com/mattermost/mattermost-plugin-jira/assets/2040554/a013ac0a-ffef-4ac0-8be8-ebf811e07d61">

**Comment by Kshitij-Katiyar** [comment]
@matthewbirtch @wiggin77 
I looked into this issue and would like to share some findings with you:
- Jira sends the ordered list used in the comment as:
```
# orderedListItem1
# orderedListItem2
# orderedListItem3
```

- Similarly, headings used in comments on the Jira issue are sent as `h1. heading from jira issue` which is not handled on the plugin side and is rendered as it is.

We assume there are more of these markdown issues. We have assigned @AayushChaudhary0001 to list all the possible markdown issues.
Once we have the list of the issues, we can proceed to make custom handling of those markdowns

**Comment by raghavaggarwal2308** [comment]
@wiggin77 Also, do you think we should work on the task explained above?

**Comment by wiggin77** [comment]
@raghavaggarwal2308 Yes, let's at least fix the known. easy ones.

**Comment by AayushChaudhary0001** [comment]
I tried to reproduce this issue and below are my findings.
These following types of text I have tested and they are shown as:-

- Bold text on Jira :- Italic on MM
- Italic text on Jira :- Italic on MM
- Underline text on Jira :- Weird text
- Strikethrough text on Jira :- Weird text
- Subscript and superscript text on Jira :- Weird text
- Multiple coloured text :- Shown as normal with colour codes
- Bulleted list on Jira :- Bulleted list on MM
- Numbered list on Jira :- Headings on MM
- Headings in Jira :- Weird text with heading classification

I am also attaching screenshots below to verify

On Jira:-
![image](https://github.com/user-attachments/assets/3a7b1327-b13e-4b06-abc2-7239ca68449e)


On Mattermost:-
![image](https://github.com/user-attachments/assets/ed780668-7d34-4b29-9596-74b1e4be74db)


On Jira(for headings):-

![image](https://github.com/user-attachments/assets/9960d19d-c1e1-488a-91b4-ddff2a1dc11c)


On Mattermost(for headings):-

![image](https://github.com/user-attachments/assets/5e3dd9a1-8a84-42de-a1f4-4b6300409bc1)
