### ISSUE TITLE
After executing "/jira uninstall", link to the appropriate Jira Settings page in the resulting ephemeral message

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#145]
SCENARIO 1: 
Repro: Successfully uninstall Jira Cloud via "/jira uninstall cloud <url>"
Observed: Ephemeral message:
```
Jira instance successfully disconnected. Go to **Settings > Apps > Manage Apps** to remove the application in your Jira Cloud instance.
```

EXPECTED: Ephemeral message, containing a link to Manage Apps page
```
Jira instance successfully disconnected. Go to [**Settings > Apps > Manage Apps**](...appropriate page link here...) to remove the application in your Jira Cloud instance.
```

----

SCENARIO 2: 
Repro: Successfully uninstall Jira Server via "/jira uninstall server <url>"
Observed: Ephemeral message:
```
Jira instance successfully disconnected. Go to **Settings > Applications > Application Links** to remove the application in your Jira Server or Data Center instance.
```

EXPECTED: Ephemeral message, containing a link to Manage Apps page
```
Jira instance successfully disconnected. Go to [**Settings > Applications > Application Links**](...appropriate page link here...) to remove the application in your Jira Server or Data Center instance.
```

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by promulo** [comment]
Hi, I am interested on working on this issue.

**Comment by jasonblais** [comment]
Thanks @promulo! Assigned to you, let us know if you have any questions to get started :)
