### ISSUE TITLE
After executing "/jira install server", link to the appropriate Jira Application Links page in the resulting ephemeral message

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#146]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

**Repro:** Post `/jira install server <URL>`

**Observed:** First step asks the admin to navigate to "Settings > Applications > Application Links".
**Expected:** First step includes a link to "Settings > Applications > Application Links", which redirects user to <Jira URL>/plugins/servlet/applinks/listApplicationLinks

More specifically, change this line of code (https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go#L264) to

```
1. Navigate to [**Settings > Applications > Application Links**](%s/plugins/servlet/applinks/listApplicationLinks)
```

where %s is the URL specified in the `/jira install server <URL>` command

**Comment by lucianomagrao** [comment]
already done by #316

**Comment by jasonblais** [comment]
Thanks @lucianomagrao for the heads up!
