### ISSUE TITLE
Automatically convert JIRA-formatted messages to Mattermost Markdown

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#147]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

See this PR as a starting point: https://github.com/mattermost/mattermost-plugin-jira/pull/24

The objective of this PR is to convert Jira-formatted messages to Mattermost Markdown, when notifications from Jira are posted to a Mattermost channel.

**Comment by nathanmkaya** [comment]
I would like to work on this

**Comment by jasonblais** [comment]
Great! 🚀 

cc @aaronrothschild @levb

**Comment by aaronrothschild** [comment]
@nathanmkaya That's great, thanks for your help!  Let me know if you have any questions that pop up.

**Comment by mickmister** [comment]
Hi @nathanmkaya, just checking in. How are you doing on this feature?

**Comment by levb** [comment]
@mickmister @nathanmkaya submitted a draft to me at https://github.com/nathanmkaya/goldmark-extended but I have not yet had a chance to carefully review it and provide meaningful feedback. If you can help out it'd be great!

**Comment by mickmister** [comment]
@nathanmkaya Do you mind submitting a pull request to the Jira plugin repo that uses your solution? Thank you for your work on this feature!

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
