### ISSUE TITLE
plugin 1.0.4 is not working

### ISSUE THREAD

**Issue by fireau1** [mattermost/mattermost-plugin-jira#15]
Hello

I have tried to get the jira plugin to work, but was not able to. I enabled debug level log but nothing appears in the log file.
I'm running mattermost 5.6.2 on centos 7.xx with postgress database.
I enabled normal webhook for other service we use (site24) and that works fine.
Our Jira is running on the cloud with atlassian.

Thanks

**Comment by ksast** [comment]
I can confirm this. No logs created. Mattermost 5.6.1 on debian 9.6 (stretch).

**Comment by hanzei** [comment]
Are you able to enable the plugin? Could you test, if v1.0.1 works fine?

CC @jwilander

**Comment by ksast** [comment]
The plugin can be enabled from my side. I also tested with 1.0.1. Same result. No posting to the channel and no log information.

**Comment by fireau1** [comment]
I just tried 1.0.1 same result as 1.0.4
I dont think the plugin itself is logging to mattermost log file.

**Comment by fireau1** [comment]
Any update on this?

**Comment by hanzei** [comment]
With no log and no step to reproduce this is quite hard to fix. Let's fix #3 and #17 first, cut a new release and then try to debug. @jwilander are you fine with this?

**Comment by jwilander** [comment]
That's fine with me 👍 

@fireau1 if you could also share the PluginSettings section of your config.json (with sanitized config settings as needed) I can compare it to ours that is working to see if it's possibly a configuration issue

**Comment by fireau1** [comment]
![image](https://user-images.githubusercontent.com/46446437/50839580-e28a1880-1360-11e9-90d4-1e247c8b2d98.png)
![image](https://user-images.githubusercontent.com/46446437/50839627-0188aa80-1361-11e9-9015-f57abe69e863.png)
![image](https://user-images.githubusercontent.com/46446437/50839737-3268df80-1361-11e9-9c17-95349d2ca955.png)
![image](https://user-images.githubusercontent.com/46446437/50839921-adca9100-1361-11e9-8765-70447663d44a.png)

**Comment by fireau1** [comment]
This to let you know that we have found the issue it is not working
the parameters in the webhook on jira have to be passed in order of
 secret=xxxx&team=xxx&chanel=xxx if they are not then nothing gets posted

**Comment by ksast** [comment]
> This to let you know that we have found the issue it is not working
> the parameters in the webhook on jira have to be passed in order of
> secret=xxxx&team=xxx&chanel=xxx if they are not then nothing gets posted

Glad to hear that you've got this one working. Unfortunatelly this is not true for my case, so I provide you the requested snippets:

![image](https://user-images.githubusercontent.com/43265582/50884817-46a5ee80-13ec-11e9-87ab-db844bc665ee.png)

![image](https://user-images.githubusercontent.com/43265582/50884828-4ad20c00-13ec-11e9-9cb6-eb25a018e14e.png)

/opt/mattermost/config/config.json:
`"PluginSettings": {
    "Enable": true,
    "EnableUploads": true,
    "Directory": "./plugins",
    "ClientDirectory": "./client/plugins",
    "Plugins": {
        "jira": {
            "enabled": true,
            "secret": "NfN70AIPh1Qe6YYzL3YgojYk2xxxxxx",
            "username": "someuser"
        },
        "jitsi": {
            "jitsiurl": "https://jitsi.myjitsiurl.com"
        }
    },
    "PluginStates": {
        "com.github.matterpoll.matterpoll": {
            "Enable": true
        },
        "jira": {
            "Enable": true
        },
        "jitsi": {
            "Enable": true
        },
        "mattermost-autolink": {
            "Enable": false
        },
        "zoom": {
            "Enable": false
        }
    }
},
`
Note that plugin version 1.0.4 does not contain a plugin.json file, so I can’t show you this one.

**Comment by fireau1** [comment]
We got version 1.0.4 to work. We did not try with 1.0.1

**Comment by fireau1** [comment]
Look in /opt/mattermost/plugins/jita in 1.0.1 i think it was plugin.yaml and in 1.0.4 its plugin.json

**Comment by ksast** [comment]
> Look in /opt/mattermost/plugins/jita in 1.0.1 i think it was plugin.yaml and in 1.0.4 its plugin.json
Yeah sorry, you are totally right. This file is unchanged on my system. However 1.0.4 still does not work.

**Comment by hanzei** [comment]
@ksast Could you please try with the newly released [v1.1.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v1.1.0)? It adds a lot of more logging. This will help us debugging your problem.

**Comment by fireau1** [comment]
Is there a compiled version? or do I have to compile it?

**Comment by fireau1** [comment]
Ok this is strange.
I got 1.0.4 to work with Jian now it doesnt.
![image](https://user-images.githubusercontent.com/46446437/51615382-fc625880-1f27-11e9-82c6-e4320200f7c1.png)

**Comment by ksast** [comment]
> @ksast Could you please try with the newly released [v1.1.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v1.1.0)? It adds a lot of more logging. This will help us debugging your problem.

I'll test this within the next few days, thanks.

**Comment by hanzei** [comment]
@fireau1 Could you try [v1.1.0](https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v1.1.0) and see if the issue still exists?

**Comment by fireau1** [comment]
I did. The image if from the latest build

**Comment by hanzei** [comment]
@fireau I found the bug and submitted a PR to fix it. Thanks for helping us debug this!

**Comment by ksast** [comment]
I upgraded mattermost to 5.7.1 and the jira plugin got upgraded to 1.1.0. Now everything works fine, thank you.
