### ISSUE TITLE
Support "Share Issue" workflow in Jira plugin

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#163]
Reopened from https://github.com/mattermost/mattermost-plugin-jira/issues/131

**CONTEXT**

In Jira, it is possible to share a specific ticket with certain users.

This triggers an email notification with the given text message.

![image](https://user-images.githubusercontent.com/13119842/59165844-0dcf8a00-8af0-11e9-91df-d10f027110c1.png)

(See the red box in https://www.google.de/search?q=jira+share+issue&prmd=nisv&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiElebegdPiAhWCCuwKHYwpBZQQ_AUoAnoECAwQAg&biw=1024&bih=634#imgrc=mnsLR2VazD05WM)

**PROPOSED CHANGE**

Enable users to receive these notifications via Mattermost instead of email.

The exact approach would need to be investigated, but one option is for Mattermost to plug in to the Jira notification preferences and enable users to choose between receiving these notifications in email or Mattermost. The sender would then not be required to make a choice about the message medium.

**Comment by AGMETEOR** [comment]
@jasonblais I would suggest something like this;
- The user intending to share types `/jira share <issueKey> <mattermost username or id>`
- When they press enter, a DM is sent to the MM user whose id/username was provided in the command. The DM has the link to the issue on Jira

**Comment by jasonblais** [comment]
Thanks @AGMETEOR! @aaronrothschild / @jfrerich what do you think?

**Comment by aaronrothschild** [comment]
> Thanks @AGMETEOR! @aaronrothschild / @jfrerich what do you think?

@AGMETEOR This sounds like a great addition.  

> The user intending to share types /jira share <issueKey> <mattermost username or id>

**Comment by jfrerich** [comment]
@AGMETEOR, @jasonblais, @aaronrothschild - I do think we should implement @AGMETEOR's suggestion (verbatim and as suggested). 

I think the suggestion from the issue author is asking for one more item. 

> IMO a user should configure how he/she would like to receive notifications. The sender should not be required to make a choice about the message medium.

This quote suggests that we store a user setting that allows a user to receive MM DM notifcations or email, or perhaps both.

I suggest moving forward with the slash command and if y'all agree there is a third item, we create a separate ticket to address that concern.

**Comment by jasonblais** [comment]
Thanks all! As a note, the use case was shared for the situation when someone is inside Jira and wants to share a ticket to one or more users directly from Jira (for notification purposes). 

While we could add a Mattermost slash command for it, two thoughts come to mind:
 - it does not address the original use case
 - would the user be more likely to send a DM or at-mention the user with the ticket link, or use a slash command to do so when they want to share it in Mattermost?

Completely open to feedback.

@aaronrothschild @jfrerich @AGMETEOR

**Comment by jfrerich** [comment]
@jasonblais, regarding the original use case:
> someone is inside Jira and wants to share a ticket to one or more users directly from Jira (for notification purposes)
Correct me if I am wrong, but the user is asking for an integration or app inside Jira, not Mattermost.  That seems outside of our scope since it isn't something that could be implemented with the plugin

**Comment by jfrerich** [comment]
@jasonblais Regarding your second bullet:
> would the user be more likely to send a DM or at-mention the user with the ticket link, or use a slash command to do so when they want to share it in Mattermost?

I think a user would just DM or at-mention vs the slash command and although adding the slash command seems great, I'm not sure that it would get used.

**Comment by jasonblais** [comment]
> That seems outside of our scope since it isn't something that could be implemented with the plugin

True - at the time of creating the help wanted issue, there were considerations for creating an Atlassian marketplace plugin for Mattermost that would support such a use case and interact with the Mattermost plugin for Jira.

**Comment by aaronrothschild** [comment]
@jasonblais Reading the ticket, I didn't realize it was "in Jira" as the original ask. This sort of UX is possible, but needs some ninja-level-jira-work IMO. Out of scope...

@AGMETEOR However, I like the "share" idea.... BUT - I also just realized...with Autolink and Jira working together now to auto-detect Jira Project Codes.... the user literally just needs to paste the Jira ticket name/id and send it to someone - it is now clickable.  I'm not sure it can get simpler than that.  

However, with "/jira share" we could show more info to the end-user (before they click) by posting it as a message attachment.  I'm kinda torn now.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
