### ISSUE TITLE
Render Jira webhook comments as slack attachment posts

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#167]
This Jira plugin send notifications from Jira projects to Mattermost channels via webhooks. To learn more about configuring and using the webhooks, see the documentation at https://github.com/mattermost/mattermost-plugin-jira/blob/master/README.md.

For the source code, see the server-side webhook code at https://github.com/mattermost/mattermost-plugin-jira/tree/master/server

**PROPOSED CHANGE**

For webhook events sent for issue comment creations and issue comment updates, add a Markdown quotation in front of the comment, inside the webhook attachment

Current:

![image](https://user-images.githubusercontent.com/13119842/59476876-ba777780-8e20-11e9-899d-d2899b760c7b.png)

Proposed:

![image](https://user-images.githubusercontent.com/13119842/59476851-a16ec680-8e20-11e9-9401-94bcbb39c564.png)

Note that the comment is in a slack attachment style post and also quoted.

Additionally, this issue requests to fix the following issue, in tandem.
https://mattermost.atlassian.net/browse/MM-19652

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by mickmister** [comment]
@aaronrothschild Comments are rendered with just quotes at the moment. What do you think about rendering them in a box like in this issue's description? I think it looks much cleaner is more isolated from the rest of the post.

**Comment by jfrerich** [comment]
@aaronrothschild, @mickmister do we have a final suggestion for this issue?  I'd like to open it back `Up For Grabs`

**Comment by mickmister** [comment]
I think it should have the box and the quotes, as shown in the second screenshot in the description. With our current implementation (does not match either picture in the description), we have the quotes but not the box.

This is also a good opportunity to solve the indentation issue described here: https://mattermost.atlassian.net/browse/MM-19652 . I have a proposed solution in the comments there.

**Comment by aaronrothschild** [comment]
> @aaronrothschild, @mickmister do we have a final suggestion for this issue? I'd like to open it back `Up For Grabs`

I agree with Michael, makes it look much cleaner, lets open up to `up for grabs`

**Comment by jfrerich** [comment]
Thanks fellas!  I'll be posting as a HW soon!

**Comment by promulo** [comment]
Hi, I've been looking for a Go issue to work on as first contribution. May I take this one?

**Comment by mickmister** [comment]
Absolutely, thanks @promulo!
