### ISSUE TITLE
Bold action verb in webhook notification pretext

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#168]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

This Jira plugin send notifications from Jira projects to Mattermost channels via webhooks. To learn more about configuring and using the webhooks, see the documentation at https://github.com/mattermost/mattermost-plugin-jira/blob/master/README.md.

For the source code, see the server-side webhook code at https://github.com/mattermost/mattermost-plugin-jira/tree/master/server

**PROPOSED CHANGE**

For webhook events sent for issue creation/update/delete and comment creation/update/delete, add Jira issue type icon in front of issue type in webhook notification pretext

Current: Action verb is not bolded

![image](https://user-images.githubusercontent.com/13119842/59477139-e0514c00-8e21-11e9-8574-1610dd20987b.png)

Proposed: Bold the action verb to draw attention to whether it was created, updated or deleted
 - for issue creation: bold **created**
 - for issue assignment: bold **assigned**
 - for issue transition: bold **reopened**, or **resolved**
 - for issue deletion: bold **deleted**
 - for comment creation: bold **commented**
 - for comment updates: bold **edited a comment**
 - for comment deletions: bold **removed a comment**

![image](https://user-images.githubusercontent.com/13119842/59476851-a16ec680-8e20-11e9-9401-94bcbb39c564.png)

Note: You can ignore other formatting changes in the sample screenshot, these are covered by other open issues.

**Comment by mavegaf** [comment]
Hi :wave:  I'd like to take this issue

**Comment by jasonblais** [comment]
Great, thanks @mavegaf! If any questions, let us know

cc @aaronrothschild @levb FYI

**Comment by mickmister** [comment]
Closing per https://github.com/mattermost/mattermost-plugin-jira/pull/404
