### ISSUE TITLE
When posting a response from the Jira plugin, we get React warnings in the console

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#173]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

**Repro steps**:
1. Enable and configure the plugin using steps at https://github.com/mattermost/mattermost-plugin-jira
2. Use "/jira connect" to connect your Mattermost account with Jira
3. Complete the connection flow
4. Hover over a message, click on the "More Actions" (...) menu, and either create or attach an issue using the post menu
5. Complete the flow and submit changes

Observed: JavaScript error in the console
![image](https://user-images.githubusercontent.com/13119842/59545103-d09c3b00-8ee7-11e9-9e68-c165fcad4daf.png)

Expected: No error

**Comment by AGMETEOR** [comment]
I'll take a look at this.
