### ISSUE TITLE
could not insert reporter field of jira when create jira issues

### ISSUE THREAD

**Issue by kolinz** [mattermost/mattermost-plugin-jira#174]
I am using Mattermost 5.12.
I checked this issue when use language settings of Jira are Japanese and Chinese. It could not insert reporter field of jira when create jira issues at Mattermost messages.

As a result, the issue can not be created. 
It works only when the language setting of Jira is English.

language settings of Jira : Japanese
----------------------
![mattermost512_jira_integration_get_messages](https://user-images.githubusercontent.com/16685896/59646195-d11b2700-91b0-11e9-9ee7-07d26b814bb1.png)

language settings of Jira : English
----------------------
![mattermost512_jira_integration_no_messages](https://user-images.githubusercontent.com/16685896/59646667-daa58e80-91b2-11e9-9788-290f39ea1eaf.png)

**Comment by jasonblais** [comment]
Thanks @kolinz for reporting this! Much appreciated it.

When you click on the "Please create your Jira issue manually", what happens? (I just want to confirm the behaviour after this link)

**Comment by jasonblais** [comment]
Thanks @kolinz! I'll share this with our dev team 👍

**Comment by jasonblais** [comment]
We've created a bug ticket to investigate this issue: https://mattermost.atlassian.net/browse/MM-16503

**Comment by jasonblais** [comment]
Fix for this issue has been merged https://github.com/mattermost/mattermost-plugin-jira/pull/195

We expect it to be available in v2.1.

Thanks again for the report!
