### ISSUE TITLE
Add support for intermediate issue status change (eg: open to in Progress)

### ISSUE THREAD

**Issue by prajnadnayak** [mattermost/mattermost-plugin-jira#193]
Currently the plugin only sends notifications when the issue is created,opened,resolved or re-opened. We want to be notified when the issue status is changed to any state.  eg: In progress or when moved to backlog . Could this support be please considered in the future releases?

**Comment by cored** [comment]
@levb This looks like a good one to start with.

**Comment by mickmister** [comment]
Hi @cored, we have a fix in for this issue here https://github.com/mattermost/mattermost-plugin-jira/pull/280 . Sorry for having this ticket open. Thank you for your interest in completing the ticket!
