### ISSUE TITLE
Only messages for "Issue created" are displayed

### ISSUE THREAD

**Issue by GF-EffDee** [mattermost/mattermost-plugin-jira#205]
We don't get messages for events other than "Issue created". According to the logs Mattermost receives notifications for the "missing" events, e.g.:

```
2019-07-05T14:37:31.224+0200    debug   mlog/sugar.go:15        skipping: "abc transitioned foo [FOO-42: asdf](https://jira.xyz.com/browse/FOO-42) from \"Planned\" to \"In Progress\""     {"plugin_id": "jira"}
2019-07-05T14:37:31.226+0200    debug   mlog/sugar.go:15        OK:     {"plugin_id": "jira", "Status": "200", "Host": "mattermost.xyz.com", "RequestURI": "/plugins/jira/webhook?secret=12345&team=someteam&channel=somechannel&user_id=abc%40xyz.com&user_key=abc%40xyz.com", "Method": "POST", "query": "channel=somechannel&secret=12345&team=someteam&user_id=abc%40xyz.com&user_key=abc%40xyz.com"}
```

Versions involved:
* mattermost-jira-plugin v2.0.6
* mattermost-server v5.12.1
* JIRA 7.12.3

**Comment by jasonblais** [comment]
@GF-EffDee Thanks for the report, and for using the plugin! 

1 - Would you be open to sharing a screenshot of the webhook configuration page in Jira, for section "Issue related events"

![image](https://user-images.githubusercontent.com/13119842/60813605-16a09380-a162-11e9-8491-f10765a8b603.png)

2 - Would you know if this is for Jira Core or Jira Software?

**Comment by GF-ZmAno** [comment]
Hey @jasonblais ,
Thank you for getting back to us!
2. we're using JIRA Software.
1. We've tested several configurations of the webhook but unfortunately none seem to work as configured.
We do see POST requests in the nginx access.log of the Mattermost Instance but nothing being logged in mattermost log or posted in the configured Channel.

Attached Image for "Issue realted events"
![image](https://user-images.githubusercontent.com/52664649/60816947-0b1d8e80-a19b-11e9-8f69-f67b0170def2.png)

**Comment by aguilloteau** [comment]
Hi
We have the same issue with following versions : 
- Jira : 8.2.3
- mattermost-server : 5.11.0
- mattermost-jira-plugin : 1.1.1

**Comment by levb** [comment]
This is a result of a conservative decision that we made shipping the updated plugin. To protect webhooks set up with previous versions mattermost-plugin-jira from getting a lot more traffic upon upgrading the plugin, we added an extra layer of plugin-side filtering. As can be seen here, https://github.com/mattermost/mattermost-plugin-jira/blob/7e3884c1f59aab201621c2ab79cd78ca0d7892e8/server/webhook.go#L24-L55 only eventUpdatedReopened, eventUpdatedResolved, eventDeletedUnresolved, eventUpdatedAssignee are turned on by default.

To overcome this, you can add extra flags (parameters) to the webhook URL, from the list in https://github.com/mattermost/mattermost-plugin-jira/blob/7e3884c1f59aab201621c2ab79cd78ca0d7892e8/server/webhook.go#L61-L70. For example, to turn on comment events and changes in priority, add `&updated_comments=1& updated_priority=1` to the end of the webhook URL. Adding `updated_all=1` will enable all supported events.

@aaronrothschild @jasonblais should we document and support these, even though it was not conceived as a real feature?

**Comment by jasonblais** [comment]
@GF-EffDee @GF-ZmAno If you change the assignee of a user, do you get a notification sent to a Mattermost channel?

@levb My hope is that Chris' subscription feature shipping in v2.1 will be the go-to way to subscribe notifications rather than the webhooks. We can document these but I worry it's not a great admin experience. It's very technical and error prone

**Comment by GF-EffDee** [comment]
@jasonblais Appending an "&updated_status=1" to a webhook's URL solves the initial problem. We now get messages for status changes.

**Comment by jasonblais** [comment]
@GF-EffDee Glad it's fixed! For reference, the list of supported events by default can be found here https://github.com/mattermost/mattermost-plugin-jira#11-send-notifications-from-jira-to-mattermost
