### ISSUE TITLE
allow non-Mattermost admins to setup integration

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-plugin-jira#25]
Currently a Mattermost admin must enable Jira, set username, and get secret key. Lets allow anyone to setup integrations similar to what anyone can do with incoming and outgoing webhooks.

**Comment by jasonblais** [comment]
Thank you for the suggestion!

https://github.com/mattermost/mattermost-plugin-jira/pull/61 enables non administrators to subscribe Jira projects to Mattermost channels.

This enhancement is scheduled for Jira v2.1. For latest updates on timelines for Jira v2 releases, see https://github.com/mattermost/mattermost-plugin-jira#2-jira-plugin-v2-roadmap
