### ISSUE TITLE
Allow uppercase in URL?

### ISSUE THREAD

**Issue by marcomujica** [mattermost/mattermost-plugin-jira#27]
If I create a custom webhook in Jira specifying the channel name in lowercase, the plugin works perfectly. If I try using the project.key variable (channel=${project.key}), the URL resolved in uppercase and I get a 404 error. Is there any change I can make to the webhook URL to send the post in lowercase or an edit to the plugin to negate case?

**Comment by marcomujica** [comment]
This works perfectly: https://mattermost.soartech.com/plugins/jira/webhook?secret=secretkey&team=soartech&channel=test

But this: https://mattermost.soartech.com/plugins/jira/webhook?secret=secretkey&team=soartech&channel=${project.key}
Resolved as: https://mattermost.soartech.com/plugins/jira/webhook?secret=secretkey&team=soartech&channel=$TEST

**Comment by levb** [comment]
@marcomujica In Mattermost, when you click on the channel name (menu) in the header line, you can "Rename Channel". In that dialog box you can edit the Channel's URL "name" to match your project key. Will that work for you?

**Comment by marcomujica** [comment]
Unfortunately, no. The channel name is in caps, but the channel URL is lowercase and cannot be changed to upper. The Jira project's key can only be uppercase. I could try using the variable project.id (ie 12345) for the URL and set a friendly name for the channel (ie test). Maybe that'll work.

**Comment by marcomujica** [comment]
That seemed to work. I'll use this method for now, but it would be preferable to use the project key. Perhaps Jira could set up a better-fitting variable.
