### ISSUE TITLE
 Unsupported webhook data: jira:issue_updated_v2.1.0_rc2

### ISSUE THREAD

**Issue by razbag** [mattermost/mattermost-plugin-jira#277]
After we upgraded our mattermost server to version 5.13.2 we're experiencing issues with our Jira integration via the webhook method.

Update from 5.5.0 and in  this version (5.5.0 it is worked for example Resolved)
I already update plugin from 2.0.7 pre-packed to 2.1.0_rc2 and results the same  

Before the upgrade we were notified about opened and closed issues in the respective channel. After the update we only get notifications for opened issues. If someone closes a task in Jira we also see the following error message in our mattermost server log:

{"level":"error","ts":1565268360.034311,"caller":"mlog/sugar.go:23","msg":"ERROR: ","plugin_id":"jira","Status":"400","Error":"Unsupported webhook data: jira:issue_updated"

Thanks,
Razmik

**Comment by mickmister** [comment]
Solved via linked merged PRs above
