### ISSUE TITLE
Server responds with 200 even when post fails due to bad JSON.

### ISSUE THREAD

**Issue by apophisnow** [mattermost/mattermost-plugin-jira#3]
If you send a request to the Jira webhook endpoint with correct secret, channel, etc, but bad JSON (for example {"test": "test"}), the server responds with a blank 200 response instead of an error. No message gets posted to Mattermost.

**Comment by amyblais** [comment]
Hi @apophisnow! Apologies that this got missed earlier - are you still experiencing trouble with this?
