### ISSUE TITLE
405 response does not return Allow header field.

### ISSUE THREAD

**Issue by apophisnow** [mattermost/mattermost-plugin-jira#30]
[RFC 7231](https://tools.ietf.org/html/rfc7231#section-6.5.5) requires an allow header field to be returned with a 405 response. Currently, if hitting the endpoint with a GET request, a 405 response is returned with no Allow header field.

**Comment by levb** [comment]
@apophisnow are you referring to a mattermost-plugin-jira endpoint, and if so which one?  

Also, somewhat out of personal curiosity, was there a specific use-case that triggered this issue report?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
