### ISSUE TITLE
Add support for issue transitions

### ISSUE THREAD

**Issue by sei-dmorda** [mattermost/mattermost-plugin-jira#304]
Our team currently relies on the Hipchat integration within Jira Service Desk to send notifications to a Hipchat room. Now that we are transitioning to Mattermost, we're looking for a way to accomplish the same type of notifications. However, we can't seem to figure out a way to pull that off because it seems the current plugin does not support the functionality we need.

Here's how it works for us now. We configure the Hipchat integration within Jira Service Desk to match the following issues:

```project = PROJECT_NAME AND issuetype in standardIssueTypes() AND "Assignment Group" = "SOME_GROUP" AND assignee in (EMPTY) AND status not in (Resolved, Closed)```

Then, when an issue within the Jira Serve Desk projects transitions to the status "Open", it fires a notification to the room if the issue matches the query above.

![hipchat-transition](https://user-images.githubusercontent.com/12237323/64256495-9b552700-cef1-11e9-9c8c-f47720889a76.png)

Since the plugin only supports a single Jira instance, it would be awesome if we could accomplish this with a webhook. I'd prefer a webhook because we have the Mattermost Jira plugin configured to use one of our other Jira servers and configure additional notifications via webhooks for our Jira Service Desk.

**Comment by aaronrothschild** [comment]
Have you tried setting up a Webhook in jira to point to a MM channel and use this JQL for the webhook query:
`project = PROJECT_NAME AND issuetype in standardIssueTypes() AND "Assignment Group" = "SOME_GROUP" AND assignee in (EMPTY) AND status not in (Resolved, Closed) AND status changed TO Open`

**Comment by levb** [comment]
This should be possible to accomplish with /jira subscribe improvements slated for the 2.3 release.

**Comment by mickmister** [comment]
The issue with supporting certain transitions should be solved along with other transition fixes, unless there are more event types being used in different Jira systems/versions. cc @joewaitye so you're aware of this ticket

I'm not sure if the subscriptions feature is related to this issue other than making it easier to configure. I think the issue is whether the webhook handler recognizes the state transition or not.

**Comment by jfrerich** [comment]
@levb, @mickmister. It has been a while since this ticket has been updated, but aren't webhook state transitions now recognized?  

Isn't this an example of the state getting updated, a webhook triggered and the state change displayed in Mattermost?
![image](https://user-images.githubusercontent.com/7575921/74626697-0304d480-5116-11ea-9ab7-15afec255f77.png)

**Comment by mickmister** [comment]
@jfrerich With the current state of subscriptions, we cannot make a subscription such as "when the status changes to x". [This ticket](https://github.com/mattermost/mattermost-plugin-jira/issues/440) is meant to solve that.

Once that ticket is implemented, using `Issue Updated: Status`, along with using the appropriate status(es) you want to capture in the filter fields of the subscription, you will be able to make the correct subscription.

**Comment by sei-dmorda** [comment]
@mickmister - I noticed your comment above seemed to indicate that the transition issue I'm running into might be solved. Is that true?

Just to clarify, we have two Jira servers. One is configured to use the Mattermost jira plugin subscription approach and the other needs to use a normal Jira webhook notification since the jira plugin only supports a single server at this time. So I need to be able to detect that status transition using the normal Jira webhook approach.

**Comment by mickmister** [comment]
> I noticed your comment above seemed to indicate that the transition issue I'm running into might be solved.

@sei-dmorda I see that the HipChat integration within Jira allows for a query such as "when a specific transition occurs". Unfortunately, the options Jira allows when setting up webhooks are not granular enough to create a webhook for this sort of query. You may want to research [workflow post functions](https://developer.atlassian.com/server/jira/platform/webhooks/#adding-a-webhook-as-a-post-function-to-a-workflow) to see if you can have the transition trigger a specific webhook. However, creating a subscription in Mattermost with the configuration I describe in my previous comment should also be able to accomplish this, once [this ticket](https://github.com/mattermost/mattermost-plugin-jira/issues/440) is implemented.

We are currently in active discussion of the implementation of supporting multiple Jira instances. It is a large task that needs to be executed with backwards compatibility in mind. There are also several UX issues that come into play for a connected user to be able to seamlessly interact with the intended server in the context of different user actions. These are described in depth [here](https://mattermost.atlassian.net/wiki/spaces/JM/overview).

Thank you very much for expressing your pain points. They certainly give the team direction what needs to be implemented. Please stay tuned, and feel free join the conversation and share your thoughts on our community server in the [Jira plugin channel](https://community.mattermost.com/core/channels/jira-plugin).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
