### ISSUE TITLE
"Create Jira Issue": the comment posted back to channel should include the issue summary

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#312]
Currently, the comment looks like:

`Created a Jira issue [MM-18150](https://mattermost.atlassian.net/browse/MM-18150)`

Proposed:

`Created a Jira issue [MM-18150](https://mattermost.atlassian.net/browse/MM-18150): Plugin panic traces in production should not be lost`

https://mattermost.atlassian.net/browse/MM-18151

**Comment by SezalAgrawal** [comment]
Can I take this up?

**Comment by levb** [comment]
@SezalAgrawal of course, thank you for contributing! Let me know if you need any help.

**Comment by levb** [comment]
@SezalAgrawal just checking in, can we help you with this ticket?

**Comment by SezalAgrawal** [comment]
Hi @levb, I am still working on it. Will keep you updated.

**Comment by levb** [comment]
@SezalAgrawal Hi, a gentle ping, are you still intending to finish this ticket?

**Comment by SezalAgrawal** [comment]
Hi @levb, I have been caught up with some work and couldn't make time to complete it. I really appreciate your patience. I have unassigned myself from this task. Looking forward to make more contributions to mattermost community.

**Comment by mickmister** [comment]
I think this ticket is rendered obsolete by https://github.com/mattermost/mattermost-plugin-jira/issues/420. Closing this ticket
