### ISSUE TITLE
Add server-side validation to Subscription APIs

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#313]
Subscription management APIs, https://github.com/mattermost/mattermost-plugin-jira/blob/f0cd373a5bcd8fba161f19b595bf574f10bd9294/server/subscribe.go#L527, should implement server-side data validation, they currently rely on the webapp submitting valid data.

https://mattermost.atlassian.net/browse/MM-17903

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by imazik** [comment]
hi @levb i would like to take it

**Comment by levb** [comment]
@imazik are you intending to finish this ticket, or should we put it back in the "Up for grabs"?

**Comment by RajatVaryani** [comment]
@levb Can you please elaborate more on the validations required on server side?

**Comment by levb** [comment]
@mickmister This was your ticket, can you please elaborate?

**Comment by jfrerich** [comment]
@mickmister, does server-side validation implementation still need to be added?

**Comment by mickmister** [comment]
@jfrerich Nope, closing per https://github.com/mattermost/mattermost-plugin-jira/pull/432

**Comment by jfrerich** [comment]
@mickmister Awesome!
