### ISSUE TITLE
Add unit tests for DM notifications from Subscribe

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#314]
Currently, there are server-side unit tests that test that the legacy webhooks post messages to channels, see https://github.com/mattermost/mattermost-plugin-jira/blob/f0cd373a5bcd8fba161f19b595bf574f10bd9294/server/webhook_http_test.go#L660.

We should add tests that similarly verify that direct post notifications are made.

Jira: https://mattermost.atlassian.net/browse/MM-18122

**Comment by dnguy078** [comment]
I can take a look at this

**Comment by levb** [comment]
@dnguy078 Thank you for taking his on, let us know if you need help/pointers. The best forum is https://community-daily.mattermost.com/core/channels/jira-plugin

**Comment by levb** [comment]
Hi @dnguy078, are you still interested in this ticket?

**Comment by dnguy078** [comment]
Hi, @levb I opened a pr https://github.com/mattermost/mattermost-plugin-jira/pull/363/files. I left a few outstanding questions in the pr.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
