### ISSUE TITLE
Show user their settings with `/jira settings`

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#315]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

-----

#### Summary

Currently, `/jira settings` command requires a `name`, `value` and sets them. 
Add support for `/jira settings` (no arguments) to display all settings, in a user-friendly format. The only setting we have now is notifications anyway.

https://mattermost.atlassian.net/browse/MM-18166

**Comment by simross** [comment]
@levb I would like to work on this.

**Comment by levb** [comment]
Thank you! Let us know if you need help/pointers. The best place to reach the team is https://community.mattermost.com/core/channels/jira-plugin
