### ISSUE TITLE
Isolation between jira projects

### ISSUE THREAD

**Issue by zetaab** [mattermost/mattermost-plugin-jira#319]
We tried this jira plugin. However, it looks like this does not have any isolation in mattermost side? For instance, I can subscribe to jira organizations which I do not have access at all - and also those events will be published to channel. This is quite huge issue in security perspective. This should work in similar way that github mattermost plugin is working (check does user have access to organization). Are we doing something wrong or is this plugin working as "planned"? 

It looks like the isolation is handled in Jira server side - but then we can have only one webhook per mattermost installation. It does not work.

**Comment by levb** [comment]
There are several issues indicated here, however the key request appears to properly support multiple Jira instances from a single Mattermost instance, i.e. establish and display their identities, use separate webhook URLs/secrets, etc.

**Comment by aaronrothschild** [comment]
@levb This is obviously a departure from our architecture, so i'll set some time up to discuss this sort of approach.

**Comment by mickmister** [comment]
> Currently with mattermost jira plugin it is possible to subscribe to `management` events and I can see everything what is happening there.

@zetaab Are you using the `/jira subscribe` command to create subscriptions? When we fetch the project information for creating a subscription, we use the logged in MM user's Jira account to authenticate with Jira. If the user does not have permissions/access to the project in Jira, there will be an error returned from Jira.

Can you confirm that you are able to create a subscription for a project that you would expect to be unavailable? If so, the access control issue is on Jira's side, as we rely on Jira to return the 403 error when we fetch the project info. The plugin has no stored knowledge of which project memberships users have.

**Comment by bbodenmiller** [comment]
> @zetaab Are you using the `/jira subscribe` command to create subscriptions? When we fetch the project information for creating a subscription, we use the logged in MM user's Jira account to authenticate with Jira. If the user does not have permissions/access to the project in Jira, there will be an error returned from Jira.
> 
> Can you confirm that you are able to create a subscription for a project that you would expect to be unavailable? If so, the access control issue is on Jira's side, as we rely on Jira to return the 403 error when we fetch the project info. The plugin has no stored knowledge of which project memberships users have.

What happens if a users Jira access changes - does it properly unsubscribe them? Am I correctly understanding that the plugin basicly expects a firehouse of Jira data and then the plugin secures who can see the data? I doubt most Jira admins of large instances would allow this. Users need a way to add project specific webhooks and they need a way to do it without involving the Mattermost admin.

**Comment by levb** [comment]
@bbodenmiller @zetaab understood and acknowledged. When we developed `/jira subscribe` we were not able to find a robust mechanism for creating user-level subscriptions from the Jira end. While the `firehose` approach works for some simpler use-cases, we need to find a better way going forward. Specific suggestions and ideas would be great!

**Comment by mickmister** [comment]
https://github.com/mattermost/mattermost-plugin-jira/pull/432

**Comment by bbodenmiller** [comment]
> Solved with #432

@mickmister it appears that still does not solve a number of isilotation issues:
* Firehouse of data still required - this sounds like deal breaker for many Jira admins
* Mattermost admin must still create connection to Jira server. Why not let any user add connection to channel?

**Comment by mickmister** [comment]
> Firehouse of data still required - this sounds like deal breaker for many Jira admins

@bbodenmiller I'm not sure if we have a way around this at the moment. If sending over data about specific projects is a problem, you can whitelist or blacklist certain projects within the JQL of the webhook. Ideally the functionality is configurable entirely on Jira's side. When researching options for the subscriptions feature, I didn't come across the necessary functionality like this. If it does exist, we can certainly work on adding it to the product.

> Mattermost admin must still create connection to Jira server. Why not let any user add connection to channel?

There are two layers of control to determine who can create subscriptions. You can filter on Mattermost role and Jira role. With these settings, you can allow any user to create a subscription.

![image](https://user-images.githubusercontent.com/6913320/102175576-cc9b0180-3e6d-11eb-8445-6b5e3b0812f2.png)

**Comment by bbodenmiller** [comment]
@mickmister looking at https://mattermost.gitbook.io/plugin-jira/admininstrator-guide/administrator-slash-commands it says an "administrator" must perform Jira instance installation as well as manage channel subscriptions. Is that perhaps just a documentation oversight?

Additionally looking at https://mattermost.gitbook.io/plugin-jira/setup/configuration, do all Jira servers you want to connect to Mattermost use the same Jira plugin webhook URL and secrets? Currently the page appears to be wrote assuming just one Jira server is going to be connected to Mattermost. It's not ideally to have to give out same secret to multiple Jira server admins.

> you can whitelist or blacklist certain projects within the JQL of the webhook

Where can I find more details on this? I would have expected this under https://mattermost.gitbook.io/plugin-jira/setup/configuration#step-2-configure-webhooks-on-the-jira-server.

**Comment by mickmister** [comment]
@bbodenmiller Thanks so much for pointing these out :+1:

@justinegeffen @aaronrothschild Let's get together to discuss adding these items to the documentation

**Comment by justinegeffen** [comment]
That sounds good to me, @mickmister. We can discuss further in the Integrations Documentation channel.
