### ISSUE TITLE
compatibility issue with mattermost 5.8.0

### ISSUE THREAD

**Issue by turdusmerula** [mattermost/mattermost-plugin-jira#32]
I'm testing the plugin v1.1.1 on our mattermost instance, the plugin setup is okay and is configured okay but when testing with curl I get an error 500.
There is not that much clue on what's going wrong on mattermost logs:
```
{"level":"debug","ts":1552652119.5225964,"caller":"app/plugin_api.go:650","msg":"HTTP request","plugin_id":"jira","Host":"mattermost.devinternet.net","RequestURI":"/plugins/jira/webhook?secret=dMn2ZBjPMN5ogORmsFCutxexOy55hk74&team=devops&channel=jira","Method":"POST","query":"channel=jira&secret=dMn2ZBjPMN5ogORmsFCutxexOy55hk74&team=devops"}
{"level":"debug","ts":1552652119.5253737,"caller":"app/plugin_api.go:650","msg":"Failed to serve HTTP request","plugin_id":"jira","Error message":"Failed to create post"}
```
My curl command seems correct:
`curl -v --insecure "https://mattermost.devinternet.net/plugins/jira/webhook?secret=dMn2ZBjPMN5ogORmsFCutxexOy55hk74&team=devops&channel=jira" --data '{"WebhookEvent":"issue_created"}'`

Is it a compatibility issue?

**Comment by jasonblais** [comment]
Hey @turdusmerula, for the curl command, `{"WebhookEvent":"issue_created"}` isn't enough data to trigger a notification post.

To troubleshoot why notifications aren't posted, can you help try run these steps: https://docs.mattermost.com/integrations/jira.html#why-doesn-t-my-jira-webhook-post-any-messages

**Comment by turdusmerula** [comment]
Hello @jasonblais, I configured according to the documentation without any success.
Requests from jira with full payload gives the same error 500 and logs are not really verbose inside mattermost. 
Is there a debug mode I can activate?

**Comment by jasonblais** [comment]
@hanzei I'm wondering if you'd have thoughts on further troubleshooting steps?

**Comment by hanzei** [comment]
Hey @turdusmerula,

What kind of requests do you tested? Currently `jira:issue_created`, `"jira:issue_updated` and `jira:issue_deleted` are supported.

**Comment by turdusmerula** [comment]
I managed to have it work with curl and jira, I was missing the `jira:` before my message type.
However It only worked with `created` and `deleted` event types, I get an error type 500 from a `jira:issue_updated` event webhook.

**Comment by hanzei** [comment]
> I managed to have it work with curl and jira, I was missing the `jira:` before my message type.

Glad it works now. :+1: 

> However It only worked with `created` and `deleted` event types, I get an error type 500 from a `jira:issue_updated` event webhook.

Do you see a log message? Did you include a `ChangeLog` element with at least one `Items` it it? See https://github.com/mattermost/mattermost-plugin-jira/blob/v1.1.1/server/webhook.go#L51-L57 of the required message structure.

**Comment by turdusmerula** [comment]
After several tests I was able do see that the `jira:issue_updated` is only treated by the plugin from a state change for the issue, adding a comment or other modification are not handled (the `ChangeLog` is effectively not present in those cases).

**Comment by jasonblais** [comment]
@turdusmerula Correct - for issue updated events, only status changes when the ticket is reopened, or when resolved/closed are supported.

That said, support for more issue updates such as comments and other modifications is planned, with some work already begun: https://github.com/mattermost/mattermost-plugin-jira/pull/22

**Comment by turdusmerula** [comment]
Thank you for your help :)
