### ISSUE TITLE
jira plugin bot does not pull in human readable account id on channel update

### ISSUE THREAD

**Issue by atkasa** [mattermost/mattermost-plugin-jira#322]
The jira integration is working quite well, aside from one minor detail (not a deal breaker, but I can't figure out if this is a know issue or misconfiguration?)

Jira bot posts into a #jira-updates channel on our mattermost server, each time someone references a team member (using @membername) in jira on a comment, update, or new ticket -- the associated message in #jira-updates shows the ticket, but the @membername is shown in this format:

[~accountid:5c45e4d6cc3a1d3d8a2b9117]

does anyone know how I can get that to map to the mattermost membername, or just to a text string with the jira username instead of the internal account id?

**Comment by aaronrothschild** [comment]
@atkasa This issue arises on Jira-cloud-only because of some changes they implemented around GDPR and not exposing the userID to outside systems.  We will have a fix for this particular issue with Jira 2.2 or 2.3 shortly, please stay tuned.

**Comment by levb** [comment]
This should be resolved (only for the Account IDs that have been connected from Mattermost) in https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v2.2.0.

**Comment by Grienauer** [comment]
just to clear it a bit more (because it took a while for my to get this working):
each user has to connect their jira account to mattermost via "/jira connect" command.
