### ISSUE TITLE
Error installing Jira when key is too long

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#330]
The `key` value that is generated to install Jira is based on the site URL. In some cases the key will become long and prevent you from installing Jira. 

The user will see a misleading error on cloud `An error occurred while provisioning the user for this app. Please try installing it again, and if then problem persists then contact Atlassian support.`
 
On server the Jira UI will show `error` with no details when attempting to create the application link 

We need a solution where the key would still be based on URL to keep it unique but enforce a maximum length.  

Steps (Cloud):
- Login as an admin to a server with a long URL such as https://mattermost-server-pr-12407.test.mattermost.cloud
- Enable the Jira Plugin and use the slash command to install Jira
- Copy the path to the resulting .json to the clip board (in this case the key would be `mattermost_https_mattermost_server_pr_12407_test_mattermost_cloud`)
- Login to Jira as an Admin and navigate to Manage apps
- Click Upload apps and enter the .json
**Observed:** jira UI shows the error `An error occurred while provisioning the user for this app. Please try installing it again, and if then problem persists then contact Atlassian support.`

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by DHaussermann** [comment]
@aaronrothschild and @levb, Please confirm that this is suitable to address as help wanted and contains enough detail before I add the label.

**Comment by levb** [comment]
This is awesome, @DHaussermann! My implementation suggestion would be keep it as is if under 32, otherwise replace with a UUID.

**Comment by aaronrothschild** [comment]
@levb Hacktoberfest?

**Comment by SezalAgrawal** [comment]
Can I take up this task?

**Comment by levb** [comment]
@SezalAgrawal of course! Thank you for contributing!

**Comment by levb** [comment]
@SezalAgrawal Hi, are you still interested in this ticket?

**Comment by SezalAgrawal** [comment]
Hi, @levb, I would like to continue working on this.

**Comment by AGMETEOR** [comment]
@levb I'll pick this up.

**Comment by mickmister** [comment]
Thanks @AGMETEOR! It's all yours :slightly_smiling_face:

**Comment by AGMETEOR** [comment]
Worked on this using @levb 's suggestion here
> My implementation suggestion would be keep it as is if under 32, otherwise replace with a UUID.
