### ISSUE TITLE
Document that Jira mentions need to be turned on by the authenticated  user

### ISSUE THREAD

**Issue by matterdoc** [mattermost/mattermost-plugin-jira#336]
Mattermost user `aaron.rothschild` from https://community.mattermost.com has requested the following be documented:

```
https://jsoftconnector.atlassian.net/wiki/spaces/JS/pages/765001735/Mattermost+-+Direct+message

End users:  Get notified personally by the Jira bot whenever you are mentioned or an issue that is assigned to you is updated: You need to type `/jira notifications....`
```

See the original post [here](https://community.mattermost.com/_redirect/pl/x7kic6kxi3dgdbaw8zy3kmmfjc).

_This issue was generated from [Mattermost](https://mattermost.com) using the [Doc Up](https://github.com/jwilander/mattermost-plugin-docup) plugin._

**Comment by jfrerich** [comment]
@aaronrothschild, Is this an item that you are going complete, or does it need to be designated to a developer?

**Comment by aaronrothschild** [comment]
@jfrerich I thought I had updated the Gitbooks docs to have that referenced, but it doesn't seem to be there.  I'll add it to the docs. Just so I'm clear - is the default that it does NOT notify users via DM?

**Comment by jfrerich** [comment]
@aaronrothschild, I am not quite sure what the default is and would need to test it. Can you give that a try?  I'm not sure of the defaults

**Comment by jfrerich** [comment]
On by default
