### ISSUE TITLE
`/jira transition` names should also ignore whitespace

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#337]
Currently, to transition an issue to the `In Progress` state one needs to type, `/jira transition XYZ-123 in prog`. The ask is that `/jira transition XYZ-123 inprog` also work.

**Comment by imazik** [comment]
hi @levb i would like to take it

**Comment by fm2munsh** [comment]
It doesnt look like @imazik is working on this, mind if I grab it?
