### ISSUE TITLE
Webhooks and subscriptions should support `Component` field in issues updates

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#338]
When processing issue updated webhook messages, certain fields are recognized and treated specially. See, for example, the handling of the `Reporter` field in https://github.com/mattermost/mattermost-plugin-jira/blob/bbac7f8410142319c3bb8c31d98cd585a0997cb0/server/webhook_parser.go#L161.

Need to add similar support and tests for the `Component` field.

Originally https://mattermost.atlassian.net/browse/MM-19170

**Comment by cored** [comment]
@levb I would like to work on this.

**Comment by levb** [comment]
@cored thanks for taking this up!

**Comment by cored** [comment]
@levb I've been off the grid due to moving to a new apartment, however, I am planning on finishing the work this week.

**Comment by levb** [comment]
@cored ping, are you still working on this?

**Comment by mickmister** [comment]
Closing per https://github.com/mattermost/mattermost-plugin-jira/pull/411

**Comment by cored** [comment]
@levb Sorry for the delay. I am dealing with some family matters. Sorry again for the late response.

**Comment by levb** [comment]
@cored no problem, and hope everything works out.
