### ISSUE TITLE
/jira transition should use transition name instead of state

### ISSUE THREAD

**Issue by gpr** [mattermost/mattermost-plugin-jira#346]
The state is unique but you may have several transitions to a given state (typically to move to a state by changing automatically some fields).

    State1 -- transition1 --> State2
    State1 -- transition2 --> State2
In such case the command `/jira transition ISSUE-1 State2` does not work and we get the following error:
```
please be more specific, "State2" matched several states: "State2, State2"
```
It seems reasonable to use the transition name instead of the destination state name.

**Comment by qiell** [comment]
Hi @gpr I'd like to work on this.

**Comment by aaronrothschild** [comment]
Hey @qiell Thanks for taking this on, I've removed the "up for grabs" label.

**Comment by levb** [comment]
@qiell Are you still interested in working on this ticket?

**Comment by qiell** [comment]
Hi @levb, 
Sorry for my late response. I was on leave and in no network zone from last 20 days. 
I'll work on this and raise a PR ASAP.

Thank you. :)

**Comment by mickmister** [comment]
@jfrerich I believe the `/jira transition` functionality is more or less being replaced by the new transition functionality being introduced to `/jira view` https://github.com/mattermost/mattermost-plugin-jira/pull/454. I'm not sure if this ticket is still relevant

**Comment by jfrerich** [comment]
@mickmister, thanks for letting me know.  If the plan is to remove the `/jira transition` command, then I'd agree we can also close this issue.

**Comment by mickmister** [comment]
> If the plan is to remove the `/jira transition` command, then I'd agree we can also close this issue.

@aaronrothschild Since the `/jira view` command will now support transitioning an issue by selecting the transition with a select box, do you agree that we should retire the `/jira transition` command?

**Comment by levb** [comment]
I don't understand the logic here. Why do I need to view an issue? Why retire the transition command?

**Comment by jfrerich** [comment]
Let's complete the spec for this ticket. 

Although we will have the ability to transition an issue from `/jira view` with #454, let's leave the `/jira transistion` command and keep the original scope to use transition names instead of state names.  Any objections?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
