### ISSUE TITLE
Feature request. / command for issue overview 

### ISSUE THREAD

**Issue by scottleedavis** [mattermost/mattermost-plugin-jira#37]
It has been useful to have an issue overview in channel discussion when no public access to jira is available.  The integration slash-jira does this but it might be more appropriate in the plugin.
![290BD180-2BB8-47B4-9104-7CBFE8850007](https://user-images.githubusercontent.com/2914443/56433675-923b2480-6286-11e9-9929-1c185b36cb6e.png)

On the spot info more than Autolink
e.g. /jira ASDF-1234

**Comment by jasonblais** [comment]
Anyone interested contributing? Here are some additional considerations:

Add `/jira view <issue-key>` command where <issue-key> refers to the Jira issue key such as "MM-14151"

Notes:
1. Typing the command "/jira <issue-key>" performs the same action as "/jira view <issue-key>"
2. When successful, the command returns an ephemeral message back to the channel the user posted their command. The UI should match that specified at https://github.com/mattermost/mattermost-plugin-jira/issues/86
3. Error cases:
 - If user doesn't have permissions to view the issue, return ephemeral message "You do not have the appropriate permissions to view the issue. Please contact your Jira administrator."
 - If "/jira view" is posted, return ephemeral message "Please specify an issue key in the form `/jira view <issue-key>`."
 - If <issue-key> is not found, return ephemeral message "We couldn't find the issue key. Please confirm the issue key and try again."

**Comment by scottleedavis** [comment]
Hey, I am interested @jasonblais ! 👍

**Comment by jasonblais** [comment]
This is now scheduled for a Mattermost staff team member to work on next week, as part of Jira v2.1.0 release

**Comment by jasonblais** [comment]
This is submitted here https://github.com/mattermost/mattermost-plugin-jira/pull/160

**Comment by jasonblais** [comment]
This was added with https://github.com/mattermost/mattermost-plugin-jira/pull/160, closing. Expecting to be available in v2.1 release.
