### ISSUE TITLE
SSL error when atempting to install mattermost app on Jira cloud

### ISSUE THREAD

**Issue by pmaurais** [mattermost/mattermost-plugin-jira#387]
When I try to upload my atlasian-connect.json file to a Jira cloud instance I get the following errors, 

From Jira Cloud : `An SSL error occurred when we tried to contact the app host at https://www.xxxxxx.com/plugins/jira/ac/atlassian-connect.json. Please try again later or contact the app vendor. See also Troubleshooting SSL issues in the developer documentation.`

From my logs on the mattermost server `{"level":"error","ts":1574016761.5486608,"caller":"http/server.go:3010","msg":"http: TLS handshake error from 18.234.32.228:53108: remote error: tls: unknown certificate","source":"httpserver"}
`

I have TSL set up on the site, using a certificate signed by Sectigo Limited

**Comment by levb** [comment]
My gut instinct is that Jira has a limited set of supported CAs, and errors out if it's not. Will need to check with Atlassian.

**Comment by levb** [comment]
@pmaurais Can you perhaps try the diagnostics described in https://confluence.atlassian.com/cloudkb/cloud-applinks-and-ssl-691011834.html?

**Comment by levb** [comment]
Closing since there's been no response.
