### ISSUE TITLE
[MM-19529] Gracefully handle when plugin bundle reloads at runtime

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#390]
#### Summary

When a plugin is disabled then re-enabled, a websocket event is sent to the client saying to fetch the bundle again. This can cause the Jira plugin bundle to malfunction, and makes client-side plugin functionality break.

The webapp side of the plugin should be resilient to this and should allow for loading of the plugin multiple times.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19529

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by mickmister** [comment]
FWIW this is very intermittent, and I do not have a direct reproducible cause. It may be the case that there is nothing to fix here. An error occurs sometimes upon loading the plugin as described here:

https://community.mattermost.com/core/pl/ka99epk17iyyudrgmt4iqfn65c

`Error: You attempted to set the key 'display_name' with the value '""' on an object that is meant to be immutable and has been frozen.`

This error is unrelated to the plugin's source code, but can occur on plugin startup at line https://github.com/mattermost/mattermost-plugin-jira/blob/b5b54a1ebb27156a9734c7fe991455b6619b2b5e/webapp/src/plugin.tsx#L22

I do not recall if this is the error that occurs upon re-enabling the plugin. If it is, there is nothing to fix in the plugin. Rather, the fix would need to be applied to the `mattermost-webapp` or `mattermost-redux` repo.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
