### ISSUE TITLE
[MM-18811] Show different instructions to end-users vs sysadmins

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#391]
#### Summary

`/jira help` need to have slightly different output based on if the user is a system admin or not. Currently, the output has a section for admins only, but we want to only show this text to admins, and remove this section for non-admins.

So the help text pertaining to `/jira install` and `/jira uninstall` needs to be hidden from non-admins.

In addition to this, the `/jira subscribe list` command should show for admins in the `/jira help` output. It is currently not in the help text. This command's help text should display:

`List of Jira Notification subscription rules across all channels.`

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18811

**Comment by mickmister** [comment]
@aaronrothschild Could you please approve the wording for `/jira subscribe list`:

> List the subscriptions configured across all channels of your Mattermost instance.

**Comment by aaronrothschild** [comment]
`List of Jira Notification subscription rules across all channels`

**Comment by arjunlather** [comment]
I'd like to take a stab at this.
