### ISSUE TITLE
[MM-18811] Allow system admins to provide a block of text to display in output of `/jira help`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#392]
#### Summary

Admins may want to tell end-users some specific instructions/information pertaining to their Jira instance, or usage of the Jira plugin. The admin should be able to enter this text in the settings for this plugin in the system console. This will require a new config setting for the plugin.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18811

**Comment by aaronrothschild** [comment]
More context: 
- Some Jira instances are intended for Service Desk Usage other for Software Development
- Some Jira instances may require their IT admin team to setup notifications to Mattermost channels
- Some Jira instances are handled by specific people and require instructions on how to contact them.

The idea here - provide a simple way for MM admins to provide some extra "help/direction" to their users when using the plugin that may be custom to their organization.

For example the sample text might be inserted into the help text when a user types in `/jira help`:

"If you encounter issues - please contact Corporate IT at @IT-support channel.  If you require Jira notifications for your project - send a note to Jira IT here: jirait@corporate.com" 

"Reminder: Jira Service Desk issues should be logged via Jira directly."

Then it would render something like:
![image](https://user-images.githubusercontent.com/915956/70434403-f63e7300-1a38-11ea-8c17-eae42b86bce6.png)

Use simple quotes or a codeblock to indicate the message from the admin has been appended into the help message.  Paste a screenshot if you need some help with design/looks.

**Comment by themaverikk** [comment]
I'd like to work on this.

**Comment by themaverikk** [comment]
@aaronrothschild @mickmister Can you please have a look at these screenshots and let me know if they are good to go ahead with.
![Admin enter extra help text setting](https://user-images.githubusercontent.com/35112571/71008717-1643f580-210f-11ea-94a5-a52d572d0081.png)
![Uploading screenshot with admin extra help text.png…]()

**Comment by aaronrothschild** [comment]
@themaverikk Looks good, I'm going to tag @asaadmahmood for his comments when he's back from vacation.
