### ISSUE TITLE
[MM-17816] Reporter is not automatically set for `/jira create` on Jira Server, when required field is missing

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#393]
#### Summary

This occurs when using the `/jira create` modal, and there are required fields not supported by the modal. When the user navigates to the issue to finish filling out the form, the reporter is not assigned, when it should be set to the current user.

This only occurs on Jira Server.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19256

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by AGMETEOR** [comment]
@mickmister I want to give this a try.

**Comment by jfrerich** [comment]
Thanks again, @AGMETEOR!  I'll remove the HW label.

**Comment by AGMETEOR** [comment]
Hello @jfrerich and @mickmister , so I tried to reproduce this bug following the repro steps from the ticket. I am not sure if what I reproduced matches what's in the issue description, so, I took some screen shots from what I saw. Please confirm whether I am on the right track.

* Step 1: I added a custom field of type `Date picker` to my Field Configuration scheme (the default)
* Step 2: I made it required
* Step 3: I tried to create a bug type issue from Mattermost and saw this output from Jira bot
![Screen Shot 2020-02-04 at 12 54 48](https://user-images.githubusercontent.com/28563179/73734503-cbc61900-474e-11ea-8438-b400c4fff8e0.png)

* Step 4: Clicked on the link and saw this
![Screen Shot 2020-02-04 at 12 55 09](https://user-images.githubusercontent.com/28563179/73734578-e8625100-474e-11ea-93bf-65e79fc85d2e.png)
 
So, if I understand this well, what we want is to have the reporter already set when we arrive on that second screen shot in step 4?

It also looks like after I have added the reporter manually, there's no input to add the unsupported field and consequently I can't create the issue.
