### ISSUE TITLE
[MM-19792] Implement label search select box

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#394]
#### Summary

The user should be able to use server-side autocomplete search for labels.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-19792

#### Additional Info

https://community.atlassian.com/t5/Answers-Developer-Questions/How-do-I-use-the-JIRA-API-to-get-a-list-of-label-options-for-a/qaq-p/537723

In the CreateIssueMetadata, “Labels” come with an “autoCompleteUrl” like this:

`https://mmtest.atlassian.net/rest/api/1.0/labels/suggest?query=`

`https://mmtest.atlassian.net/rest/api/1.0/labels/suggest?customFieldId=10071&query=` for custom label fields

Here’s an example: https://github.com/mattermost/mattermost-plugin-jira/blob/59ded5f9c21a6fbcb2088dc9c4fd39a73751cc1d/webapp/src/testdata/cloud-get-create-issue-metadata-for-project-many-fields.json#L138

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by AGMETEOR** [comment]
@mickmister I'll pick this up.

**Comment by AGMETEOR** [comment]
@mickmister Are supposed to add a SelectBox on the form in the CreateModal where a user can attach labels?

**Comment by mickmister** [comment]
@AGMETEOR I apologize for the lack of an explanation of the use case. This ticket was made so the label select box could be used in the Subscriptions modal, though it would also be very useful in the CreateIssue modal.

Currently, the Subscriptions modal requires the user to enter the labels by value, and does not have any autocomplete. This works because the labels do not have IDs associated with them when they come through the webhook events. Being able to query the labels in the form would be a huge UX improvement.

**Comment by AGMETEOR** [comment]
@mickmister looks like we use [go-jira](https://github.com/andygrunwald/go-jira) to provide a client that interacts with the API. The API version used is `2` while this issue's info suggests using `1.0`.

The equivalent of 1.0's `https://mmtest.atlassian.net/rest/api/1.0/labels/suggest?query=` is `https://mmtest.atlassian.net/rest/api/2/jql/autocompletedata/suggestions?fieldName=labels&fieldValue=c` in 2.0

Issues
----
* There's currently no way of filtering out the labels based on project
* Looks like the go-jira client library doesn't implement any autocomplete

Work around
-----
* Pull in all labels regardless
* Add an autocomplete method to the plugin client interface

Any comments?
