### ISSUE TITLE
[MM-18168] Support better changelog display for multiselect options

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#395]
#### Summary

Currently, when a multiselect field's value changes, we use the `fromString` and `toString` that Jira gives us in the changelog. Unfortunately, Jira does not provide much info in the changelog for multiselect fields.

There are two improvements to be made here:

1. For label fields, include the `toString` to the output to show the user the current state of the field. This will work on Jira Cloud and Jira Server.

2. For every other kind of multiselect, look through the issue payload and find the field's current value. This will only work with Jira Cloud.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18168

#### Additional Info

Consider this situation: The issue currently has `version 1` set to the `fix version`. Adding `version 2` will have this in the changelog:

```
"changelog": {
    "id": "12630",
    "items": [
        {
            "field": "Fix Version",
            "fieldtype": "jira",
            "fieldId": "fixVersions",
            "from": null,
            "fromString": null,
            "to": "10000",
            "toString": "version 2"
        }
    ]
}
```

`version 1` is not present, so we need to parse the rest of the issue payload in order to find the current value of the field. This is only possible with Jira Cloud, since Jira Server does not provide a `fieldId` here, and the field values are expressed with the `fieldId` in the other portion of the issue payload. We could fetch the issue from Jira's API for Jira Server, but we should not hit Jira's API for every webhook call. Curious what you think about this @levb and @cpoile 

![image](https://user-images.githubusercontent.com/6913320/69119861-cb7a8380-0a65-11ea-8968-7155bf86b313.png)

It should say something like: `... added fix version "version 2" to the issue. The fix version value is now: [version 1, version2]`

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
