### ISSUE TITLE
Generated JQL doesn't work, if Jira is set to Non-English languages

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-jira#400]
Hi,
I just gave 2.3.0-rc1 a test.
When creating a new subscription using labels the German translation "Stichwörter" is used. This generates a JQL like:

`Project = IT AND IssueType IN (Serviceanfrage) AND Stichwörter IN (test)`

Problem is, that "labels" is translated to German in the Mattermost UI, but must not be translated when generating the JQL. The generated JQL does not work. It should be:

Project = IT AND IssueType IN (Serviceanfrage) AND labels IN (test)

Will there be a support for the components field? This gives us much more functionality than labels?

Otherwise: GREAT WORK! APPRECIATED!!!

**Comment by jprusch** [comment]
Hi,
not sure, if this is only a UI problem. I set the Jira language to English & checked the subscriptions in MM: All fine. So maybe the generated JQL preview is language dependent but the executed JQL is not.
I already set up all our service desk channels to only display the relevant issues. This is really great!

**Comment by levb** [comment]
Seems like the JQL preview should be using "system" names as opposed to the display names of the fields. It appears that the actual filtering is working correctly.

**Comment by mickmister** [comment]
The JQL search inside of Jira does not allow you to use the system names. This is why the display names are used instead.

The JQL preview output is not used to handle Jira events. It is only there to show an approximate equivalent to what the subscription is set up to handle. There is no guarantee that the JQL will be a valid query that you can copy and paste into the Jira UI.

> Will there be a support for the components field? This gives us much more functionality than labels?

The plugin currently has a lack of support for Components. It is something that we plan to include. Thank you for letting us know the value it has in your system @jprusch

**Comment by levb** [comment]
Resolving, will not fix. Support for Components is(?) tracked separately.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 12.12. bis 5.1. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
