### ISSUE TITLE
Add "Advanced" section to subscription that allows JQL

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-plugin-jira#415]
The subscription dialog is great, but advanced users should be able to enter a JQL statement to have more control over what is posted to a channel.

**Comment by mickmister** [comment]
Hi @icelander, I apologize for the delayed response. I've replied in the forum thread here https://forum.mattermost.org/t/filter-jira-subscriptions-using-jql/8636

**Comment by levb** [comment]
@icelander Basically it really is not a good fit with the current `/jira subscribe` architecture.

In the Microsoft Calendar plugin we are exploring subscribing to user-specific, expiring, limited "Subscriptions". I believe Jira has a similar API that we initially chose against. If the Microsoft implementation proves robust, we should explore adding it to Jira too, I believe that we would be able to specify JQL in such programmatically-created subscriptions.

Closing for now though as Will Not Fix.
