### ISSUE TITLE
[MM-18075] Reuse output of `/jira view` in the output of `/jira create` command

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#420]
#### Summary

Currently, the output of `/jira create` just shows a link to the ticket. We can instead provide more useful info by reusing the code that creates the output for the `/jira view` command.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18075

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by iamsayantan** [comment]
Would like to work on this.

**Comment by jfrerich** [comment]
Thanks again, @iamsayantan!  Marking this ticket as WIP and removing the `Up For Grabs` label!
