### ISSUE TITLE
[MM-20280] Display reporter name and avatar in `/jira view` output

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#421]
#### Summary

In the output of `/jira view` we can include the following additional info:
- Reporter's name
- Reporter's avatar

Info about the reporter can be found in the data we fetch from Jira in the field `jiraIssue.Fields.Reporter`, which includes `jiraIssue.Fields.Reporter.AvatarUrls` for using the avatars.

Info on including images in the post can be found here: https://docs.mattermost.com/developer/message-attachments.html

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20280

#### Screenshots

The current output of `/jira view`:
![image](https://user-images.githubusercontent.com/6913320/71023303-77000d80-20d0-11ea-9e86-ee9493f8de56.png)

---

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by AGMETEOR** [comment]
Will work on this

**Comment by jfrerich** [comment]
Thanks @AGMETEOR!
