### ISSUE TITLE
[MM-17816] Add the ability to transition an issue after running `/jira view`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#422]
#### Summary

Currently there are no available actions in the output of the `/jira view` command. Using a dropdown within the output, we can allow the user to transition the ticket into a different status.

Info on using dropdowns in the output can be found [here](https://docs.mattermost.com/developer/interactive-messages.html#message-menus).

The transitions can be fetched using the `GetTransitions` method [here](https://github.com/mattermost/mattermost-plugin-jira/blob/73624679260bc1e4803046802ea72bb867d75b04/server/client.go#L182).

There may be some required fields that are not yet filled out for the transition. If this is the case and the user tries to transition the ticket, Jira will return an error. A message should be displayed to the user saying that they need to fill out the fields in Jira. In the future, we will provide a way for the user to fill out those fields without having to leave the Mattermost application.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-17816

#### Screenshots

The current output of `/jira view`
![image](https://user-images.githubusercontent.com/6913320/71023303-77000d80-20d0-11ea-9e86-ee9493f8de56.png)

---

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by jasoncarreira** [comment]
I'm going to give this a shot... Is there a Jira server I can test against?

**Comment by mickmister** [comment]
@jwilander I see the Up For Grabs label was removed here. Has this task been assigned to someone?

**Comment by jwilander** [comment]
@jasoncarreira is going to be working on it

**Comment by jwilander** [comment]
@jasoncarreira was going to but not anymore, I'll open it back up

**Comment by AGMETEOR** [comment]
> I'm going to give this a shot... Is there a Jira server I can test against?

You can create an account on Jira and either use the cloud instance or download a server instance to use locally.

**Comment by AGMETEOR** [comment]
@mickmister I'll pick this up.
