### ISSUE TITLE
[MM-18737] Change wording of save subscription buttons

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#423]
#### Summary

Currently, the button to save a subscription is labeled `Set Subscription`, and the loading text is `Setting...`.

When creating a subscription, the label should read `Add Subscription`. While updating a subscription, the label should read `Save Subscription`. The loading text should read `Saving...` for both scenarios.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18737

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/71051073-0a5b3200-2115-11ea-9669-b22c662c5e46.png)

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by M-ZubairAhmed** [comment]
I would like to take this one please as its my first time collaborating to this repository

**Comment by mickmister** [comment]
@M-ZubairAhmed Fantastic! Thanks for contributing :+1:

**Comment by jfrerich** [comment]
Hi, @M-ZubairAhmed.  I hope this request is going well.  Do you need any assistance?

**Comment by M-ZubairAhmed** [comment]
sorry @jfrerich on this one now, i have posted request for help here https://community.mattermost.com/core/pl/qwry35zt1pn9fga9waopemcyjr
can you please help with that
