### ISSUE TITLE
[MM-20281] Show channel name at the top of subscription modal when editing a subscription

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#424]
#### Summary

Currently, when selecting a subscription in the modal, the channel name is at the top of the modal. But when you are in edit mode, it says `Add Jira Subscription`. The channel's display name should be at the top instead.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20281

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/71051222-90777880-2115-11ea-8be1-5f7ec7cda85f.png)

![image](https://user-images.githubusercontent.com/6913320/71051239-a127ee80-2115-11ea-924d-9ce34fbac900.png)

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by AGMETEOR** [comment]
Want to try this one out

**Comment by jfrerich** [comment]
@AGMETEOR! I'll remove the `Up For Grabs` label and this one is yours.  For any questions you may have, feel free to reach out in the [Contributors](https://community.mattermost.com/core/channels/tickets), [Developers](https://community.mattermost.com/core/channels/developers), or [Plugin: Jira](https://community.mattermost.com/core/channels/jira-plugin) channels, or in this issue.  

Thanks in advance for your help.
