### ISSUE TITLE
[MM-16948] `/jira install` should show a helpful error when the wrong server type is provided

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#425]
#### Summary

When running `/jira install server mmtest.atlassian.net`, the plugin shows the setup instructions for a Jira Server instance, instead of showing an error like `Please provide a URL to a Jira Server instance.`

If the user gives a Jira Cloud URL when running `/jira install server`, or gives a Jira Server URL when running `/jira install cloud`, we should show an error.

We can assume that Jira Cloud URLs have the domain `atlassian.net`, and Jira Server URLs do not. cc @levb

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-16948

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by popstr** [comment]
I would like to try this as my first ticket.

**Comment by jprusch** [comment]
This behavior will change soon.

Please check:
https://blog.developer.atlassian.com/ecosystem-support-for-custom-domains
and
https://jira.atlassian.com/browse/CLOUD-6999

A check for *.atlassian.net always defines a cloud instance. The test for server will be a little more complicated. But for the time being, this should work.

**Comment by mickmister** [comment]
@jprusch Thank you for providing these links. I agree, I was thinking any test for Jira server would be unreliable. I'm not sure we can support the Jira server use case at all. The improvement introduced in the PR may be the only available option.

**Comment by jprusch** [comment]
Sehr geehrte Damen und Herren,
ich bin vom 12.12. bis 5.1. nicht im Hause und habe daher leider keinen Zugriff auf meine E-Mails.
Ihre Mail wird NICHT weitergeleitet und nach meiner Rückkehr bearbeitet.
In dringende Fällen wenden Sie sich bitte an Hr. Tarrach (v.tarrach@schaeferbarthold.de)
Mit freundlichen Grüßen

i.V. Jan-Peter Rusch

TEL +49 (0)571-502-145 | FAX +49 (0)571-502-66-145
j.rusch@schaeferbarthold.de
______________________________________________________________________
Schäferbarthold GmbH
Erbeweg 2-12 | 32457 Porta Westfalica | Deutschland
www.schaeferbarthold.de
Schäferbarthold GmbH: Amtsgericht Bad Oeynhausen HRB 3748
Geschäftsführer: Dr. Volker Schäferbarthold, Dr. Christian Schäferbarthold, Wolfgang Schäferbarthold
