### ISSUE TITLE
[MM-20142] Handle `unhandledPromiseRejectWarning`s in test logs

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#427]
#### Summary

In some of the webapp tests for the plugin, there are log outputs showing `unhandledPromiseRejectWarning`. Any unhandled promises should be handled properly in the tests to avoid this warning.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20142

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by ramkumarvenkat** [comment]
Hi @mickmister , I am learning JS/React and go, so it will be a good first issue for me to look at. Will be sending a PR today
