### ISSUE TITLE
[MM-20139] Use typed mattermost-redux library to add typings to Jira plugin's redux store

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#428]
#### Summary

The redux store in the plugin is currently not typed with typescript. The task here is to use the types exposed from the `mattermost-redux` library to properly type the redux store in the plugin.

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-20139

#### Additional Info

mattermost-redux now exposes its store as a type. We can define the store slice for the plugin repo, and combine it with the one received from mattermost-redux, so the full store can be typed.

Here is a starter for typing the Jira plugin portion:

```typescript
export enum JiraInstanceType {SERVER = 'server',CLOUD = 'cloud',}

export type PluginState = {
	userConnected: boolean
	instanceInstalled: boolean;
	instanceType: JiraInstanceType;
	createModal: {
		postId?: string;
		description?: string;
		channelId?: string;
	};
	attachCommentToIssueModalVisible: boolean;
	attachCommentToIssueModalForPostId: string;
	jiraIssueMetadata: IssueMetadata;
	jiraProjectMetadata: ProjectMetadata;
	channelIdWithSettingsOpen: string;
	channelSubscriptions: {[subscriptionId: string]: ChannelSubscription};
}

type StoreFromMMRedux = {}

export type GlobalStore = StoreFromMMRedux & {[id: string]: PluginState;}
```
---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by AGMETEOR** [comment]
Hello @mickmister I am attempting this issue. I have done some work in the `actions/index` and opened a draft. Please, take a look and let me know of I am on the right track.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
