### ISSUE TITLE
Add Status to the available subscription field filters

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#440]
#### Summary

Currently, the field filters do not allow for a subscription such as "when a ticket's status is x".

#### Additional Info

The option needs to be added to the dropdown on the frontend for it to be supported. The change will likely need to go in `webapp/src/utils/jira_issue_metadata.tsx`

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/72076584-b8489f00-32c3-11ea-80bb-7709931b9d45.png)

**Comment by M-ZubairAhmed** [comment]
Can someone please help me understand or direct me to docs for " what does when tickets status is x "

**Comment by mickmister** [comment]
x is a placeholder for any valid status value. It's essentially asking to be able to filter on statuses in general.

**Comment by M-ZubairAhmed** [comment]
ok thank you @mickmister i will try to take this one

**Comment by mickmister** [comment]
Awesome thanks @M-ZubairAhmed! We really appreciate your efforts!

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
