### ISSUE TITLE
Refactor code to use KVListWithOptions to get keys

### ISSUE THREAD

**Issue by dlclark** [mattermost/mattermost-plugin-jira#441]
New helper functionality was added in https://github.com/mattermost/mattermost-server/issues/12936 to make writing plugin code that performs operations on a set of keys easier to write.  

At this time there are several places in the jira plugin where this happens:
* `CountUsers`
* `debugResetStats`
* `consolidatedStoredStats`

Update these areas to use the new `KVListWithOptions` helper function and remove the `listPerPage` var.

**Comment by AGMETEOR** [comment]
Hello @dlclark , looks like the [PR](https://github.com/mattermost/mattermost-server/pull/13576) to add the helper function `KVListWithOptions` has not yet been merged.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
