### ISSUE TITLE
Clean up mattermost-server references (v5), go mod tidy

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#452]
We should make all imports of mattermost server refer to /v5, and then create a clean go.mod.

_Originally posted by @levb in https://github.com/mattermost/mattermost-plugin-jira/pull/450_

**Comment by jfrerich** [comment]
@levb Looking at Jira, it seems all imports already point to `mattermost-server/v5` references.  Is this a ticket to apply and double-check other plugins?

**Comment by jfrerich** [comment]
linked comment -> https://github.com/mattermost/mattermost-plugin-jira/pull/450/files#r368590185

**Comment by jfrerich** [comment]
closing.  See merged ticket above.
