### ISSUE TITLE
Subscribe to multiple projects per channel (or multiple subscriptions per channel)

### ISSUE THREAD

**Issue by paladinlogic** [mattermost/mattermost-plugin-jira#463]
We use a single channel for multiple service desk projects. As the plugin is currently working, it seems you would need a channel per Jira project.

I can see this working one of two ways.

1. Use the current view and make the projects field also be multi-selection.
2. Allow for multiple subscriptions in a given room.

The major benefit of the latter case would allow different subscription schemes, if you will, for instance on one project only show notifications for comments, but for another one also show created or assignments.

**Comment by mickmister** [comment]
@paladinlogic May I ask which version of the plugin you are using? As of `v2.3.1`, you should be able to configure multiple subscriptions per channel.

**Comment by paladinlogic** [comment]
Apparently, 2.2.2. We're using MM 5.17.2 via GitLab Omnibus.
Is 2.3.1 compatible with MM 5.17?

**Comment by paladinlogic** [comment]
I answered my own question by looking at the Releases list. I'll try 2.3.2

**Comment by mickmister** [comment]
@paladinlogic Closing for now. Let us know if you have any questions, we're here to help :slightly_smiling_face:
