### ISSUE TITLE
Add slash command to add autolinks manually for jira server.

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#468]
#### Summary 
Something like `/jira autolinkadd MM PLT...` where `MM` and `PLT` are project keys. 

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-22077

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by promulo** [comment]
Hi, is there a Jira issue or something giving more details about this one? Thanks.

**Comment by hanzei** [comment]
@jfrerich Can you help with the above questions please?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
