### ISSUE TITLE
Use the Epic Link search box in the CreateIssue modal

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#471]
#### Summary

An autocomplete select box for Epics was introduced for the Subscriptions modal, but it is not currently used in the CreateIssue modal. The task here is to reuse the Epic Link select component in the CreateIssue modal.

**Comment by jfrerich** [comment]
PR merged closing.

**Comment by mickmister** [comment]
@jfrerich The PR is not merged, you can see the linked one above is "Closed" instead of "Merged". The new PR is here https://github.com/mattermost/mattermost-plugin-jira/pull/583 . I forgot to link the issue/PR together

**Comment by jfrerich** [comment]
Thanks, @mickmister.  This was unintentional and my mistake!  Thanks or catching an reopening.
