### ISSUE TITLE
Auto-detect new projects in Jira and update Auto-link registration

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jira#472]
Currently, you need to restart the Jira plugin to detect new projects on the Jira server and register them with Auto-link.  Ideally, this would be automated in some fashion, like via a webhook.  Alternatively polling on a time basis, and as a last resort running a manual "re-register" command.

See https://github.com/mattermost/mattermost-plugin-jira/pull/453

**Comment by AGMETEOR** [comment]
Looks like this was already worked on. Maybe this issue should be closed.

**Comment by hanzei** [comment]
Good catch @AGMETEOR. Closing as fixed with https://github.com/mattermost/mattermost-plugin-jira/pull/453
