### ISSUE TITLE
Include SiteURL in third-party cookie error message

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#476]
#### Summary

If authentication fails during the `/jira connect` process, we generate the following error to be shown to the user on Jira's page:

`Mattermost failed to recognize your user account. Please make sure third-party cookies are not disabled in your browser settings.`

The issue causing the error could also be that the user is not logged into their MM server in the same browser session. The error message should show an additional message such as the following.

`Make sure you are signed into Mattermost on (insert SiteURL)`.

On our community server, the user must be logged into `https://community.mattermost.com` specifically, in order for the OAuth process to work correctly. If the error message included the `SiteURL`, the process for debugging would be much smoother.

**Comment by MatthewDorner** [comment]
I would like to try this one.

**Comment by mickmister** [comment]
Awesome thanks @MatthewDorner!
