### ISSUE TITLE
Plugin config page has dead link to README.md

### ISSUE THREAD

**Issue by MatthewDorner** [mattermost/mattermost-plugin-jira#477]
The plugin configuration page contains this link to "configure the jira integration", which points to https://about.mattermost.com/default-jira-plugin, which redirects to https://github.com/mattermost/mattermost-plugin-jira/blob/master/README.md, which 404s. I'm guessing this is because the repo now uses GitBook.

![jira link](https://user-images.githubusercontent.com/36939751/74682370-7c8ada00-518b-11ea-8152-61e867ce7363.png)

**Comment by levb** [comment]
@aaronrothschild what's the correct link now?

**Comment by MatthewDorner** [comment]
Actually both the links (on lines 27 and 84 of https://github.com/mattermost/mattermost-plugin-jira/blob/4de6a5320e6921b48f87351acf84afcf2ef64fce/plugin.json) have this problem, though they're not the same link.

**Comment by AGMETEOR** [comment]
Will quickly fix this as soon  as we get the correct link from @aaronrothschild
