### ISSUE TITLE
Inform assigned User about issue changes via Bot 

### ISSUE THREAD

**Issue by Grienauer** [mattermost/mattermost-plugin-jira#479]
Currently the bot works great, but it does not inform Users via PM about Issue changes if they are assignee but not mentioned.

It would be great if the bot also inform users about issue comments/changes if they are not mentioned but the assignee. this would help a lot and the annoying jira mails will be gone ;)

maybe I also missed some setting to configure this?
thx!

**Comment by levb** [comment]
There should be a special stream of notifications for the assignee, maybe it stopped working? @jfrerich @DHaussermann?

**Comment by Grienauer** [comment]
We get still informations if we got mentioned… but not if a user is "just" an assignee for the issue.

**Comment by DHaussermann** [comment]
If you are the assignee, the bot will not DM you for all updates. However I believe that comments added to task your assigned to will send a DM (assuming they're being added by a different user)

I can double check this and let you know what I see. @Grienaue I'm curious what version of the plugin you're using as well as if you're using it with Jira Cloud or Jira server

**Comment by DHaussermann** [comment]
If you are the assignee, the bot will not DM you for all updates. However I believe that comments added to task your assigned to will send a DM (assuming they're being added by a different user)

I can double check this and let you know what I see. @Grienauer I'm curious what version of the plugin you're using as well as if you're using it with Jira Cloud or Jira server

**Comment by Grienauer** [comment]
plugin: jira - 2.2.2, pre-packaged
jira cloud

If I am the assignee and some other users writes a comment, no bot notification is currently sent.

a slash command `/jira version` would be nice btw ;P

**Comment by jfrerich** [comment]
@Grienauer, there is a `/jira info` slash command available, although I see it is not listed in the list of slash commands from `/jira help`.  Thanks for the feedback and I'll create a separate ticket to address it! :)

**Comment by jfrerich** [comment]
Ticket created https://github.com/mattermost/mattermost-plugin-jira/issues/485

**Comment by DHaussermann** [comment]
@Grienauer This looks like a bug to me. The functionality of notifying the assigned user when a comment is added is not working on Cloud. 

I'm not sure if this something that worked in earlier release or if there is another cause for the notification not being delivered.

The assignee should receive DM notifications when comments are added to their jira ticket.
I can see this functionality working on Jira Server with Jira v2.3.2.
