### ISSUE TITLE
Add number of projects to /jira stats or /jira info 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#483]
Add a new dynamically-pulled metric to report the number of projects on the installed Jira Instance.

---
(was)
There are some metrics we don't currently show that would be valuable to expose. 
- Number of issues created in past X
- \# of Projects on Jira server
- Number of Auth'd Jira users
- Number of Webhooks received in past 24 hours

These should be added to either the info or stats in a way that admins can view it from the UI.

**Comment by levb** [comment]
- The number of "connected" users should already be reported.
- The number of projects - I agree we should add, should be very much like the number of users, pull dynamically?
- Daily metrics can get expensive and difficult to implement; 1/5 I suggest we wait for better infrastructure in the framework.

**Comment by levb** [comment]
@DHaussermann @jfrerich unless you have objections, I'll change this ticket to reflect the only immediately actionable item, # of projects. LMK.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
