### ISSUE TITLE
JIRAv2 plugin should use gorilla/mux

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#484]
JIRAv2 plugin should use [`gorilla/mux`](https://github.com/gorilla/mux).

Most migrations has to take place in https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/http.go.

**Comment by levb** [comment]
We used to have this logged for a long time now, and then closed it. Now I see it back. What immediate benefits do we get from making this transition now? We are not planning on adding a significant number of new APIs, not changing the routing significantly in the near term, as far as I know.

Longer-term, I suggest that we adopt the new code structure from mscalendar, solar-lottery and such; it comes with `mux` already. Suggest closing.
