### ISSUE TITLE
Update `commonHelpText` and `sysAdminHelpText` to include all slash commands

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#485]
## Summary 
`jiraCommandHandler` contains the mappings of slash commands to their corresponding command handler functions.  The following slash commands are missing and should be added to the `HelpText` variables.
* webhook
* stats
* info
* help

The file containing the relevant code is https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go

**Comment by jfrerich** [comment]
@lev, do we want to include `debug/stats` and `debug/workflow` in the sysadmin help text?

**Comment by Francois-D** [comment]
I would like to work on this.  
Thanks

**Comment by Francois-D** [comment]
@jfrerich 
I've made the updates to the file and attempted to compile command.go.  However I am running into an undefined: plugin error.

./command.go:48:33: undefined: Plugin
./command.go:83:36: undefined: Plugin
./command.go:93:21: undefined: Plugin
./command.go:97:10: undefined: Plugin
./command.go:118:10: undefined: Plugin
./command.go:130:27: undefined: Plugin
./command.go:154:24: undefined: Plugin
./command.go:173:25: undefined: Plugin
./command.go:199:28: undefined: Plugin
./command.go:204:21: undefined: Plugin

Can you be of assistance?  Thank you.

**Comment by jfrerich** [comment]
Hi @Francois-D!  Thanks for taking on this ticket!  Let me see if I can help.  I am assuming you are working in a cloned repo.  What branch?  I'll clone from there to see what's happening :)

**Comment by Francois-D** [comment]
Thanks so much @jfrerich I actually forked the repo to my account.
I simply added the missing strings then tried to build/compile the command.go file.
I presume I am doing something wrong as it is complaining about line 43 and and undefined plugin.

**Comment by jfrerich** [comment]
Can you try running `make` from the root `mattermost-plugin-jira` directory?

**Comment by Francois-D** [comment]
One moment thanks

**Comment by Francois-D** [comment]
Looking good now thanks for the assistance. 
@jfrerich

**Comment by jfrerich** [comment]
No problem.  We utilize a lot of make targets for building, linting, .etc
