### ISSUE TITLE
Validate and document that cloud requires and https endpoint

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#487]
#### Summary

When configuring webhooks, in Jira, the SITEURL must use `https://` if connecting to a cloud instance.  This ticket has two requests.

1. Document in the README that cloud instances will require an `https` endpoint.
2. Add validation that will reject non-https URLS for jira cloud instances.  This will be handled in the code that is executed with `/jira install cloud <URL>`

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-22593

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by Francois-D** [comment]
I would like to be assigned this issue.

Thanks.

**Comment by jfrerich** [comment]
@Francois-D, you are more than welcome to take this ticket.  Please let me know if you have any questions!
