### ISSUE TITLE
Refactor UploadAttachment to stream

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#488]
#### Summary
Came out of investigating https://mattermost.atlassian.net/browse/MM-16925

Currently, the jira client buffers entire PostAttachments files in memory, see https://github.com/andygrunwald/go-jira/blob/216e0056d6385eba9d31cb37e6ff64314860d2cc/issue.go#L618.

This should be refactored to stream directly to Jira, no reason to buffer. We can do a custom implementation, or contribute to the client.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-17132

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
