### ISSUE TITLE
Add support for storybook

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#493]
#### Summary

Storybook support has been added to the webapp repo and plugin repos would also benefit from using storybook.  https://storybook.js.org helps build, test, and view components in isolation!

**Relevant and informative links**
* [webapp storybook PR](https://github.com/mattermost/mattermost-webapp/pull/3570) The PR for adding storybook to the webapp repo
* [webapp .storybook directory](https://github.com/mattermost/mattermost-webapp/tree/master/.storybook)
* https://storybook.js.org
* [introductory video]9https://www.youtube.com/watch?v=p-LFh5Y89eM&feature=youtu.be)

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-18622

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
