### ISSUE TITLE
Use json web token (JWT) instead or custom mm-token

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#494]
#### Summary

Currently, the plugin uses a custom mattermost auth token. This ticket is a request to convert to using a standard JWT token.

The relevant code containing the mmtoken is [here](https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/user_cloud.go)

The custom mattermost auth token code, which will be replaced is [this file](https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/auth_token.go)

#### Ticket Link

https://mattermost.atlassian.net/browse/MM-15248

---

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
