### ISSUE TITLE
Properly support OAuth2 (beta) in Jira Cloud

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#499]
Jira cloud appears to have added "normal" OAuth2 support, we should probably support it when it's out of beta, as an alternative to Atlassian-Connect deployments.

See https://mmtest.atlassian.net/secure/admin/oauth-credentials.

What makes this ticket hard is that it needs to be implemented in ways that are backwards-compatible with the existing AC-based flows.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
