### ISSUE TITLE
release notification support

### ISSUE THREAD

**Issue by Grummfy** [mattermost/mattermost-plugin-jira#5]
Hello,
If it's possible, can you add a release notification support

thanks

**Comment by Hanzei** [comment]
@Grummfy what exactly are you requesting?

**Comment by levb** [comment]
@Grummfy were you requesting `jira:version_released` event (see https://developer.atlassian.com/server/jira/platform/webhooks/)

**Comment by jasonblais** [comment]
We haven't received an update so we'll close the issue for now.

If you're still interested to see support for the feature, please help add relevant information. A good option may be to share a screenshot of the items in Jira you'd like to receive notifications for.
