### ISSUE TITLE
Add per-subscription "Hide issue descriptions and comments" setting

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#504]
https://github.com/mattermost/mattermost-plugin-jira/pull/503 added the setting as a plugin-wide config option.

We should add a per-subscription setting as well.

@asaadmahmood will provide the UX, and the priority order (i.e. should the plugin config override, or be overridden by subscription-specific settings)

**Comment by asaadmahmood** [comment]
@levb We can place the checkbox here, and this should override the system console setting, as there may be cases where we want to do something different than the global setting, and that's how various other settings work in the system.
We have a global default, and then we have the ability to override that on a per channel basis (mentions as an example).

![ci-extensions azure k8s mattermost com_dkh-team_channels_town-square](https://user-images.githubusercontent.com/11034289/80467446-3ace9a80-8957-11ea-8143-92282e75a256.png)

**Comment by jfrerich** [comment]
Thanks for the UX description, @asaadmahmood!  I am removing updating the issue as an `Up For Grabs` ticket after getting your spec.

**Comment by sanjaydemansol** [comment]
Hi, #783 needs to be merged first.

**Comment by mickmister** [comment]
@sanjaydemansol The two features both use the subscriptions feature, but I don't think adding a new setting to the subscription needs to wait for the subscription template feature to be complete. No interfering data model changes are part of the template feature's PR.

I think this issue can be worked on in parallel with the linked PR https://github.com/mattermost/mattermost-plugin-jira/pull/783. @sanjaydemansol @jfrerich What do you think?

**Comment by jfrerich** [comment]
I agree this feature can be worked on in parallel

**Comment by sanjaydemansol** [comment]
@mickmister I suggested because if we work on this issue in parallel, this feature won't be a part of subscription templates.

**Comment by mickmister** [comment]
@sanjaydemansol I still think it can be worked on in parallel. Whichever PR gets merged first will have to incorporate the other PR's changes. I don't think it will be difficult to handle that situation

**Comment by hanzei** [comment]
This is not a priory. Unassigning @jupriano for now.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
