### ISSUE TITLE
Add support for logging work using /jira work

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-jira#505]
I suggest the following enhancement:

A new slash command:

**/jira work ISSUE-KEY(mandatory) Time(optional) "Worklog desc (optional)"**

should log work of TIME to the given issue with an optional worklog description.

Time would be anything like 1h, 60m. If no unit is given minutes should be assumed. If no time is given, a default time value eg. 15 minutes is used.

This would really push the usage of the Jira plugin in our company. Right now, each user always has to switch to Jira to log his time.

**Comment by aaronrothschild** [comment]
Thanks for the suggestion @jprusch - I'm going to ask some users about their use of the "work logging".

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
