### ISSUE TITLE
When mentioning recently added attachments through the attachments button, the comment is automatically added as thumbnail

### ISSUE THREAD

**Issue by gastaldelloa** [mattermost/mattermost-plugin-jira#506]
**Expected Results:**
The attachment would be mentioned in the following format since it's an image:

`[^attachment_name.txt]`

**Actual Results:**

`!attachment_name.txt!`

The file is automatically mentioned as thumbnail which results in an error when adding the comment as thumbnail since the file isn't an image

`Unable to embed resource: attachment_name.txt of type text/plain`

Please review the issue.go at the following function:

```
	go func() {
		conf := ji.GetPlugin().getConfig()
		extraText := ""
		for _, fileId := range post.FileIds {
			mattermostName, jiraName, e := client.AddAttachment(api, attach.IssueKey, fileId, conf.maxAttachmentSize)
			if e != nil {
				notifyOnFailedAttachment(ji, mattermostUserId, attach.IssueKey, e, "file: %s", mattermostName)
			}

			extraText += "\n\nAttachment: !" + jiraName + "!"
		}
		if extraText == "" {
			return
		}

		jiraComment.ID = commentAdded.ID
		jiraComment.Body += extraText
		_, err = client.UpdateComment(attach.IssueKey, &jiraComment)
		if err != nil {
			notifyOnFailedAttachment(ji, mattermostUserId, attach.IssueKey, err, "failed to completely update comment with attachments")
		}
	}()
```

**Comment by aaronrothschild** [comment]
@gastaldelloa Could you send a screenshot of where this is occurring?

**Comment by gastaldelloa** [comment]
> @gastaldelloa Could you send a screenshot of where this is occurring?

[images.zip](https://github.com/mattermost/mattermost-plugin-jira/files/4415075/images.zip)

Aaron, here enclosed you can find the step by step images to reproduce the issue. Basically I created a new comment with a simple attachment text file, then I attach the comment to an existing JIRA issue and the result in the JIRA issue is the available attachment but the link in the comment has the "Unable to embed resource" error. This is due to the wrong way to include a not image attachment as described.
Hope this help you. I'm available for any further information about.
