### ISSUE TITLE
Jira Connect "App is not responding."

### ISSUE THREAD

**Issue by Askotion** [mattermost/mattermost-plugin-jira#509]
Hello,

so i have tried setting up the jira plugin. I followed the whole tutorial but when it comes to the part where users connect their account using /jira connect, they all get this error: "App is not responding. Wait or cancel?" 

I have set the webhook acording to the documenation. Anyone expirenced this before?
For the beginning i just want to receive jira notifiactions in a separate channel. 
We are running mattermost behind a nginx proxy using docker. Is this maybe the problem?

What logs can i provide to you that might help?

Thanks in advance.

**Comment by svelle** [comment]
Hi @Askotion,
I take it this is happening in the desktop app. Could you please provide the version they're using?

**Comment by Askotion** [comment]
Hi @svelle,
thanks for your quick answer! Yes its happening in the desktop app but it doesnt matter if its the app for mac or linux. Both should be the latest version. Mattermost version is: 5.15.0

I just tried the connection using my browser and there i get an error within the iframe. 

![Screenshot 2020-03-30 at 12 36 57](https://user-images.githubusercontent.com/4161328/77903624-722c2780-7283-11ea-843e-55aca50e82b5.png)

Chrome gives this error:
Refused to display '**URL**' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

So i guess its a problem with the proxy settings? Im using this docker image for my proxy: 
https://hub.docker.com/r/jwilder/nginx-proxy/

**Comment by levb** [comment]
@Askotion sorry for the delay getting back to this. Is your Mattermost site URL set to an externally accessible URL? (I personally use ngrok). If not, please make sure it's set as such.

**Comment by levb** [comment]
Closing, not reproduced.
