### ISSUE TITLE
Hide previous notifications or update their content when updated?

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jira#511]
After an issue is created and shown in the channel -  Ideally we would either keep the same "view" of the post once the status is modified OR remove the visual elements from the previous post once a new post with a more current view of the ticket is made.

One drawback with the current design (MM-17816) is that previous instances of the "view" in the ephemeral post stay visible and you can manipulate the drop-down. This seems like a broader issue with how plugins make ephemeral posts. 

_Originally posted by @DHaussermann in https://github.com/mattermost/mattermost-plugin-jira/pull/454#issuecomment-603855704_

**Comment by levb** [comment]
We could (should?) remove the post-action from the ephemeral message upon performing a selection.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
