### ISSUE TITLE
Can't choose sub task issue types in subscription filters

### ISSUE THREAD

**Issue by ousnius** [mattermost/mattermost-plugin-jira#519]
When adding or editing a channel subscription in the UI, it's not possible to select issue types for sub tasks in the filter. As such, no messages from sub task webhooks will appear.

**Comment by ousnius** [comment]
The behavior of skipping sub tasks when getting the metadata to fill the react boxes was introduced with #208.

I know nothing about the code base, but I assume this was introduced since creating sub tasks isn't supported right now, but the filter also affects the channel subscription dropdown choices.

**Comment by Kshitij-Katiyar** [comment]
@ousnius The above functionality was added in https://github.com/mattermost/mattermost-plugin-jira/pull/1095.
