### ISSUE TITLE
Allow for addition of labels in creation modal

### ISSUE THREAD

**Issue by clham** [mattermost/mattermost-plugin-jira#520]
My Jira setup requires I attach a label to each ticket so it shows up on my teams board. Currently I have to create a ticket, then go manually add the label. I would like  to be able to add labels in the create modal

**Comment by mickmister** [comment]
Hi @clham, thanks for voicing your need for this. Supporting labels in the create issue modal is currently in our pipeline. We have functionality in the works for supporting labels in the subscribe modal. After this is merged, we will port over the select boxes from the subscribe modal to the create issue modal.

Here are the tickets so you may track the progress:
https://github.com/mattermost/mattermost-plugin-jira/issues/394
https://github.com/mattermost/mattermost-plugin-jira/issues/502
