### ISSUE TITLE
New User Connect: Prompt if they want to be notified of mentions

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jira#522]
Currently, the default setting for notifying users if they are mentioned in Jira is set to "off" (I think!).  

When the user first connects, we should then prompt them with a question like "Would like me to notify you with a Direct Message whenever someone mentions your name on a Jira issue?"  Then show a Yes/No button.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
