### ISSUE TITLE
Why the required fields are not filled but the status can still be changed?

### ISSUE THREAD

**Issue by shi-link** [mattermost/mattermost-plugin-jira#524]
![未命名](https://user-images.githubusercontent.com/63843614/79547967-4dc7ac00-80c7-11ea-8962-1d7129bc9cf0.png)

**Comment by jprusch** [comment]
I just wonder if this question is related to Jira only or in combination with the Mattermost Jira plugin.
What action are you trying to do from your Mattermost client? /jira transition?

**Comment by shi-link** [comment]
When I transitioned to the completion status at Mattermost (/ jira transition DEMO-19 done), I need to fill in the  Resolve Issue screen, but I did not jump out of the  Resolve Issue screen

**Comment by levb** [comment]
@shi-link Apologies for the slow response. I checked the implementation at https://github.com/mattermost/mattermost-plugin-jira/blob/d776dd30b9ad8beae03d9f74535c5d989c9e710b/server/issue.go#L970-L1007.

The logic is - we get the list of known transitions for the issue (defined in Jira), then we try to find an unambiguous match to the desired state; if found - use it. I can see a potential bug there if multiple transitions can lead to the same state - we choose the last matching transition, but this appears an esoteric case.

If there is a matching transition, and we execute it without providing the required fields set, I'd expect the command to fail.

Do you mind posting (or DM-ing me on community.mattermost.com) more details about the transitions and fields as they are defined in Jira for your project?

**Comment by levb** [comment]
Closing, no response.
