### ISSUE TITLE
Cannot link with jira 8.8

### ISSUE THREAD

**Issue by kasak87** [mattermost/mattermost-plugin-jira#526]
Mattermost 5.22.0, jira plugin 2.3.2, jira 8.8.0.
When i post /jira install server myurl
bot answer me how to add application link in jira. 
but bot don't mention anything about "request token url" "access token url" and "authorize url" 
without this fields i cannot finish creating link. 
![Снимок экрана от 2020-04-20 16-51-31](https://user-images.githubusercontent.com/64020259/79759342-3be44400-8327-11ea-8c27-351430dcc5f0.png)

**Comment by kasak87** [comment]
There is no info about this fields here. 
![Снимок экрана от 2020-04-20 16-53-52](https://user-images.githubusercontent.com/64020259/79759608-8d8cce80-8327-11ea-93c2-190d6ab7c73b.png)

**Comment by DHaussermann** [comment]
@levb For what it's worth, I spun up a docker container of Jira server 8.8 and these fields are not mandatory for me when creating the connection link and I can connect normally. 

I'm not sure what may be making these fields mandatory but it may not be something new to Jira 8.8.

**Comment by kasak87** [comment]
> @levb For what it's worth, I spun up a docker container of Jira server 8.8 and these fields are not mandatory for me when creating the connection link and I can connect normally.
> 
> I'm not sure what may be making these fields mandatory but it may not be something new to Jira 8.8.

I have tested this on two jira installations, both of them is 8.8, one of them is fresh installed, and they both require this fields

**Comment by aaronrothschild** [comment]
@DHaussermann Spoke to customer - this was on an upgraded Jira server box FYI.

**Comment by ahmaddanialmohd** [comment]
Hello, team. I am bumping this on behalf of another customer. May I know if we have any updates on when this issue will be ironed out? Thanks.

**Comment by hanzei** [comment]
@kasak87 Can you connect successfully, if you fill out the field with junk?

**Comment by kasak87** [comment]
> @kasak87 Can you connect successfully, if you fill out the field with junk?

I was able to connect by not filling anything, but link name. 
After that, i edited link, and added required fields. Seems like workaround.

**Comment by jfrerich** [comment]
@kasak87, @ahmaddanialmohd, @DHaussermann  I'm sorry this issue has taken so long to resolve, but it's a very simple solution, that took many hours to debug before realizing the error.  

The instructions received after installing a server instance could be clearer and I will address in a separate ticket. However, here is the solution.

When installing an application link on a Jira Server, there are two forms to fill out.  Unfortunately, they are both named `Link applications`.  

### Form 1
In the first modal, the only fields that should be filled in are the following:
* `Application Name` 
* `Application Type`
* `Create incoming link`

![image](https://user-images.githubusercontent.com/7575921/94175340-29cd7b00-fe5c-11ea-865e-846529071480.png)

Form 2
In the second modal, this is where you will need to fill in the following:
* Consumer Key
* Consumer Name
* Public Key

![image](https://user-images.githubusercontent.com/7575921/94175318-22a66d00-fe5c-11ea-815e-6fe567767736.png)

**Comment by jfrerich** [comment]
PR created with new help text! Please see linked PR

**Comment by vikulin** [comment]
Thanks. It works!
