### ISSUE TITLE
Jira will post "Attachment: !!" in a comment when attachment fails

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#529]
When attachments from the mattermost post fail to upload due to permission or size restrictions, the plugin will include  the text `Attachment: !!` in your comment.

This is not helpful and does not indicate an attachment was not included in the comment. We should include a message such as `Attachment from the Mattermost post was not included` or add nothing at all.

**Comment by hectorgabucio** [comment]
I'll do it!

**Comment by levb** [comment]
@hectorgabucio just checking in to see if you are still interested in this issue?
