### ISSUE TITLE
Add info about `/jira webhook` to admin jira config for contextual help 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#531]
The admin Jira config UI has a section providing an example of a jra webhook. 
<img width="1201" alt="JiraConfigPage" src="https://user-images.githubusercontent.com/35588783/80527455-5ee3a900-8962-11ea-947f-a09c238a95df.png">

It would be helpful to inform the user that they can use `/jira webhook` to see the current hook.
This info may also be valuable to add in the instructions ephemeral post when `/jira install` has been used.

**Comment by levb** [comment]
3 parts to this request:
1) change the text in https://github.com/mattermost/mattermost-plugin-jira/blob/d776dd30b9ad8beae03d9f74535c5d989c9e710b/plugin.json#L91 to recommend the use of `/jira webhook` to see the fully expanded URL;
2) change the output of `/jira install` to include the webhook URL
3) (bonus) change the output of `jira uninstall` to include the reminder to remove the Jira-side webhook, and a link to do so.
