### ISSUE TITLE
Unable to install Jira cloud with 2.4 atlassian-connect.json returns a 404

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#532]
When trying to install a Cloud instance with Jira 2.4 the atlassian-connect.json is unavailable and the Jira side install fails. 
Tested on server versions master and 5.23-release for good measure. Same behavior.  

Steps:
- Unintall existing instance from Mattermost server and from jira apps
- From Mattermost type `/jira install cloud https://mmtest.atlassian.net`
- Go to apps management in JIra and upload the app from the provided URL ` https://dkh-local.ngrok.io/plugins/jira/ac/atlassian-connect.json` 
**Expected**: App installs
**Observed**: App is not available 
- Manually navigate to provided URL
**Expected**: json file is visible in the browser
**Observed**: Server returns a 404

**Comment by levb** [comment]
Works for me, @DHaussermann did you have the plugin built off of `master`?

**Comment by DHaussermann** [comment]
It seems @mickmister came across a fix for this issue while debugging a different issue with me. Hw should have a PR that resolves it.
