### ISSUE TITLE
Implement a `/jira comment issue-id "text"` command

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#533]
No web UI, just add the comment, and post the link back to the channel

**Comment by levb** [comment]
*@lev.brouk attached a* [message](https://community.mattermost.com/core/pl/1ou6tjiti3r9dq6i8w5sq5mthr) *from @wwollesen*
so something like, you know, `/jira comment <issue-ID> "some udpate text"`

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
