### ISSUE TITLE
Incorrect error message when user has no create permissions on any projects

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#539]
There is an edge case where a user has no create permission on any project and then tries to create an issue they will see a message about an unexpected value in json rather than a user friendly message.
![NoPermision](https://user-images.githubusercontent.com/35588783/81580044-ea096980-937a-11ea-80b1-edfcdad8dffa.PNG)
This occurred on Jira server 8.8.1
Steps:
- Connect test user in Mattermost
- In Jira note test users role and remove create permissions for all projects
- In matter most attempt to create an issue from a post

**Expected**: Some message about no projects available comparable to subscribe modal in similar case
**Observed**: Error about invalid json

**Comment by raghavaggarwal2308** [comment]
Closing as completed for now. Can reopen if someone faces this issue again
