### ISSUE TITLE
jira webhook command returns the URL for Legacy webhook instead of newer subscription webhook 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#540]
We are now exposing a command to admins where `/jira webhook` will show the webhook URL including the secret. 
However, we are displaying the URL that is used for legacy hooks that is specific to a team and channel. 
Granted with new webhooks there is less need for this command but it still seems like we should be showing the webhook URL needed for subscriptions here.

**Comment by DHaussermann** [comment]
@aaronrothschild just want to confirm with you on this behavior change ☝️

**Comment by aaronrothschild** [comment]
@DHaussermann sounds good totally agree.

**Comment by jfrerich** [comment]
This is done.
