### ISSUE TITLE
Attachment get's dropped when user has to finish save on Jira side

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#541]
In cases where a user is trying to create an issue from a post with files attached and the issue must be completed and saved from the Jira side due to unsupported fields, the attachment does not get included 

In this case the user is directed to Jira via a link as expected and all data they have entered is pre-populated but the attachment does not come over. 

steps:
- Configure Jira such that an unsupported filed (radio for example) is required for your target project
- As a user in Mattermost, make a post with a file attachment
- Create an issue from the post
- Enter data in the modal and save
- Click the link to finish completing your issue

**Observed**: When navigating to jira to finish the creation, the file attachment has not been uploaded

**Comment by DHaussermann** [comment]
0/5 on if this should be changed to an enhancement instead of a bug.

**Comment by levb** [comment]
I am not sure it's possible to include the attachment like that. We may be able to provide a link to the file in mattermost, but it'd potentially require user (re-)authentication if a different browser is popped for the link. 1/5 resolve as will not do.

**Comment by hanzei** [comment]
Discussed at the integrations meeting: Given that it is quite hard to fix and an edge case, it will be closed as won't fix.
