### ISSUE TITLE
Improve view UI to include icon based on Jira issue type

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#542]
We should be including the corresponding icon next to the text showing what issue type is.

![IssueType](https://user-images.githubusercontent.com/35588783/81583254-1aeb9d80-937f-11ea-85fb-e0895d9ea26d.PNG)

This would go well with the other visual enhancements we've made here and give the integration a more polished feel.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
