### ISSUE TITLE
Plugin not posting comments

### ISSUE THREAD

**Issue by s1lviu** [mattermost/mattermost-plugin-jira#543]
I've integrated it, shows activities regarding sprints, tasks.. but nothing about comments. 

Mattermost version:  5.16.0
Plugin version: 2.2.2

**Comment by PhilipsIII** [comment]
Adding `&updated_comments=1` to the webhook worked for me.
https://github.com/mattermost/mattermost-plugin-jira#how-do-i-manually-configure-webhooks-notifications-to-be-sent-to-a-mattermost-channel

**Comment by s1lviu** [comment]
> Adding `&updated_comments=1` to the webhook worked for me.
> https://github.com/mattermost/mattermost-plugin-jira#how-do-i-manually-configure-webhooks-notifications-to-be-sent-to-a-mattermost-channel

Does the trick work for subtasks too? Because I've updated it, but cannot subscribe to subtasks

**Comment by levb** [comment]
@s1lviu `&updated_all=1` would expose all events that the plugin currently supports, but I don't believe subtask updates currently are. Do you mind filing a separate issue for that?

FWIW, we encourage users to use `/jira subscribe` rather than the individual "legacy" webhooks.

**Comment by mickmister** [comment]
I do not believe subtasks are supported in the current or legacy webhook systems. I've created a ticket to add support https://github.com/mattermost/mattermost-plugin-jira/issues/555

@s1lviu Are you only experiencing the comments issue with subtasks? I second the notion of using `/jira subscribe` over the alternative that is linked in the docs above.

**Comment by s1lviu** [comment]
Yep, only with subtasks. 

Thank you for creating the support ticket.
