### ISSUE TITLE
Remove `by mattermost-jira-plugin` link/text

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jira#551]
![image](https://user-images.githubusercontent.com/915956/82476274-a30a2b00-9a82-11ea-8459-d9dc773fa14b.png)

Users are confused by the message appended to "Attached to Jira issue" that shows that the Jira plugin did the update (`by mattermost-jira-plugin`).  the intention of showing the Jira plugin text is to encourage other users to discover the Jira/Mattermost integration and use it themselves. 

1) I think we should consider making the link go to a Webpage served by the plugin which explains to a user WHAT the plugin does and how they can get started.  Maybe they click a button like "Connect Jira to my Mattermost Account" on that page which then starts the "Connect" process for them.  This is basically an internal "Marketing/Adoption" landing page. 
2) In the meantime the text could probably be updated to be in Parantheses to indicate it's a meta-message.  Like `Message contents were attached to XYZ-123 (by the Mattermost Jira Plugin)`

**Comment by aaronrothschild** [comment]
One other consideration: Add the user who made the "attachment" to the message too.

`Message contents were attached to XYZ-123 by Bob Username (using the [Mattermost Jira Plugin]() )`

This may be redundant since we post using the user's account.  

@asaadmahmood thoughts?

**Comment by asaadmahmood** [comment]
Sounds good to me @aaronrothschild

**Comment by jprusch** [comment]
Please make the link feature, the link text and the URL configurable. Non-English speaking users are disturbed being send to a page they don't understand. I tend to write/translate most of every plugin descriptions and manuals to use our language and internal wording.

**Comment by levb** [comment]
0/5 we should remove the link - it's click bait. A plain text reference "using the Mattermost Jira plugin" may be reasonable compromise?

I feel that making this text configurable is just too much complexity; if it really is controversial, maybe we should remove it altogether.

**Comment by hanzei** [comment]
Discussed offline: "using the Mattermost Jira plugin" should be dropped

**Comment by aaronrothschild** [comment]
Agreed - we should be making Welcomebot better or something to that effect to increase the awareness of the Jira plugin.
