### ISSUE TITLE
Support filtering on subtasks for subscriptions

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#555]
Creating subscriptions with `/jira subscribe` for subtask issue type is currently not supported. The subscription setup code will need to be updated to support subtasks.

**Comment by dzinkevich-renins** [comment]
Do you working on it?

**Comment by mickmister** [comment]
@dzinkevich-renins This is not being worked on at the moment. Why do you ask?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
