### ISSUE TITLE
Add LinkTooltip to ticket links, similar to that of the GitHub plugin

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#556]
#### Summary

The GitHub plugin now supports a LinkTooltip that shows details on a linked issue or PR when the user hovers over the link in Mattermost. The task here is to apply this functionality in this plugin when hovering over Jira issues.

#### Screenshots

![image](https://user-images.githubusercontent.com/4473536/82212169-7cb08800-98e8-11ea-8876-c654f9cf2ad7.png)

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
