### ISSUE TITLE
`/jira assign` should accept `@username`

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#558]
Currently, the first parameter is interpreted solely as a search string for a Jira user search. We should support accepting an `@username`. If the user is connected to the instance, we can use the AccountID; if not - can perform a Jira search on the Mattermost display name.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-jira/pull/863 can be used as a starting point

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.

**Comment by wiersgallak** [comment]
I see activity on a recent PR. Reopening.
