### ISSUE TITLE
DM Notifications not working

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-jira#559]
![image](https://user-images.githubusercontent.com/1187448/83439042-37677c80-a3f7-11ea-9d27-1155a8bef509.png)

With @ali-farooq0 on community-daily, Jira v2.4

cc @jfrerich @mickmister @DHaussermann

**Comment by levb** [comment]
*@lev.brouk attached a* [message](https://community.mattermost.com/core/pl/wibk3yytu7gy9ersiag5cw5eiw) *from @ali.farooq*
@lev.brouk just tried `/jira disconnect` `/jira connect` . No dice, still no notification.

**Comment by levb** [comment]
@ali-farooq0 We currently are not sending comments in the Jira subscription on the community servers, for data security reasons, so you are not being mentioned.

**Comment by mickmister** [comment]
@ali-farooq0 @levb You should still be getting DM notifications for comments though. The only thing that is disabled is the comment bodies of posts in channels. Help wanted on supporting comment visibility filters on subscription posts: https://github.com/mattermost/mattermost-plugin-jira/issues/626

**Comment by mickmister** [comment]
Note that at the time of creating this `DM Notifications not working` ticket, we had all comment events turned off on the Jira webhook side. But DM notifications should be working now.
