### ISSUE TITLE
`/jira` slash command posting as system and jira bot

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#560]
### Summary

`/jira connect` and `/jira disconnect` show ephemeral messages using two different icons.  This ticket is a request to use the Jira bot for all ephemeral messages.

![image](https://user-images.githubusercontent.com/7575921/83462188-2be47780-a430-11ea-9c77-cdd34aff267f.png)

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by mickmister** [comment]
The ones that are posted as `System` are ephemeral messages generated in the webapp side of the plugin. This would require changes in the core product to support posting as the bot from the webapp. I agree that the UX is not very good at the moment, but I'm not sure if it is worth supporting the use case.

@hanzei What are your thoughts?

**Comment by mickmister** [comment]
That being said, it may actually be possible to do this from the webapp. We would just need to have the bot user ID if that would work.

**Comment by mickmister** [comment]
With some quick testing, the messages show as system, even if the user id is set to the bot. What's weird is that if the plugin reloads at runtime, those system messages turn into Jira plugin ephemeral messages. Interesting ticket to debug for HW.

**Comment by Francois-D** [comment]
@jfrerich 
Would like some assistance on how to connect the MM server with the Jira server.  I ran the /jira connect command and followed the instructions after the /jira install server command <jira url> 
Ran into error that said user is not authorized.

Opened up https://mattermost.gitbook.io/plugin-jira/setup/installation#step-2-install-app-on-jira-server.   Was unable to change the setting to developer mode as this option was not available to me.    I'm not sure if it's the Mattermost server or a special app?.  Thanks.
Jira server (evaluation) and Mattermost server are both local to my machine.

Screenshot 2,3 are the same, I did notice that if I click back and select the allow again, i got a more user friendlier message.
<img width="614" alt="Screen Shot 2020-06-06 at 2 07 51 PM" src="https://user-images.githubusercontent.com/46973576/83954891-177ef100-a81b-11ea-996e-9dd9ec010b4b.png">

Attached screenshots of for reference.
<img width="1049" alt="Screen Shot 2020-06-06 at 2 08 31 PM" src="https://user-images.githubusercontent.com/46973576/83954838-ac351f00-a81a-11ea-9cf6-e62c10218942.png">
<img width="872" alt="Screen Shot 2020-06-06 at 1 58 26 PM" src="https://user-images.githubusercontent.com/46973576/83954845-ba833b00-a81a-11ea-8823-554f8c1dafcb.png">
<img width="701" alt="Screen Shot 2020-06-06 at 2 00 22 PM" src="https://user-images.githubusercontent.com/46973576/83954855-cd960b00-a81a-11ea-8400-fc29c7e8a80c.png">

Thanks for your time. :)

**Comment by mickmister** [comment]
@Francois-D The steps in the docs you linked (where step 3 is referring to Upload App) are specific to Jira Cloud. It is a bit confusing. For Jira Server, all the instructions should be in the slash command response of the `install` command. I'll have the docs updated accordingly.

If you are having problems installing with Jira Server feel free to DM me at https://community.mattermost.com at `michael.kochell`.

Thanks @Francois-D!

**Comment by wiersgallak** [comment]
Look like this may have been completed. Closing issue.
