### ISSUE TITLE
Concurrency issues when saving subscriptions

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#562]
### Summary
There has been an incident where saving an existing subscription is showing an error that is implying that the subscription's id does not exist in the kv store. This can occur when the subscription has been deleted elsewhere before saving. No message was posted saying that the subscription was deleted, so we believe this was not the cause.

There could be an issue with multiple users editing subscriptions simultaneously, causing a conflict in the data stored in the kv store.

**Original Message:**
Team, came across some potential bugs (I think) which I am not sure if they have been reported yet or not. 

* Cannot re-set the subscription in the channel. Clicking *Save subscription* does not save it
* Deleting the subscription afterwards gave me a error related to `bad subscription id`
* Running `jira /subscribe` again gives me a new error `modification error: Existing subscription does not exist`

Please see the [Mattermost Conversation](https://community-release.mattermost.com/core/pl/wu6axnostigmmdkuy6diq7qfyw) for additional context and discussion.

More info can be found in follow up messages in the MM thread

### ScreenShots
Screen Shot 1
![image](https://user-images.githubusercontent.com/7575921/83464071-64d31b00-a435-11ea-98ea-19f5f75488db.png)

Screen Shot 2
![image](https://user-images.githubusercontent.com/7575921/83464077-6997cf00-a435-11ea-8a24-a3d77ce16a54.png)

Screen Shot 3
![image](https://user-images.githubusercontent.com/7575921/83464081-6c92bf80-a435-11ea-8689-e59966a17d64.png)

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by jfrerich** [comment]
@mickmister this doesn't seme a trivial issue. Could you provide some additional context or proposal?  What else should be done besides informing the user that a subscription no longer exists?  This is already done  with the error messages shown in the screenshots.

**Comment by mickmister** [comment]
I agree that the error message is sufficient here. I think this was resolved but I had not marked the ticket as such. 1/5 this ticket can be closed on this premise.

We have not seen this issue happen other than that one time, and I believe Ahmad was the only user on that server at the time, so I don't think it's related to concurrency issues anyway.

**Comment by jfrerich** [comment]
Thanks for the reply, @mickmister.  Based on our discussion regarding sufficient error messages, not getting any further reports of this issue, and the belief this has been resolved, I'm closing this ticket.
