### ISSUE TITLE
Jira issue viewing in RHS panel

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#565]
### Summary

Users want to see details about Jira issues without switching contexts to a browser. Some users have also said that they don't want the channel getting "spammed" with issue cards that unfurl automatically. I'm proposing that we automatically append a "tag" to any Jira issues mentioned in a channel (via autolink detection?) that lets a user see the details about the jira issue in the Right Hand Side Panel. 

I'm proposing that we use the RHS panel to make it easy to see all the key details about jira issues - including comments about the issue.   Ideally, the fields that are displayed on the panel are customizable or at least contain the "required" fields for the issue. 

This is a very rough draft of the concept:
 
![image](https://user-images.githubusercontent.com/7575921/83475546-2e58c880-a454-11ea-8b18-e3026c3467a8.png)

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-17887

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
