### ISSUE TITLE
Add button to Channel Menu

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#568]
### Summary
A user should be able to subscribe to Jira notifications from the current channel's menu bar.  The channel's header bar is too visible for certain actions that need to performed every once in a while. 

This is the channel menu 
![image](https://user-images.githubusercontent.com/7575921/83795066-89610a00-a664-11ea-9c07-36752c811cb5.png)

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-19905

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-plugin-jira/pull/587 can be used as a starting point but needs permission checks

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
