### ISSUE TITLE
document custom certificate authority setup

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#569]
### Summary

Please view the following two Mattermost messages for context.

#### Post 1
0.) You will need to know where you $JAVA_HOME is OR find out where your instance's "keystore" is located by [[# find / -name "keystore"]]
1.) # openssl s_client -connect my.mattermost.com:443 -servername my.mattermost.com:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/my_mattermost_public.crt
2.) # Edit the my_mattermost_public.crt fil so it containes only what is between the -----BEGIN CERTIFICATE----- && -----END CERTIFICATE----- lines.
3.) # <JAVA_HOME>/bin/keytool -import -alias my.mattermost.com -keystore <JAVA_HOME>/jre/lib/security/cacerts -file ~/my_mattermost_public.crt

#### Post 2
I was up to the point where I needed to "connect" inside XYZProject -> Project Settings -> Integrations -> Mattermost Integrations and it was failing with the following error:

"Connect error!

Slack request access error : [sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target]." 

The following steps corrected the underlying issue that Sectigo (formerly comodo) was not stored as a trusted source in my Keystore.

0.) You will need to know where you $JAVA_HOME is OR find out where your instance's "keystore" is located by [[# find / -name "keystore"]]
1.) # openssl s_client -connect my.mattermost.com:443 -servername my.mattermost.com:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ~/my_mattermost_public.crt
2.) # Edit the my_mattermost_public.crt fil so it containes only what is between the -----BEGIN CERTIFICATE----- && -----END CERTIFICATE----- lines.
3.) # <JAVA_HOME>/bin/keytool -import -alias my.mattermost.com -keystore <JAVA_HOME>/jre/lib/security/cacerts -file ~/my_mattermost_public.crt
4.) I repeated steps #2 and #3 for my_jirainstance.com ssl certificate seeing as how they were on separate domains. I just wanted to be save (possibly not needed)
5.) I restarted jira after the above [[# cd /etc/init.d && ./jira stop && ./jira start ]]
6.) Inside Jira I went to XYZProject -> Project Settings -> Integrations -> Mattermost Integrations -> Connect and the system connected fine.

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-21227

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
