### ISSUE TITLE
Subscriptions functionality should restrict users to creating subscriptions that respect their Jira security level

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#573]
### Summary

We've created the ability to filter out issues from subscriptions based on security level.But the subscription must deliberately be made secure by setting filters.

Because Filters have always been optional, subscriptions can be used to circumvent jira security level by simply leaving them out of filters. This current design only makes sense if the Mattermost user with access to subscriptions is also a highly privileged user in Jira as well. 

The subscriptions functionality should be changed so user can only create subscriptions that match the security level they have access to in Jira. This way subscriptions access can be granted to users more safely.

Steps:
* Create 2 issue security groups in Jira "Public" and "Internal" 
* Create a user in Jira that can read "Public" issues but not "Internal" issue
* In Mattermost login as a user with access to create subscriptions that is mapped to the Jira user above
* As the Mattermost user create a subscription for the target project and do not add any filters.
* Have a Jira user crate an issue of security level internal
  * **Observed**: The subscription delivers data that this user would not be able to read from Mattermost. 

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-21361

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
