### ISSUE TITLE
Investigate: Limit availability of Jira plugin to certain LDAP groups

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#574]
### Summary
We have large customers with many users, and when Jira is installed it becomes very visible to all users equally.  We have recently added the concept of LDAP group syncing and some customers have asked for the ability to "hide" the jira integration from certain users.  This is primarily about the actions and slash commands - not around restricting Jira content (such as jira update messages sent into channels).

### Original Jira Ticket
https://mattermost.atlassian.net/browse/MM-17823

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
