### ISSUE TITLE
For the Attach and Create Issue post menu features, support attaching certain messages from a thread

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#575]
Original thread: https://community.mattermost.com/core/pl/wp7c1ap86tg97qh9af6g4auino

Currently you can only attach a single post to a Jira ticket. It would be convenient to be able to pick from posts in the thread through a modal that scans the given thread. You would need to fetch all the posts in the thread to be sure they are available to be used in a select dropdown.

The link at the end of the description/comment can still link to the specific post the user clicked on the post menu dropdown.

Here is a suggestion for what we could show in the body:

@ali.farooq [Link](https://community.mattermost.com/core/pl/wp7c1ap86tg97qh9af6g4auino)
Can I request a feature for the jira plugin:
Somehow let users attach multiple messages in one shot, rather than attaching one by one

---

@ali.farooq [Link](https://community.mattermost.com/core/pl/s69piagjp3dz9d1bz4eekesegy)
Feature I'm referring to

---

@michael.kochell [Link](https://community.mattermost.com/core/pl/pty15cx3dtf87ephk3aijf91we)

@ali.farooq I really like this idea. Do you mind making a GitHub ticket in the Jira plugin repo where we can discuss the UX for it?

**Comment by mickmister** [comment]
@gabrieljackson I think your concept in the Wrangler plugin of having an active state of choosing posts would be really useful here. The user could select multiple posts then confirm their choice to attach them as one comment to a Jira ticket.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
