### ISSUE TITLE
Update plugin-jira documentation 

### ISSUE THREAD

**Issue by Francois-D** [mattermost/mattermost-plugin-jira#579]
Update documentation for the [Plugin-Jira](https://mattermost.gitbook.io/plugin-jira/)

- Add the administrator slash commands to the plugin-jira documentation.
https://mattermost.gitbook.io/plugin-jira/admininstrator-guide/administrator-slash-commands
- Make updates to the installation steps `#2` .
Clarify Jira Server vs Jira server (case).  
- Edit step `#4` - Clarify   
 Setup webhooks from Jira to Setup Webhooks on the Jira Server
https://mattermost.gitbook.io/plugin-jira/setup/configuration#step-4-required-setup-webhooks-from-jira

**Comment by hanzei** [comment]
@justinegeffen Did https://github.com/mattermost/mattermost-plugin-jira/pull/668 resolve this issue?

**Comment by jfrerich** [comment]
@hanzei That PR did not resolve this issue.  This will be moved to v3.0.1 add added to the 3.0.0 docs asap
