### ISSUE TITLE
Add Custom Field to Subscription

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/mattermost-plugin-jira#585]
I tried searching for this issue and didn't see it so I apologize if this is covered somewhere else, but we are new to the Jira plugin and one of our users brought up a question about subscriptions that I didn't have a good answer for. In our Jira instance we have a custom field that lets users assign issues inside of a project to a "team". And so the issue is that if they subscribe to that project they get updates for every issue and don't have the ability to filter down to a specific team. Here is a heavily redacted screenshot so hopefully what I'm talking about makes sense.

![Jira_teams_example](https://user-images.githubusercontent.com/50209602/84295522-4e515180-ab10-11ea-8ec0-d8e52f0e20ff.png)

So is there a way to filter by a custom field or is that something that could potentially be implemented?

**Comment by mickmister** [comment]
Hi @ewwollesen , I have a few questions:

- What version of the Jira plugin are you using?
- What version of Jira are you using? It should be at the very bottom of every page on Jira's interface. For example `v7.13.14`
- Is it possible for a Jira admin to look in the issue schema to see what _kind_ of field this is? Here's an example of a `Select List (single choice)` field in the `Custom Fields` page of the Jira admin console:

![image](https://user-images.githubusercontent.com/6913320/86377671-9d455f00-bc56-11ea-8ccc-8c621c52b5ae.png)

**Comment by mickmister** [comment]
@ewwollesen Most custom field types are supported for subscription filters. Here's an example for filtering on the `Team` field I've shown above:

![image](https://user-images.githubusercontent.com/6913320/86378279-7b98a780-bc57-11ea-844b-e2ed82322cec.png)

You can include, or exclude, one or more values for each custom field.

**Comment by mickmister** [comment]
@ewwollesen How are you doing? Have you had a chance to see my comments above?

**Comment by levb** [comment]
Closing since no response
