### ISSUE TITLE
Cant connect user via /jira connect

### ISSUE THREAD

**Issue by Hottemax** [mattermost/mattermost-plugin-jira#588]
Environment:
- Self-hosted JIRA 8.5.1
- Self-hosted Mattermost 5.23.1
   - Jira Plugin 2.4.0

I get an error when connecting a user to Jira after entering the JIRA credentials:

**failed to get temporary credentials for moa9qizt1in3zf9gcz4c54rp3e: unexpected end of JSON input**

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<style>
			body {
				color: rgb(23, 43, 77);
				letter-spacing: -0.01em;
			}

			.flex-parent {
				padding: 50px;
			}

			.message-container {
				padding: 1.6em 0 0.8em;
				opacity: .6;
			}
		</style>
		<link rel="stylesheet" href="https://unpkg.com/@atlaskit/css-reset@2.0.0/dist/bundle.css" media="all">
	</head>
	<body>
		<div class="flex-parent">
			<h3>
				Failed to connect to Jira.
			</h3>
			<div class="message-container">
				<div>Failed to get temporary credentials for moa9qizt1in3zf9gcz4c54rp3e: unexpected end of JSON input</div>
			</div>
		</div>
	</body>
</html>
```

I assume it has to do with user access rights, but I cant find any documentation how to fix this problem ...

**Comment by hanzei** [comment]
@Hottemax Dos this happen with every user? Or just with one?

@levb This is caused by https://github.com/mattermost/mattermost-plugin-jira/blob/e51e09019bd8337b92ba3ec1382dcd81cb218ce6/server/kv.go#L650 failing. Do you see any reason that invalid json data could be stored?

**Comment by Hottemax** [comment]
> @Hottemax Dos this happen with every user? Or just with one?

I tried it with several users and browsers, it worked for three users and failed for about 10 or so. All connection attempts were made from the same desktop computer.

**Comment by hanzei** [comment]
I'm out of ideas. @levb ?
