### ISSUE TITLE
"only cloud instances supported for autolink" should be logged at INFO instead of WARN

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#589]
I believe a log warning is unwarranted just because a Jira plugin instance has a Jira Server instance installed. 2/5 INFO or DEBUG should be used instead.

**Comment by DigasNikas** [comment]
Greetings,
Can I lend a hand on this one?

**Comment by mickmister** [comment]
@DigasNikas Absolutely! Thanks!!
