### ISSUE TITLE
Refactor test code to use avoid superfluous calls to `mock.AnythingOfTypeArgument("string")`

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#590]
Our test code is riddled with several sequential calls to `mock.AnythingOfTypeArgument("string")`. We can instead create a helper function like `mockBatch("string", numCalls)` to do this in one line. Here's an example:

https://github.com/mattermost/mattermost-plugin-jira/blob/dd988f94ebcf834806aeabefc470b410977dc187/server/issue_test.go#L212-L225

**Comment by DigasNikas** [comment]
Greetings,
Can I lend a hand on this one?
