### ISSUE TITLE
Add Support Additional Events

### ISSUE THREAD

**Issue by mediavariance** [mattermost/mattermost-plugin-jira#6]
I'm interested in adding support for additional events and looking for feedback. I'd love to see support for:

- Comment (Created/Updated/Deleted)
- Work Log (Created/Updated/Deleted)

**Comment by hanzei** [comment]
@levb Will #22 cover both of this?

**Comment by levb** [comment]
Comments - yes, Work Log - no.

The issue with worklog hooks is that there does not appear to be enough data in the webhook message, so we need to go with Oauth/API to get more details (like the issue key - the message only seems to include the issue ID)

**Comment by szi-secunet** [comment]
How about changes of the issue priority?

And how about direct messages, if the issue gets assigned to someone?

**Comment by levb** [comment]
> How about changes of the issue priority?

Yes

> And how about direct messages, if the issue gets assigned to someone

The "re-assigned" events are now supported, but no user mapping is performed yet, so the new assignee appears in the post by JIRA name; One could set up notifications to be triggered by that, but may be kind of spammy.

**Comment by jasonblais** [comment]
To summarize the conversation 

> Comment (Created/Updated/Deleted)

This has been added with https://github.com/mattermost/mattermost-plugin-jira/pull/22, and scheduled for Jira v2.0 release.

> Work Log (Created/Updated/Deleted)

Not planned, but I've opened a help wanted ticket. We welcome contributions to add support for these events.

https://github.com/mattermost/mattermost-plugin-jira/issues/85

> How about changes of the issue priority?

This is planned to be supported by a new Jira subscription feature, scheduled for Jira v2.1 release. The subscription feature was started with https://github.com/mattermost/mattermost-plugin-jira/pull/61, and we have a Jira ticket to include issue priority notifications as part of this feature (see https://mattermost.atlassian.net/browse/MM-15678).

> And how about direct messages, if the issue gets assigned to someone?

This has been added with https://github.com/mattermost/mattermost-plugin-jira/pull/62, along with a slash command (`/jira settings notifications on/off`) to control whether direct messages are received for issue assignments.

The feature is scheduled for Jira v2.1 release 

---

If you are wondering about dates for Jira v2 releases, see the latest timelines here: https://github.com/mattermost/mattermost-plugin-jira#2-jira-plugin-v2-roadmap

**Comment by jasonblais** [comment]
Thank you all for the feedback! I'll close the issue based on the response above, and we'll track the outstanding items via 
 - https://github.com/mattermost/mattermost-plugin-jira/issues/85
 - https://mattermost.atlassian.net/browse/MM-15678

If you have any questions, don't hesitate to let me know!
