### ISSUE TITLE
Feature to browse tickets in RHS

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#603]
Currently there is not a way to browse Jira tickets inside of Mattermost. Similar to how we can view GitHub issues/PRs in the RHS, we could do the same for Jira. However, JQL queries are often more varied and complicated than the ones provided by the GitHub plugin, so we will need a way to construct queries.

I propose a few different ways to perform a search, each used independently. The form can have different "modes":
- general search
- user-defined JQL search
- predefined saved filter in Jira

### General search
Using the `text ~` JQL syntax, we can perform a general search across different Jira fields. e.g. `text ~ "My favorite search terms"`

### JQL search
We would just put the user's search into a JQL query.

### Saved filters
Using the user's saved filters in Jira, we can form our JQL query from a predefined query. 

https://docs.atlassian.com/software/jira/docs/api/REST/6.2/#d2e1283
Use `GET /rest/api/2/filter/favourite` to fetch the saved filters.
Possibly also use `POST /rest/api/2/filter` to create a new filter from the RHS.

-----

We can have an optional project selector at the top of the form, that would include the project in the resulting JQL. It could be a multi-select, for organizations with lots of projects.

This RHS view should be view-only for displaying these tickets. No assigning etc from this view.

The bottom of the RHS view (below the scroll view itself) should show the total number of results, and allow for paging.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
