### ISSUE TITLE
Cannot paste text in desktop app's Jira connect dialog

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#605]
When connecting to Jira cloud from the desktop app, pasting my password into a text field resulted in my password being pasted into the center channel's post draft instead of the text box in the dialog. Right clicking the textbox had no effect.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/mxxx5ztypiyjuyudk9pp61w3qr) *by @mickmister*._

**Comment by DHaussermann** [comment]
@mickmister this sounds familiar. I feel like it's been fixed before. Can you please provide the version number of the desktop app your seeing this on?

**Comment by mickmister** [comment]
@DHaussermann I'm using v4.4.0-rc3

**Comment by DHaussermann** [comment]
Tested this on Mac v4.5 and v4.5.2
- Form what I remember, this was not Jira specific.
- Now paste does work when using the keyboard shortcut but when you right-click the context menu still does not display. I believe this is a known issue. I'll see if there's an open ticket for it.

**Comment by mickmister** [comment]
@DHaussermann Pasting via the keyboard on Mac does not work for me. It instead pastes the value into the center channel even though the Jira window has focus.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
