### ISSUE TITLE
There is no styling on disabled selects showing that they are disabled

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#614]
I noticed this during development. I think I ended up not having to disable any of them (they are simply hidden instead), but I thought this is worth noting.

*Issue transferred from https://github.com/mattermost/mattermost-plugin-ee-jira/issues/28*

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
