### ISSUE TITLE
Rename channel_settings files to channel_subscriptions

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#615]
The term `settings` is more appropriately named `subscriptions`. If we are configuring any `settings` for a channel, the only option is to actually configure `subscriptions`. The task is to rename files, components, function names, .etc appropriately as subscriptions, not settings.

*Issue transferred from https://github.com/mattermost/mattermost-plugin-ee-jira/issues/30*

**Comment by haardikdharma10** [comment]
Hi @jfrerich, can you give me more clarity on what exactly is to be done here? Also, the above url links to a 404 page.

**Comment by jfrerich** [comment]
@haardikdharma10, sure! cc: @mickmister for verification.

Basically, the term `settings` is more appropriately named `subscriptions`.  If we are configuring any settings for a channel, the only option is to actually configure subscriptions.  The task is to rename files, components, function names, .etc appropriately as subscriptions, not settings.

**Comment by jfrerich** [comment]
@mickmister, correct me if you think I am wrong, this task is unnecessary or needs to be scoped better.

**Comment by jfrerich** [comment]
For example https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/components/modals/channel_settings/channel_settings_internal.tsx#L23-L28

**Comment by mickmister** [comment]
> this task in unnecessary

I don't think it's unnecessary. It would improve discoverability and match the names of the features much better.

> needs to be scoped better

I think your description in your comment above https://github.com/mattermost/mattermost-plugin-jira/issues/615#issuecomment-748343073 explains it pretty well. Do you have a specific scope change in mind?

**Comment by jfrerich** [comment]
File name changes at a minimum would be great, but I think scrubbing out settings for variable, function, file, components, classes, .etc would be really helpful (especially for discoverability as you stated)

**Comment by mickmister** [comment]
Okay I agree, the task description should be updated to match your comment

**Comment by haardikdharma10** [comment]
@jfrerich, sorry to bother you but can you assign this to me? Just makes it easy for me to track my pending work. This task just left my mind.

**Comment by jfrerich** [comment]
@haardikdharma10, done!
