### ISSUE TITLE
`/jira instance uninstall server` autocomplete not reducing to only server options

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#616]
same for `/jira instance uninstall cloud`

![image](https://user-images.githubusercontent.com/7575921/85433958-e3117180-b54a-11ea-9b86-cbd5277ec619.png)

*transferred from https://github.com/mattermost/mattermost-plugin-ee-jira/issues/47*

**Comment by jfrerich** [comment]
The following is a quote from @levb in the transferred issue.

> I am not suer if this is of high value; 1/5 I'd advocate removing the entire "server/cloud" keywords from the command line and just making it work transparently.
> Also, uninstalling should probably require a confirmation - using a setting panel or a modal?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
