### ISSUE TITLE
Jira create is not included in slash command auto-complete

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#617]
There are no create options in the slash command auto-complete data

Based on the other options I expected to see `/jira create` and `/jira issue create`

It's not clear to me why these are missing or if there is some reason they were intentionally left out.

*Transferred issue from https://github.com/mattermost/mattermost-plugin-ee-jira/issues/57*

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
