### ISSUE TITLE
Delay opening subscribe modal until we know the user has permissions

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#620]
During the multi-server implementation, how we fetch subscriptions changed slightly. This resulted in a change of how the user is shown that they don't have permissions to edit subscriptions.

Previous functionality:
- User runs `/jira subscribe`
- Ephemeral message shows `Fetching subscriptions.` Permission checks begin
- If permissions valid, show modal and show data
- If permissions not valid, do not show modal, and show error in ephemeral message

Current functionality:
- User runs `/jira subscribe`
- Modal opens. Permission checks begin. Loading spinner is shown
- If permissions valid, keep modal open and show data
- If permissions not valid, close modal, and show error in ephemeral message

The problem with the current one, is that the modal flickers if the user does not have permissions, and the request for the permission check completes quickly.

I propose reverting to the old experience for a fix, and consider showing the error message in the modal instead, after this release.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-jira/pull/621
