### ISSUE TITLE
Use GetPluginStatus plugin API method before adding autolinks

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#624]
Currently, we try to communicate to the autolink plugin without first verifying that the autolink plugin is installed and/or active. This results in unnecessary errors being logged if the plugin is not available. We can instead use the PluginAPI method [GetPluginStatus](https://developers.mattermost.com/extend/plugins/server/reference/#API.GetPluginStatus) to make this process much smoother.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/9fbtxdssciytjduau8oemjen5y) *by @mickmister*._

**Comment by carantunes** [comment]
Can I help out with this one? :)

**Comment by mickmister** [comment]
Absolutely!! Thanks @carantunes!
