### ISSUE TITLE
JS error occurs after creating a jira issue from post

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#646]
When creating a Jira issue from a post on Daily, the ticket was created successfully, but I got this js error in the console
```
Uncaught Error: Given action "jira_connected", reducer "defaultUserInstanceID" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
```

_Issue created from a [Mattermost message](https://community.mattermost.com/_redirect/pl/6pkrm67uhj8wpdst5dhdbbzkqr) *by @mickmister*._

**Comment by mickmister** [comment]
Scanning the code for usage of `defaultUserInstanceID`, the only bad thing that happens as a result of this, is that the user will not have the instance auto-chosen for them. But this could be a sign of a bigger issue.
