### ISSUE TITLE
Having a open bracket breaks how link display is managed by jira plugin

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-jira#649]
as you can see [here](https://community-daily.mattermost.com/core/channels/bugs/pppwz49rfiy43pr88mow1a7scw), I accidentally hit enter when only "[webapp" was written in the title having the jira integration display the link incorrectly. 

![image](https://user-images.githubusercontent.com/7575921/91200363-af76d300-e6c4-11ea-8901-97b096f54560.png)

Original Jira Ticket: https://mattermost.atlassian.net/browse/MM-27890

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
