### ISSUE TITLE
Improve experience when `/jira subscribe` is loading modal information

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#656]
There are a few improvements that can be done to improve the behavior of the subscribe modal when the user types `/jira subscribe`.

1. Use a loading indicator in the initial post that gives the user feedback that something has started loading
2. If something fails during opening of the modal, update that same post with failure information instead of making a new post.
3. If there are no errors, the initial post can be deleted.

More information can be found here https://github.com/mattermost/mattermost-plugin-jira/pull/621#issuecomment-685836024

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
