### ISSUE TITLE
Avoid the "fetching" text in ephemeral post when it's looking to see if the user has permissions. 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#657]
Currently, when a user attempts to open the subscriptions modal they will see an ephemeral post saying that their permissions are being fetched. If they do not have access they will then see a 2nd ephemeral post saying they do not have access. 

We should enhance the UX here by showing some kind of visual element to indicate that something is loading rather than an ephemeral post that permissions are being checked.   

Current behavior:
![NoMoreModalFlash](https://user-images.githubusercontent.com/35588783/93224044-b4b4c400-f73e-11ea-8f96-a3399a54834e.PNG)

**Comment by hanzei** [comment]
Discussed offline: Drop the ephemeral post if loading the permissions take longer then 1 second.

**Comment by haardikdharma10** [comment]
Hi @hanzei, just to be clear here, only the first ephemeral post is to be dropped right? Removing [this line](https://github.com/mattermost/mattermost-plugin-jira/blob/master/webapp/src/components/modals/channel_subscriptions/channel_subscriptions.tsx#L44) from the code will do the job! Let me know what you think !?

**Comment by hanzei** [comment]
That seems like the line in question. Dropping it would do the job.
