### ISSUE TITLE
Reporter image is blurry in issue preview

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#659]
#### Summary

The Jira plugin displays the reporter's Jira image in a post after creating an issue. The reporter's image is pixelated, maybe we can an avatar link that has higher resolution. Jira gives us a few different options to choose from when we fetch the profile picture.

#### Screenshots

![image](https://user-images.githubusercontent.com/6913320/93614727-820a0600-f9a0-11ea-9002-53d6ea14901d.png)

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
