### ISSUE TITLE
/jira instance connect shows URL instead of instance allias

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#673]
Not sure how important this is but, `/jira instance connect` if the instance has an alias, it will not be shown. This is inconstant with `disconnect` which will show the alias.    

- Install a 2nd instance
- Set an alias for the instance
- /jira instance connect  

**Observed** the URL is shown instead of the alias 

Note: This is also the case but, that seems like a good thing since the admin can certain of what they're doing.

**Comment by AayushChaudhary0001** [comment]
@wiggin77 @DHaussermann I went through the issue above and found one more possible flaw in the current implementation, which is as follows:.
Although, I am not sure if we can provide the same name to 2 different instances installed, in such a case, there would be a confusing situation.
What I would suggest is, we can implement an approach in which we show both the alias or name (as the main heading) and the instance link (as supporting text). 

This can help us solve both issues in a single way.
