### ISSUE TITLE
`Issue Updated: Any` subscription setting should include catch all comment events

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#676]
For Jira Cloud and Server `Issue Updated Any` is only capturing Comment Updated events. `Comment Created` and `Comment Deleted` events do not appear when you are subscribed to Any

**Note** An issue mentioned in this task specific to Cloud has been removed. This was an error caused by webhook misconfiguration

**Comment by DHaussermann** [comment]
@mickmister, for the issues regarding comments on Jira Cloud, this sounds very familiar to me. Release testing has no special notes regarding this but, is this maybe a known limitation of our integration?

**Comment by mickmister** [comment]
@DHaussermann Do you receive DM notifications for these events? If that's the case, I don't see why the subscriptions wouldn't work properly. Anything coming back in the response in your ngrok console?

**Comment by DHaussermann** [comment]
@mickmister No, when I am the assignee, I do not get DM notifications on Cloud. There is a bug for this here https://github.com/mattermost/mattermost-plugin-jira/issues/479

Could this same issue also be the cause here?

**Comment by mickmister** [comment]
@DHaussermann What about for mentions? If so, I think it may all be the same issue

**Comment by DHaussermann** [comment]
@mickmister Please disregard the question. This was caused by a misconfigured webhook. 

As such I updated the description. The 1 remaining issue is far less severe and has an easy work-around of explicitly adding 2 events.

**Comment by mickmister** [comment]
@DHaussermann Now that I recall,  `Issue Updated: Any` was never supposed to include comment events. @aaronrothschild Should `Issue Updated: Any` be a catch-all for all events?

**Comment by aaronrothschild** [comment]
> @DHaussermann Now that I recall, `Issue Updated: Any` was never supposed to include comment events. @aaronrothschild Should `Issue Updated: Any` be a catch-all for all events?

IMO, yes - I think comments should be included and act as a catch all.

**Comment by promulo** [comment]
Hello, is this one up for grabs? I'd like to give it a try. :)

**Comment by mickmister** [comment]
Hi @promulo! My apologies for the late response. I'll assign you the ticket, please let me know your current thoughts on this 🙂
