### ISSUE TITLE
Default instance and project do not update when you must navigate to Jira to finish saving an issue

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#682]
When you can only start creating an issue form Mattermost because there are unsupported fields, the default instance and project will not update.

For users who use a project that contains unsupported custom fields, they have no way to leverage the default project and instance functionality.

- Setup a Mattermost instance connected to 2 Jira instance 
- Locate a target jira instance and project where an unsupported custom fields (such as a number field) is mandatory
- From a Matter most post, select Create Jira issue 
- Select target instance and project
- Fill in the fields shown in the modal and click save
- User id shown a link to navigate to Jira and finish saving their issue
- Go save the issue (optional)
- Open the create modal again

**Observed**: Default instance and project are not set

**Comment by DHaussermann** [comment]
@aaronrothschild, I really don't know how common it is for user to use the integration to partially  create an issue. Please confirm this can wait until the 3.0.1 release.

**Comment by aaronrothschild** [comment]
Confirmed - this can wait until the 3.0.1 release

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
