### ISSUE TITLE
Support transition webhook event

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#685]
Currently, issue transitions are not supported as webhook events. The task here is to edit the webhook parser to take into account the transition.

The transition webhook payloads do not contain the `webhookEvent` field, nor the `issue_event_type_name` field. These fields are currently used as the main indicator of how to process a webhook event. For the transition event case, we will instead need to look for the presence of the `transition` property in the webhook payload. Here is an snippet of a transition event payload:

```
{
    "transition": {
        "workflowId": 3580030,
        "workflowName": "SW Workflow 2.3",
        "transitionId": 871,
        "transitionName": "Request CCB",
        "from_status": "In Development",
        "to_status": "In Development"
    },
    "comment": "",
    "user": {...},
    "issue": {...},
    "timestamp": 1598893874818,
	...
}
```

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
