### ISSUE TITLE
Add a "public" flag option to the `/jira view <key>` to post the link to the channel - not an ephemeral message.

### ISSUE THREAD

**Issue by aaronrothschild** [mattermost/mattermost-plugin-jira#691]
From a customer: 

> "When you do a ‘/jira view <issue-key>’ it displays the issue only visible to you. 
> 
> Is there a way to make that viewable to the channel? Or maybe adding a ‘/jira show’ or ‘/jira print’ which functions the same way as view but displays output to the channel. 
> 
> Use case: “Hey Bill did you see this latest service desk ticket?” <run /jira show>. 
> 
> As it currently is, you either have to copy the URL to the Jira issue and post in the channel (then they have to click on it, and open browser and log in…), OR copy the output of /jira view and paste it into a channel post and it completely mangles the format. 
> 
> Even just being able to copy the output of /jira view and paste it and have it maintain its basic format and issue link and description would be a gigantic improvement. Any others make this request for a ‘/jira show’? This one seems like a small development investment but large efficiency payoff.

Two possible approaches:
- Add a "public" flag to the `/jira view` command such as `/jira view mm-123 public` would post a public message to the current channel instead of an ephemeral one. 
- Add an interactive "Share Publicly" button to the epehemeral message itself, and let the user click it to make a post in that channel if they want to.  This button could be shown on the ephemeral message after a jira issue is created as well. 
- Or do both...

**Comment by hectorgabucio** [comment]
Hello @aaronrothschild can I do this?

**Comment by aaronrothschild** [comment]
@hectorgabucio Absolutely, thanks for your help - let me know if you have any questions.  Myself @mickmister or @jfrerich (Developers at Mattermost) will be happy to hep as this moves along.  I was JUST talking with a customer about this yesterday - they would be very excited if this feature moved along!

**Comment by mickmister** [comment]
@hectorgabucio Thanks for your interest in contributing to the project! If you'd like, you can join the [Jira plugin channel](https://community.mattermost.com/core/channels/jira-plugin) on our community server to discuss more with the team.

**Comment by mickmister** [comment]
@hectorgabucio I think the public button should also show in the output of `/jira create` (after the issue is created). Can you check to see if this is the case?

**Comment by hectorgabucio** [comment]
@mickmister 
![image](https://user-images.githubusercontent.com/7504298/96175789-ad462d80-0f2b-11eb-842c-111071f50189.png)

PS: I was trying different styles, thats not the final look, we are discussing it in the jira plugin channel, there you will find more pictures and updates :D
