### ISSUE TITLE
Jira v3 Post menu options do not update until refresh on Community

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#694]
There is an issue occurring on Community that does not seem to repro on other servers. When a users connected / disconnected status changes, the post menu options for connecting or creating and attaching do not change until a refresh is done. 

I have tested this on my local and other servers and I do not see this issue. Post menu options update without a refresh based on my status. 

This is occurring on community with the 3.0.0 release applied.

Seps:
- with a connected user note that create and attach options are available
- type /jira disconnect
- Feedback post shows user is disconnected
- Post menu now shows Connect to Jira option
- type /jira connect
- Authenticate user in the pop-up window
- Feedback post show user has connected   

**Observed**: 
- Post menu still shows connect option until next refresh
- No JS error seen in the console

**Comment by catalintomai** [comment]
@mickmister to add thread.

**Comment by mickmister** [comment]
Here's some discussion https://community-daily.mattermost.com/core/pl/g9qdgr84qtr9brfm1pfw8gkbic

The conclusion is to have `GetUserInfo` accept a second argument of `*User`, and avoid a trip to `MigrateV2User` if it is passed in. So far, this would only be for the one call from `disconnectUser`. Other places may need to be updated.
