### ISSUE TITLE
JS error occur when running /jira view 

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#698]
When I  run the /jira view command I see 2 different JS error appear in the console.

![Screen Shot 2020-10-13 at 9 20 22 AM](https://user-images.githubusercontent.com/35588783/95868565-5a585480-0d38-11eb-82fe-688da91f25b4.png)
![Screen Shot 2020-10-13 at 9 21 56 AM](https://user-images.githubusercontent.com/35588783/95868572-5cbaae80-0d38-11eb-8391-15f5e2f7f012.png)

Steps:
- Locate a Mattermost instance (I used 5.28-release as my version) deploy the Jira plugin built from then master branch. 
- Install and connect to an istance
- Type `/jira issue view <issue-Key>` 
**Observed**: The post appears as expected but, JS errors are shown in the console

**Comment by DHaussermann** [comment]
Dylan to confirm this bug is still valid.

**Comment by raghavaggarwal2308** [comment]
I tried to reproduce the issue but its no longer reproduced.
