### ISSUE TITLE
Reporter should receive DM when someone comments on their issue

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#699]
Currently the assignee of an issue receives a notification when someone comments on an issue they are assigned to. It would be beneficial if the reporter could also receive a notification.

**Comment by wijayaerick** [comment]
Hi @mickmister, can I work on this?

**Comment by mickmister** [comment]
> Hi @mickmister, can I work on this?

Absolutely! Thanks @wijayaerick!!

**Comment by mickmister** [comment]
@maisnamrajusingh Please comment here so I may assign you to the ticket

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
