### ISSUE TITLE
When a subscription posts to a channel, show the subscription name in the post.

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#700]
When a subscription posts to a channel, there is currently no way to know which subscription generated the message. If we include the subscription name in the post, users will be able to know more about why the notification was posted.

**Comment by wijayaerick** [comment]
Hi, I would like to give it a try

**Comment by jials** [comment]
Hi @mickmister I would like to take on this task if possible. Thanks!

**Comment by mickmister** [comment]
> Hi @mickmister I would like to take on this task if possible. Thanks!

@jials Awesome! It's all yours 🙂
