### ISSUE TITLE
Implement subscription "draft" feature

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#701]
Currently, subscriptions can only be set up by designated admins. Other users cannot make specialized subscriptions for their own DM notifications for example.

Main feature:
- We can allow all users to create a draft of a subscription, and have them approved by an admin
- Any further change to the subscription will need to be approved as well.
- Non-admin users should only be able to see their own created subscriptions whenever they open the subscriptions modal.
- Non-admin users should only be able to view, delete, or edit the draft for their own subscriptions. This should be enforced on the backend.
- The same rules that apply to creating subscriptions (user must be a member of the given Jira project for example), should apply to creating/editing drafts. The admin approving must also have these same permissions to approve the subscription.
- The same subscription modal can be used, but in "draft" mode.

Extras:
`/jira subscribe list` should indicate which subscriptions were drafted by non-admins, and any that have pending drafts. A non-admin user should only see their own subscriptions/drafts when they run this command.

We can also include the subscription id in the `/jira subscribe list` output. Then create a new command `/jira subscribe edit (instance ID)` to open up the modal for the subscription. The admin should be able to edit and/or approve any pending drafts.

**Comment by aaronrothschild** [comment]
@mickmister I would caution against this complexity... I think a user with this much subscription needs could make a channel specifically for this.  

If they want to watch their own set of chosen notifications, I think we should consider adding notifications on "Watched" items in Jira for a user and notifying them via the bot.  I realize this isn't exactly the same as the ticket description. Customers have mentioned that sort of feature before, but not for creating all sorts of personal custom subscriptions.  Also, having the admin review them is really unappetizing to the admin...

**Comment by mickmister** [comment]
@aaronrothschild 

> I think we should consider adding notifications on "Watched" items in Jira for a user and notifying them via the bot

Claimed HW ticket for this https://github.com/mattermost/mattermost-plugin-jira/issues/507

I think having custom subscriptions in your own DM would be immensely powerful and provide so much value. The subscriptions feature is likely very under-utilized in this regard. Users could have their own tailored notifications. If the admin doesn't want the feature on their server, they can disable it 🙂

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
