### ISSUE TITLE
Sync with starter template

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#706]
The starter template is at a good spot to sync with different projects. Syncing now will help Hacktoberfest

**Comment by hanzei** [comment]
Maybe this is also a good time to rename `readme.md` into `README.md` for consistency.

**Comment by haardikdharma10** [comment]
Hi @mickmister, @hanzei, I'd like to take up this task. Except for renaming `readme.md` to `README.md` , what else is the scope of the task?

**Comment by hanzei** [comment]
@haardikdharma10 https://github.com/mattermost/mattermost-plugin-starter-template/pull/86 did add a tool to sync plugin repositories. That should be used to sync the file with the starter template. One example PR is https://github.com/mattermost/mattermost-plugin-github/pull/363. Let me know if that helps.

**Comment by mickmister** [comment]
@haardikdharma10 If you'd like to work on this task, you can message me on community to discuss what needs to be done

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
