### ISSUE TITLE
Check for autolink plugin panics

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#708]
The check for the autolink plugin's availability logs an error, but it's referencing the wrong error variable. We also don't make sure the error is not nil before calling `.Error()`
https://github.com/mattermost/mattermost-plugin-jira/blob/789d142a062d5d82c87f3ff846d80360ea97c1ca/server/plugin.go#L310-L314

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/dwfqssit37fgfjqcad8n9stzyc) *by @mickmister*._

**Comment by promulo** [comment]
Hi @mickmister since I stumbled on this one I think I can submit a PR for that.
