### ISSUE TITLE
 error messages for multiple Jira instances incorrect

### ISSUE THREAD

**Issue by svelle** [mattermost/mattermost-plugin-jira#719]
We say you need an enterprise license when in reality you need an E20 license, this should be properly reflected in the error to not confuse customers on E10 or E0/TE.
https://github.com/mattermost/mattermost-plugin-jira/blob/c5d366c8243ccd7d926dfd5e097ac78602641fcd/server/command.go#L790

https://github.com/mattermost/mattermost-plugin-jira/blob/0c04ea41daf62fcfb6682644ea5927370fc7ebe5/server/instances.go#L136

**Comment by haardikdharma10** [comment]
Hi @svelle,  can I go ahead and fix this?

**Comment by svelle** [comment]
> Hi @svelle, can I go ahead and fix this?

sure go ahead. Looks like no one has so far started work on this :)
