### ISSUE TITLE
Many calls to `LoadInstances()` in server do not have error checked

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#722]
Looking through the code, I see that many calls to `LoadInstances()` does not have its error checked. For every call to `LoadInstances`, we should handle it as we are in places where we are already handling the error. This PR is relevant https://github.com/mattermost/mattermost-plugin-jira/pull/721

**Comment by haardikdharma10** [comment]
Hi @mickmister, I would like to give this one a shot.

**Comment by mickmister** [comment]
Sounds good, thanks @haardikdharma10!
