### ISSUE TITLE
Intermittent issue where jira options are not visible after connect / disconnect status changes  

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#729]
I am seeing an intermittent issue where Jira options are missing from the post menu immediately after the connection status has changed. refreshing the client solves the problem. 

For example immediately after disconnecting, the `Connect to Jira` option is missing from the post menu until you refresh. Or, immediately after connecting the create and attach options are missing until you refresh.

This issue is intermittent. It seems to repro only about 1/10 times. It also seems like if I have the same user logged into multiple sessions I can't repro it.

When this does occur:
- A corresponding websocket event can be seen in dev tools
- The websocket message show the correct state of connection to JIRA
- The websocket message is missing the list of instances and shows empty user data instead (see below)
- Ephemeral post shows normally based on the status you have changed to    

```
{
    "event": "custom_jira_connect",
    "data": {
        "can_connect": false,
        "instances": [
            {
                "alias": "",
                "instance_id": "https://mmtest.atlassian.net",
                "type": "cloud"
            }
        ],
        "is_connected": true,
        "user": {
            "id": "",
            "delete_at": 0,
            "username": "",
            "auth_service": "",
            "email": "",
            "nickname": "",
            "first_name": "",
            "last_name": "",
            "position": "",
            "roles": "",
            "locale": "",
            "timezone": null
        }
    },
    "broadcast": {
        "omit_users": null,
        "user_id": "d48ffdrzyfg38pduafz6ssyddh",
        "channel_id": "",
        "team_id": ""
    },
    "seq": 11
}
```

**Update**:
I see this occurring on HA server with DB replicas relatively often. It also occurs after creating Jira issues. Seems to occur within 3 attempts. 
    
- Refresh fixes it
- Happens on both cloud and server
- When there is an additional instance available to connect to it will show "connect" option instead of nothing
- When there is an additional instance available it will show the connect Jira options
- Seems to happen within 3 attempts
- Still occurs on connect / disconnect
- Does not seem related to using a different instance than the last create  
- Occurs even if only 1 instance is installed
- Does not reproduce fir me on my local

After issue posted event occurred, the following WS event was shown

```
{event: "custom_jira_connect", data: {can_connect: true,…},…}
broadcast: {omit_users: null, user_id: "wn1tfhhezp88dgokf5qia3q34e", channel_id: "", team_id: ""}
channel_id: ""
omit_users: null
team_id: ""
user_id: "wn1tfhhezp88dgokf5qia3q34e"
data: {can_connect: true,…}
can_connect: true
instances: [{alias: "", instance_id: "http://dkh-jira.ngrok.io", type: "server"},…]
is_connected: true
user: {id: "", delete_at: 0, username: "", auth_service: "", email: "", nickname: "", first_name: "",…}
auth_service: ""
delete_at: 0
email: ""
first_name: ""
id: ""
last_name: ""
locale: ""
nickname: ""
position: ""
roles: ""
timezone: null
username: ""
event: "custom_jira_connect"
seq: 9
```

**Comment by mickmister** [comment]
@DHaussermann In which environments is this occurring?

**Comment by DHaussermann** [comment]
@mickmister this occurs on this server here: https://dkh-5-28.test.mattermost.cloud (this server would need to be upgraded now) which was created with the `/cloud` plugin. To the best of my recollection I never reproduced locally.

**Comment by mickmister** [comment]
Closing until reproduction steps are solidified
