### ISSUE TITLE
User should receive a DM notification if mentioned in an issue's description

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#732]

**Comment by petersveter108** [comment]
Hello, I'd like to work on this one, could you please assign me?

**Comment by mickmister** [comment]
For sure @petersveter108! My apologies for responding so late 🙂

**Comment by mickmister** [comment]
Hi @petersveter108, how is everything going? Let me know if you have any questions on the ticket 🙂

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
