### ISSUE TITLE
Ping Jira instance when a new instance is installed

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#745]
When `/jira instance install...` is run, there is currently no attempt to check if the URL given is valid. We can have the plugin ping the Jira instance, and expect a certain response based on if it's a Jira Cloud or Jira Server instance.

If we get an invalid response, we can show a message like:

> It looks like we couldn't validate the connection to your Jira server. Please make sure the URL was entered correctly. This could also be because of existing firewall or proxy rules. If you intend to have a one way integration from Jira to Mattermost this is not an issue.

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/9aqhqda6638nzxp6exe6ewhijr) *by @svelle*._

**Comment by sonereker** [comment]
Hi, I'd like to take this.

**Comment by mickmister** [comment]
Awesome, thanks @sonereker!

**Comment by sonereker** [comment]
Will try to deliver this tomorrow.

**Comment by wiersgallak** [comment]
This was completed. Closing issue.
