### ISSUE TITLE
Application Link setup instructions don't reflect reality...

### ISSUE THREAD

**Issue by SnorreSelmer** [mattermost/mattermost-plugin-jira#747]
Jira Server: 8.5.8
Mattermost: 5.31.1
Jira Plugin: 3.0.1

I'm trying to set up the application link, and the instructions Mattermost gives look like this:
![image](https://user-images.githubusercontent.com/19710528/111311717-d72c8900-865e-11eb-8c17-6a244957708c.png)
...while in Jira it looks like this:
![image](https://user-images.githubusercontent.com/19710528/111311979-1f4bab80-865f-11eb-994f-89260e835010.png)

We're trying to set up full Mattermost/Jira integration, but it's just not working out.

**Comment by SnorreSelmer** [comment]
Um... Wow... I think I've been distracted by "duplicate" info.. Closing...

**Comment by mickmister** [comment]
@SnorreSelmer Do you mind explaining what was confusing and what we can change that may have avoided the issue?
