### ISSUE TITLE
Mattermost Attach to Jira Issue Dialog has problems with issue search on Jira side

### ISSUE THREAD

**Issue by adammorawski1** [mattermost/mattermost-plugin-jira#748]
When user is trying to find issue on the Jira side search results are inconsistent.
I.e. Issue GEN2-3080 is mentioned in the description of the issue IT-406. When user is trying to attach message from the Mattermost and he/she is typing GEN2-3080 in Ira Issue line only issue IT-406 is found. However if user is typing Summery text for GEN-3080 issue is being found. This is very inconsistent and in the results users are creating unnecessary issues in Jira. 

Issue is associated with .\server\issue.go file

line 642 is:
var reJiraIssueKey = regexp.MustCompile(`^([[:alpha:]]+)-([[:digit:]]+)$`)

and it should be:
var reJiraIssueKey = regexp.MustCompile(`^([[:alnum:]]+)-([[:digit:]]+)$`)

If you use only :alpha: it will exclude issues with alphanumeric key like GEN2-3080

**Comment by wiersgallak** [comment]
This appears to have been resolved. Closing issue.
