### ISSUE TITLE
Enabling plugin adds autolinks

### ISSUE THREAD

**Issue by GrzegorzRussek** [mattermost/mattermost-plugin-jira#751]
Plugin automatically add patterns and templates to autolink plugin.
This behavior should be intentional not automatic, because it breaks our autolink configuration.

**Comment by mickmister** [comment]
@GrzegorzRussek Thanks for reporting this, the feature should definitely be configurable.

@aaronrothschild Thoughts on how to go about this? Currently, the Jira plugin registers regexes with the autolink plugin when the Jira plugin starts up, and when a new Jira instance is installed with the plugin. I'm thinking we can have a system console setting to enable the autolink functionality. Unclear whether the default should be on or off.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
