### ISSUE TITLE
Display post actions as submenu items

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#760]
Currently the post action menu gets crowded when there lots of plugins installed. We can utilize the plugin registry's [registerPostDropdownSubMenuAction](https://developers.mattermost.com/extend/plugins/webapp/reference/#registerPostDropdownSubMenuAction) method to register the items in a more consolidated way.

Here's an example usage of this feature: https://github.com/mattermost/mattermost-plugin-demo/blob/7f8d96cedcf6f96b76267d8bac57f875f441dc3a/webapp/src/plugin.jsx#L126-L147

-----

Current look

<img width="300" src="https://user-images.githubusercontent.com/6913320/114093463-21cda980-9889-11eb-8f1e-4d81a98b90cc.png"/>

-----

Proposed look

<img width="400" src="https://user-images.githubusercontent.com/6913320/114093286-e9c66680-9888-11eb-8b1c-110dcb44d694.png"/>

**Comment by mickmister** [comment]
@abhijit-singh What do you think about the proposed change? Should there be icons in the submenu for each item? FYI the core webapp is placing the left chevron there, so the plugin itself doesn't have control over that. We can however adjust styling of the component to the right of the chevron.

**Comment by abhijit-singh** [comment]
@mickmister I'm not sure yet if this is the approach we want to take the solve the problem of too many plugin actions making the post-action menu very crowded. The drawback of this one would be that the menu could still get crowded in cases when lots of plugins/apps are installed. 

Another solution is to show two or three most used (or selected by some logic/user input) plugin actions upfront, and nesting everything else under a 'More actions' menu item. 

With what you've proposed in this issue, would we be forcing all plugins that have multiple menu items in the post-action menu to combine them under a single menu item or would it be the plugin developer's choice?

**Comment by mickmister** [comment]
> With what you've proposed in this issue, would we be forcing all plugins that have multiple menu items in the post-action menu to combine them under a single menu item or would it be the plugin developer's choice?

@abhijit-singh It would be the plugin developer's choice. The submenu functionality shown in the screenshot has actually been available for a while, but hasn't been used because of a css bug which has since been fixed.

I agree that this isn't solving the issue when having a very large number of plugins, but this ticket is mainly meant to make use of the submenu since we haven't been able to until that css bug was solved, which was solved in 5.26. I think making a `More Actions` menu is the right solution for the general problem, but we have the code in place to use the submenus and I thought the plugins would be better organized if they use that functionality. Especially since there are many plugins with two items.

If we do go with having this ticket be implemented, what do you think about having the icons duplicated on each submenu item?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
