### ISSUE TITLE
/Jira Connect doesn't open mattermost's subpath url

### ISSUE THREAD

**Issue by sphr** [mattermost/mattermost-plugin-jira#768]
We have our mattermost installation running in a subpath called /app/ (picked by us), when a user runs the /jira connect command, mattermost opens a new window that does not include /app/ in the url, but instead uses /plugins/jira/ directly.

Please make sure the URI includes the user's subpath as this is a configurable variable plugins need to be aware of.

**Comment by mickmister** [comment]
Thanks @sphr, looks like we need to prepend the site url here https://github.com/mattermost/mattermost-plugin-jira/blob/9681f1eddf3ddf7714970508cf2aa232827a4b4e/webapp/src/actions/index.ts#L416

**Comment by sanjaydemansol** [comment]
@hanzei how do we get that variable?  using `GetConfig()` ?

**Comment by hanzei** [comment]
@sanjaydemansol Jep. `GetConfig()` returns the mattermost config where you find the  [`SiteURL`]( https://pkg.go.dev/github.com/mattermost/mattermost-server/v5/model#ServiceSettings).
