### ISSUE TITLE
When a channel is deleted /jira subscribe list gives Failed to Get Channel error

### ISSUE THREAD

**Issue by eosophob1a** [mattermost/mattermost-plugin-jira#772]
**Observed Behavior:**

When a user deletes a channel that had jira subscriptions the plugin fails to find the channel when running `/jira subscribe list` with the error of Failed to get Channel.  It also generates 404 errors in the `mattermost.log` which can potentially lead to log bloat.  

**Expected behavior:**

`/jira subscribe list` works as intended

**Steps to Recreate**

1.  Install Mattermost and Jira plugin
2. Add a subscription to a channel
3. Delete the channel in the database
4. Attempt to run `/jira subscribe list`

**Comment by mickmister** [comment]
2/5 Suggest we log `DEBUG` when a channel does not exist for a given subscription and move on, instead of bailing out of the entire `subscribe list` command execution.

We currently don't have a way to delete a subscription for a channel that does not exist. A workaround would be to have the admin manually edit the JSON array of subscriptions and remove the entries, though this is very tedious and error-prone.

**Comment by jfrerich** [comment]
Thanks for the issue submission, @eosophob1a.  

I am 5/5 in agreeance with @mickmister's suggestion that we log the missing `channel_id` and move on with the `/subscribe list` command execution.  For reference, the code that will need to be adjusted is https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/subscribe.go#L386-L391

I'm 0/5 if we should add any other enhancements beyond what is suggested. I would suggest this is a corner case and directly deleting a `channel_id row` from the `channels table` in the database is not suggested.

If we were to add a more complete set of commands to accommodate this corner case, I'd suggest we do something like the following:

* modify the `/jira subscribe list` to show subscriptions to channels that don't exist.
  *  show a list of sub names with channel ids at the end of the currently printed ephemeral message.  (this would be the cue to remove them with the following command)
* implement a `/jira subscribe remove-deleted-channel-subs

**Comment by mickmister** [comment]
@jfrerich If we have a 100% accurate way to know that this channel has been deleted and there is no way we are getting it back, specifically a channel that will have the same id as the subscription is expecting, we should remove the subscription while we are looping over the subscriptions.

If we failed to get the channel for any other reason, we should just debug log and move on with other subscriptions. This way, we don't need to have the `remove-deleted-channel-subs` command.

**Comment by jfrerich** [comment]
@mickmister I agree. I'll check the description of the error message when a channel has been deleted.  If the channel is 100% deleted, I'll remove the subscription.  For all other reasons, I'll debug log and move on.  I'm not going to add `remove-deleted-channel-subs` option.  This is overkill and should almost never be needed.

**Comment by mickmister** [comment]
@jfrerich The situation of having a deleted channel may cause issues in other cases as well, like when we handle the webhook call from Jira. Please try and see what potential pitfalls there are in that regard. If there are issues there, we shouldn't rely on `/jira subscribe list` to clean up data.

**Comment by mickmister** [comment]
The code that runs when we receive a webhook call may need to do some clean up as well to avoid issues

**Comment by jfrerich** [comment]
I'll check the code that receives a webhook too.
