### ISSUE TITLE
Add tooltip for jira ticket links

### ISSUE THREAD

**Issue by hanzei** [mattermost/mattermost-plugin-jira#774]
Implement something similar to https://github.com/mattermost/mattermost-plugin-github/issues/255

It should show:
- Ticket name
- Status
- Type
- First few characters from the description

**Comment by sanjaydemansol** [comment]
@hanzei, we have any screenshots or something for where to create this tooltip?

**Comment by hanzei** [comment]
The GitHub implementation can be a guideline on how this should look like.

I've asked a UX designer on my team for a more concrete design. Will keep you updated.

**Comment by hanzei** [comment]
JIRA ticket for the design: https://mattermost.atlassian.net/browse/MM-37599

**Comment by hanzei** [comment]
Design: https://www.figma.com/file/qRfj3yxoajQnkVJPZkoaRq/MM-37599-Jira-Ticket-Popover

**Comment by maisnamrajusingh** [comment]
@hanzei im assigning this to @jupriano and wanted to ask about the approach we are taking for this. 
1. create an api to fetch the ticket details if it doesn't exist 
2. fetch data on the frontend to display the data

**Comment by hanzei** [comment]
Only the server knows the credentials to fetch the data. Hence, we need an API.
