### ISSUE TITLE
Images in plugin docs should have descriptive names

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#779]
Right now the images in the [docs folder](https://github.com/mattermost/mattermost-plugin-jira/tree/master/docs/.gitbook/assets) are named `image.png`, `image (1).png`, and so on. We can instead have the image file names describe what the picture is for. There are also lots of duplicate images in the docs folder.

The task here is to:
- Name the files to be more descriptive (see list below)
- Go through the docs files and update paths to the correct image file names
- If any are duplicates, update the image path to the named file

`docs/.gitbook/assets/image.png` - `create-from-post.png`
 
`docs/.gitbook/assets/image (1).png` - `attach-from-post.png`

`docs/.gitbook/assets/image (2).png` - `restrict-mattermost-users.png`

`docs/.gitbook/assets/image (3).png` - `ticket-created.png`

`docs/.gitbook/assets/image (4).png` - `mention-notification.png`

`docs/.gitbook/assets/image (5).png` - `jira-slash-command.png`

`docs/.gitbook/assets/image (6).png` - `restrict-jira-users.png`

The rest of the image files that begin with the word `image` are duplicates of these files

**Comment by nishit-prasad** [comment]
Hello I'm new and would like to work on this to get started. Can I take this up if it's available?

**Comment by mickmister** [comment]
Hi @nishit-prasad! Sure thing, I'll assign you to the ticket

**Comment by nishit-prasad** [comment]
Thank you! Appreciate it!

**Comment by nishit-prasad** [comment]
@mickmister
Do you have any docs with proper directions to setup my environment before making the changes?

**Comment by mickmister** [comment]
@nishit-prasad Our docs are currently just markdown files. Gitbooks hosts and renders the documentation straight from the markdown files.

What editor are you using? I use VSCode, and it has a feature where you can view render a markdown file for viewing. You right click a file in the left pane, and select "Open Preview". This is how I develop the documentation locally:


<img width="500" src="https://user-images.githubusercontent.com/6913320/125137447-b17a3280-e0da-11eb-8376-5a4573bb2158.png"/>

**Comment by nishit-prasad** [comment]
Yeah that works for me. I use VSCode too. Do you have any specific markdown file I should look at?

**Comment by mickmister** [comment]
@nishit-prasad Everything that needs to change to complete the issue should be within the `docs` folder

**Comment by nishit-prasad** [comment]
Okay thank you!

Never used Gitbooks. This way I will learn. I will ping if I have further questions/concerns.

**Comment by nishit-prasad** [comment]
@mickmister PR is up and ready 😄 
(you may see some additional changes because of whitespace characters - my VSCode editor automatically formatted it somehow)

Further question: would you like me to delete the duplicate images (that start with `image..`)?

**Comment by manasisaiba** [comment]
is this issue still open for work?

**Comment by mickmister** [comment]
Hi @manasisaiba! It looks like @nishit-prasad has implemented the changes at https://github.com/mattermost/mattermost-plugin-jira/pull/782

This ticket is currently unavailable since there is an assignee on this ticket and the "Up for Grabs" label is not present on this ticket. If you would like to find a ticket to work on, I would include the "Up for Grabs" label in your search. If you have any questions on the contributing process, you can message me on https://community.mattermost.com at `@michael.kochell`.

Thanks for your interest in contributing @manasisaiba! Hope to see you around 🙂
