### ISSUE TITLE
Instructions for gettting this into Jira as an application? 

### ISSUE THREAD

**Issue by mathurin68** [mattermost/mattermost-plugin-jira#787]
Stupid question... 

We're pretty new to Jira... is there instructions anywhere for getting this as an application into Jira? I.E.  is there a jar file somewhere in here?   
The instructions just say...
Step 2: Install the plugin as an application in Jira

but there isn't really instructions on doing it.  

Thanks!

**Comment by mickmister** [comment]
Hi @mathurin68! In the section of documentation you're looking at https://mattermost.gitbook.io/plugin-jira/setting-up/configuration#step-2-install-the-plugin-as-an-application-in-jira, it says to run one of these commands in Mattermost:
- `/jira instance install server <your-jira-url>` if you are using Jira Server
- `/jira instance install cloud <your-jira-url>` if you are using Jira Cloud

To run the command, type the command in Mattermost's chat text box, replace `<your-jira-url>` with your Jira instance's URL, and send the message. The command will run and you be given further instructions on-screen for setting up.

Thanks for using Mattermost and the Jira plugin! Let me know if you have any further questions on the integration.

**Comment by mathurin68** [comment]
Haha... I saw that and didn't think it could be that easy!  Thank you... efforting.
