### ISSUE TITLE
Create issue modal should automatically prepopulate the chosen issue type once project is selected

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#790]
Currently the modal automatically chooses the project you used the last time you submitted the modal, but the issue type then must be selected to show the issue form fields. If we automatically selected the issue type (can just be the first one that shows up in the issue type data e.g. "Story"), the user can start filling out the form very quickly.

<img width="500" src="https://user-images.githubusercontent.com/6913320/127226638-d7fbea4c-6d14-47dc-9d85-99b3f86d5d88.png"/>

**Comment by catalintomai** [comment]
*@catalintomai attached a* [message](https://community.mattermost.com/_redirect/pl/riagqgjcjf8fbqikwnmaff17ea) *from @catalintomai*

test

**Comment by catalintomai** [comment]
*@catalintomai attached a* [message](https://community.mattermost.com/_redirect/pl/riagqgjcjf8fbqikwnmaff17ea) *from @catalintomai*

test

**Comment by Nikhil-1503** [comment]
Can I work on this?

**Comment by mickmister** [comment]
Sure @Nikhil-1503! It's all yours 😄

**Comment by maisnamraju** [comment]
@mickmister  would like to pick this one up for the next sprint as I am already working on the modal for the create issue.

**Comment by mickmister** [comment]
Hi @Nikhil-1503, how are things going for you? Do you still have interest in this ticket? Any questions we can answer?

**Comment by mickmister** [comment]
@maisnamrajusingh Keep in mind that along with this proposed fix, I suggest we also just show only one loading screen until we've fetched the issue fields for the default issue type. So to the user it will look like three steps:

- Select project
- Loading
- Selected issue type is shown, along with all the fields needed to create an issue

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
