### ISSUE TITLE
x.509 error on /jira connect

### ISSUE THREAD

**Issue by mathurin68** [mattermost/mattermost-plugin-jira#793]
This is a new install... 
/jira instance install server <your-jira-url>   seemed to go Ok. I followed the instructions that popped up in Mattermost and that seemed to go off without any errors.  

but then on '/jira connect' I get the message...

`failed to get a connect link: Post "https://<server>.net/plugins/servlet/oauth/request-token": x509: certificate signed by unknown authority
`
I'm sure it's something in our environment, but I was curious if someone else has come across it. 

Thanks!

**Comment by thomas-trenz** [comment]
Same error here since a few days.

**Comment by Frank-vd-Horst** [comment]
I know this post is old, but YES, I now have the same problem...
I have the feeling that this has to do with SSO. Are you using an external SSO solution by any chance?
Did you ever fix your problem?

Thanks

**Comment by raghavaggarwal2308** [comment]
@mathurin68 @Frank-vd-Horst @thomas-trenz Are you still facing the issue or we can close it?

**Comment by raghavaggarwal2308** [comment]
Closing for now. Can reopen if someone faces this issue again
