### ISSUE TITLE
Update project to use npm 7

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#796]
The Mattermost web application [repo](https://github.com/mattermost/mattermost-webapp) has switched to using npm version 7, which can cause compilation issues to plugins that are configured with a version of npm less than 7.

The task here is to convert this project to use npm 7. A similar PR was made here https://github.com/mattermost/mattermost-plugin-playbooks/pull/609

**Comment by mickmister** [comment]
This may be causing the errors seen in the "Generating Coverage Results" step in this CI run: https://app.circleci.com/pipelines/github/mattermost/mattermost-plugin-jira/2494/workflows/f0c2176b-6e3c-470f-b33c-766f12d428ca/jobs/7822

**Comment by sibasankarnayak** [comment]
@mickmister wanted to work on this , wanted to check how to reproduce the issue 

will it be like , upgrading the NPM to version 7 and deploy the plugin will help to reproduce. ?
any suggestion is appreciated
