### ISSUE TITLE
When the epic link changes for an issue, link to the epic in the resulting post

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#798]
The below screenshot shows the epic link changing from `MM-35529` to `MM-29077`. An issue here is that there is no indication of what the name of these epics are. Fetching the epic name is unnecessarily costly, so we can instead link to the epic.

<img width="700px" src="https://user-images.githubusercontent.com/6913320/130872155-648640b3-076d-4a2c-9538-57da6f4a50b3.png"/>

The source of the above post is:

`Ben Schumacher **updated** Epic Link from "MM-35529" to "MM-29077" on story [MM-35072: MM Apps - Update bindings when an app in installed](https://mattermost.atlassian.net/browse/MM-35072)`

Using the Jira instance's URL, and the project key that contains the Epic, we can instead change the message to:

`Ben Schumacher **updated** Epic Link from [MM-35529](https://mattermost.atlassian.net/browse/MM-35529) to [MM-29077](https://mattermost.atlassian.net/browse/MM-29077) on story [MM-35072: MM Apps - Update bindings when an app in installed](https://mattermost.atlassian.net/browse/MM-35072)`

to be rendered as:

Ben Schumacher **updated** Epic Link from [MM-35529](https://mattermost.atlassian.net/browse/MM-35529) to [MM-29077](https://mattermost.atlassian.net/browse/MM-29077) on story [MM-35072: MM Apps - Update bindings when an app in installed](https://mattermost.atlassian.net/browse/MM-35072)

**Comment by seppewyns** [comment]
Hey, can I work on this?

**Comment by mickmister** [comment]
You got it :+1: Thanks @seppewyns!

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
