### ISSUE TITLE
Make "localhost is not a valid MM siteURL" message more clear

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#808]
Maybe the error message could be a bit more describing on the reasoning why the URL is invalid. (`X is not a valid URL that is reachable from the public internet`)

_Issue created from a [Mattermost message](https://community-daily.mattermost.com/_redirect/pl/3ouqespkgt8u3mcke8o9zhbedw) *by @hanzei*._

**Comment by mickmister** [comment]
Original message:

![image](https://user-images.githubusercontent.com/6913320/134924298-5771c2ab-d0ea-4437-a20a-849ace513ca9.png)

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue

**Comment by mickmister** [comment]
Thanks @himanshu007-creator! It's all yours 🙂
