### ISSUE TITLE
Cross-plugin task: Add "npm ci" step to each plugin repo, to catch "npm i" misuse

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#814]
Running `npm ci` will check if the package-lock.json file is out of sync. If this fails, CI should fail, so the circle ci jobs need to be updated to run this command.

@hanzei Should this be an update to an appropriate orb, or should it be done in each project?

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
