### ISSUE TITLE
Create issue modal crashes when assignee is selected before switching projects

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#819]
Repro steps:

- Use the post dropdown menu to open the create issue modal
- Pick a project that has an assignee field
- Pick an issue type
- Pick an assignee
- Go to the top of the modal and select a different project
- Select an issue type

Expected: More fields show to create an issue
Observed: Webapp crashes

**Comment by sanjaydemansol** [comment]
Hi, @mickmister I am unable to reproduce this one.

**Comment by dipak-demansol** [comment]
adding a video so everyone can see how to regenerate the issue.

https://user-images.githubusercontent.com/89907719/147808095-6d4d6718-0dfe-4874-9902-00fb1693b064.mp4

**Comment by mickmister** [comment]
There is an abandoned PR that has most pieces implemented https://github.com/mattermost/mattermost-plugin-jira/pull/848
