### ISSUE TITLE
Unable to get updates to comments

### ISSUE THREAD

**Issue by maxammann** [mattermost/mattermost-plugin-jira#829]
I'm unable to configure the Mattermost plugin to send notifications about comments.
The Jira is successfully sending webhook requests to the Mattermost. I succesfully validated that events like `comment_deleted` get sent to the Mattermost by enabling debugging features within Jira.

I configured the following subscription in Mattermost:

![image](https://user-images.githubusercontent.com/905221/149156348-49116ba2-d84e-4463-a4bf-b6ff5bb3ae2c.png)

This configuration works for example for the "Issue Created" event. I tried to create comments with issues where I'm assigned without success.

I'm also unsure how notifications about comments are supposed to work. Is it possibel to create a mattermost channel which receives all updates about comments? Is is possible to DM created Jira comments to Mattermost users?

**Comment by maxammann** [comment]
I'm no longer using this plugin. But I don't think it was addressed. Maybe though it was fixed by accident.

**Comment by raghavaggarwal2308** [comment]
Closing for now. Can reopen if someone else faces this issue.
