### ISSUE TITLE
Jira subscriptions modal needs explanation in the docs

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#830]
The Jira plugin docs show a picture of the channel subscriptions modal [here](https://github.com/mattermost/mattermost-plugin-jira/blob/master/docs/administrator-guide/notification-management.md#which-notification-events-are-supported), but there's no explanation of how to use the subscriptions modal.

At the moment, the frontend shows an "approximate JQL query" which reveals a lot of what the tool can do, but it's not obvious how it works. The docs seem like the right place to explain this. We can link to the docs from the frontend, and asynchronously update the docs.

**Comment by Nityanand13** [comment]
@mickmister Can you please explain the last line that you have written in the description of this issue?

> We can link to the docs from the frontend, and asynchronously update the docs.

**Comment by mickmister** [comment]
@Nityanand13 What I mean is that if we link to the docs in the UI, we don't need to edit the UI source code to update an explanation of the feature. Linking to the docs is a "one and done" task, and we can continuously iterate on the actual docs, and it will automatically be "updated" in the UI since the information is not actually in the UI.
