### ISSUE TITLE
Customers create task

### ISSUE THREAD

**Issue by paveluskov** [mattermost/mattermost-plugin-jira#832]
Hello,
Can user with role customer create tasks via mattermost?
Because we can't do this recently.

**Comment by jprusch** [comment]
Are you conferring to Jira Service Management projects? I'm pretty sure, that Jira Service Management customers are only allowed to create tasks using the customer frontend or a configured email address fro the service desk. This is a Jira restriction.

**Comment by paveluskov** [comment]
Yes, we have Jira SM.
But you approve that customers can create tasks with your plugin, is it correct?

**Comment by jprusch** [comment]
It's not my plugin. We're just using it with our Mattermost instance. And I do NOT approve that customers can create issues via this plugin. 
As each Mattermost user connects to his Jira account, I'm not sure, if this is possible for a Jira user without a agent and/or software license. Probably dependent on your Jira configuration.

**Comment by paveluskov** [comment]
> It's not my plugin. We're just using it with our Mattermost instance. And I do NOT approve that customers can create issues via this plugin. As each Mattermost user connects to his Jira account, I'm not sure, if this is possible for a Jira user without a agent and/or software license. Probably dependent on your Jira configuration.

Thank you for the answers!

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
