### ISSUE TITLE
Version Check has not yet been added to master branch

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#843]
We don't have a version bump PR for Jira yet, but I have done some testing from the `master` brach for the release. That said, I noticed that no PR was ever up to bump the minimum server version to `v6.5.0`

This should be in place to prevent the plugin from running on older server version as per previous discussions. 
![image](https://user-images.githubusercontent.com/35588783/156023005-5afd49e3-b963-4110-84b6-316d51211e5e.png)

**Comment by DHaussermann** [comment]
Maybe @levb can confirm my understanding of the expected behavior here.

**Comment by levb** [comment]
AFAIU, we do not require any new APIs from the server, merely exposing new hooks, therefore increasing the server version was not strictly necessary. I'll leave it to @hanzei to decide if we should update as a matter of policy.

**Comment by hanzei** [comment]
Yes, we should update the minimum server version to follow the policy we set our self.
