### ISSUE TITLE
Creating an issue causes a `Failed prop type: Invalid prop `value` supplied to  BackendSelector.`

### ISSUE THREAD

**Issue by maisnamraju** [mattermost/mattermost-plugin-jira#850]
Functionality wise it doesn't cause any problems but on opening the create issue modal and selecting a project, the following error comes up on the console 

<img width="533" alt="Screenshot 2022-03-16 at 10 36 25 PM" src="https://user-images.githubusercontent.com/2786378/158630040-60cd9a01-34cd-4793-84b3-7be20d2149c4.png">

**Comment by raghavaggarwal2308** [comment]
The issue not reproducibe anymore. Might have been fixed in a release.
