### ISSUE TITLE
Add support for Jira issue previews, including "/jira settings preview" command

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#86]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

**DETAILS**

When someone posts a link to a Jira issue, or a Jira issue key, a preview of the issue is shown in the Mattermost channel. The preview includes the assignee, status, type and priority as message attachment fields side-by-side,  when available, along with the description.

Desktop UI (wide, regular view, no description):

![image](https://user-images.githubusercontent.com/13119842/58442123-110d5380-80b6-11e9-8008-517c334c0a03.png)

Desktop UI (wide, regular view, with description):

![image](https://user-images.githubusercontent.com/13119842/58442101-d7d4e380-80b5-11e9-9953-f09d7a6058a5.png)

Desktop UI (narrow, mobile view):

![image](https://user-images.githubusercontent.com/13119842/58442104-dc999780-80b5-11e9-9468-b99bf9af8548.png)

**PERMISSIONS**

Those without permissions to view a Jira issue should see the following text in the resulting issue preview.

```
Those without permissions would see You do not have the appropriate permissions to view the issue. Please contact your Jira administrator.
```

**/JIRA SETTINGS**

Add a new slash command that enables users to enable or disable issue previews. It should default to "on".

- `/jira settings preview on` - enables issue previews
- `/jira settings preview off` - disables issue previews

You can review https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go for examples of other Jira plugin slash commands.

Note: In addition to adding support for `/jira settings preview [on/off]`, update the `/jira settings` entry in [`/jira help` command](https://github.com/mattermost/mattermost-plugin-jira/blob/master/server/command.go#L12) with the setting parameter now accepting both `notifications` and `preview` values.

**Comment by jasonblais** [comment]
@asaad.mahmood This would need a case where the user doesn't have permissions to see the issue preview.

Sample use case for Mattermost team: Someone posts a link to a private security ticket in Release Discussion channel

1. Those with permissions to view the ticket see the issue preview with description, assignee, etc as specified above
2. Those without permissions would see `You do not have the appropriate permissions to view the issue. Please contact your Jira administrator.` text in the preview.

Let me know your thoughts on the proposed UX.

**Comment by iandriyanov** [comment]
Hi, guys! 
`Version: 5.16.0
Build Number: 5.16.1
Build Date: Thu Oct 24 16:04:31 UTC 2019
Build Hash: b000d2fbfb2ae8104c890c921c4a518c553b4803
Build Enterprise Ready: false
DB Version: 5.16.0
`
I'd installed Jira plugin from marketplace Mattermost, paired with Jira account, installed connection from channel Mattermost. And i want ask you, feature are not available for me

`/jira help
/jira settings [setting] [value] - Update your user settings
[setting] can be notifications
[value] can be on or off
`
I really need this option. When someone enter issue key\keys or link.

**Comment by iandriyanov** [comment]
@jasonblais 

Any news?

**Comment by jasonblais** [comment]
@iandriyanov This ticket is currently open and up for grabs.

Anyone interested to help with this improvement?

**Comment by levb** [comment]
@iandriyanov This request all but requires being able to render the post differently for different users, and because these renderings may have different sizes has implications for things like scrolling of the channel.

Because it is non-trivial, we have not been able to prioritize it yet, really hoping that someone will come through with a simpler solution. Even mere ideas on how else this might work are welcome. Like, maybe we display an (unprotected) summary and then the user has to hit a "More" button to see the protected fields? cc @crspeller

**Comment by crspeller** [comment]
@levb @jasonblais  Agreed that this is more complicated then it seems. Maybe the fastest path to this feature is the iframe sidebar idea. Click on the issue and it opens in the sidebar.

**Comment by iandriyanov** [comment]
@levb @crspeller 
For me and mine team, important, to be able to highlight some TICKET-123mber as url to jira. 
Examples: in PM or Channels
me: Today i'll try to figure out RTV-2709.
other: *click on it                          ^^^^^* 
action: Open new tab with ticket page.

**Comment by iandriyanov** [comment]
It would be perfect, if TICKET-123mber -> parse and rewrite -> "TICKET-123mber - Python TDD blah blah blah"

**Comment by levb** [comment]
@iandriyanov have you checked out https://github.com/mattermost/mattermost-plugin-autolink? we use it to do precisely that on community.mattermost.com. Due to limitations in our config UI, it requires manual configuration using the /autolink command or by editing the config.json. @crspeller is currently looking into how we can automate the configuration so that the Jira plugin would populate the Autolink config with all known Jira project keys.

**Comment by BigFishLittleFish** [comment]
Hi, our users miss this functionality from HipChat since migrating across to Mattermost. Having this functionality would be a great feature.

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
