### ISSUE TITLE
Add ability to customize baseURL

### ISSUE THREAD

**Issue by ewwollesen** [mattermost/mattermost-plugin-jira#860]
The plugin currently uses the Mattermost `SITE_URL` to create the `baseURL`. This makes the plugin unusable for customers that have a different externally facing URL than what they use internally. They would like the ability to customize the `baseURL` rather than have it created based on the `SITE_URL`.

**Comment by varundey** [comment]
I can take this up.

**Comment by mickmister** [comment]
@varundey It seems there may be some unresolved requirements here

@ewwollesen Under what circumstances does this other URL need to be used?

- Webhooks requests?
- Requests to the plugin from the Mattermost UI?

**Comment by ewwollesen** [comment]
> @ewwollesen Under what circumstances does this other URL need to be used?
> 
> * Webhooks requests?
> * Requests to the plugin from the Mattermost UI?

In this particular case the customer could not use the plugin at all because Jira was trying to connect back to their `SITE_URL` which is different than their publicly facing URL. So while the ticket is no longer open and I can't ask the customer, my assumption would be that both of those need to be able to access the custom URL.

**Comment by mickmister** [comment]
@ewwollesen I'm not sure I understand. The Site URL is supposed to be the "publicly facing URL", especially for connecting via the Mattermost UI. What other reason is this setting set to some value? Should we close this ticket since the customer's ticket was closed?

**Comment by ewwollesen** [comment]
> @ewwollesen I'm not sure I understand. The Site URL is supposed to be the "publicly facing URL", especially for connecting via the Mattermost UI. What other reason is this setting set to some value? Should we close this ticket since the customer's ticket was closed?

They have an internal URL for Mattermost that the SITE_URL is set to, but when you access Mattermost externally you use a different URL which then forwards you (I don't know exactly how this is set up, if it's firewall rules, reverse proxy, etc) to the internal URL. I assume it's set up this way for security reasons?

**Comment by mickmister** [comment]
@ewwollesen Thanks for explaining :+1:

I'm not sure where the Jira plugin comes into play here in the situation you describe. Are other parts of the application being affected by this same issue of "incorrect site URL"? I'm thinking there is some detail missing here about their Jira setup, and in which exact situations do we need to use this other URL.

**Comment by mickmister** [comment]
Closing since this ticket seems invalid to me based on the discussion above
