### ISSUE TITLE
Support status field for subscription filters

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#862]
An admin is requesting for us to support the status field so issues set to certain statuses can be matched with the subscription.

Currently the data retrieved from `get-create-issue-metadata-for-project` does not contain the status field. Because of this, we can have the status field hardcoded in the "filters" on the client, as it is with the "event" choices of the subscription modal.

**Comment by orlandorode97** [comment]
Hey there, I'd like to work on this one, please

**Comment by mickmister** [comment]
Awesome :tada: Thanks @orlandorode97!
