### ISSUE TITLE
Jira issues cannot be created anymore with Jira Server/Datacenter 9.x

### ISSUE THREAD

**Issue by jprusch** [mattermost/mattermost-plugin-jira#865]
The REST endpoint rest/api/2/issue/createmeta has been removed in Jira 9, which, if used, makes creating Jira issues using REST not working anymore.

Please check:
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

**Comment by FlintCA** [comment]
I can second this issue. 

This also disables the ability to edit or create Jira Subscriptions.

**Comment by christiaanvaken** [comment]
Is this already solved?

**Comment by hanzei** [comment]
Yes, please use https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v3.2.3
