### ISSUE TITLE
When connecting server, if a user was already connected to that server, their client won't be updated until they reload

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#89]
Repro: (Admin-A refers to a MM System Admin; User-A refers to an end user)

1. Admin-A connects to Jira-A, User-A connects their account to Jira-A.
2. Admin-A disconnects from Jira-A, User-A is notified that they are no longer connected to a Jira instance (they are shown no menu items related to Jira).
3. User-A logs off, logs back on. Their state is "jira intance not connected" AND "user account not connected" (because there was no jira instance to test if their account was connected)
4. Admin-A connects back to Jira-A.

Observed: User-A is notified that they are now connected to a Jira instance. But their client state still thinks their user account is NOT connected. User-A reloads their webapp, and it correctly pulls that their account is connected.

Expected: User-A is notified that they are now connected to a Jira instance. The client correctly pulls that their account is connected.

---
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

**Comment by wiersgallak** [comment]
Closing issues due to inactivity. This issue can be re-opened with more interest from our community.
