### ISSUE TITLE
mattermost jira plugin directory structure renamed

### ISSUE THREAD

**Issue by dcherniv** [mattermost/mattermost-plugin-jira#9]
Hello

In the latest 5.6.0 release of mattermost, it appears that directory structure for jira plugin has changed.
```
~/prepackaged_plugins $ ls
com.mattermost.jira-1.0.2.tar.gz  zoom-1.0.3.tar.gz
~/prepackaged_plugins $ 
~/plugins $ ls -la
total 20
drwxr-Sr--    4 mattermo mattermo      4096 Dec 15 19:01 .
drwxr-sr-x    1 mattermo mattermo      4096 Dec 15 19:03 ..
drwxr-Sr--    3 mattermo mattermo      4096 Dec 15 19:01 com.mattermost.jira
drwxr-Sr--    4 mattermo mattermo      4096 Dec 15 19:01 zoom
~/plugins $ 
```

As a result the webhook in the old format no longer works from jira, returning 404.
`https://REDACTED/plugins/jira/webhook` returns 404
However the following works:
`https://REDACTED/plugins/com.mattermost.jira/webhook`

This appears to be a bug. Because the plugin page advises users to use the former instead of latter.
Please either update the plugin page or update the archive name.

**Comment by jwilander** [comment]
@hanzei yes, I think we should revert it back to `jira`

**Comment by hanzei** [comment]
Thanks for the bug report @dcherniv. v1.0.3 with a fix has been released: https://github.com/mattermost/mattermost-plugin-jira/releases/tag/v1.0.3.
