### ISSUE TITLE
Not able to subscribe to jira data center instance

### ISSUE THREAD

**Issue by clanzett** [mattermost/mattermost-plugin-jira#901]
After following the configuration guide, i am not able to subscribe to a jira project via '/jira subscribe edit' . The instance seems to be connected and i am also able to view single issues via '/jira issue view'. The following error appears in the mattermost errorlog:

`{"timestamp":"2023-01-05 08:37:57.260 Z","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:976","plugin_id":"jira","Status":"500","Error":"failed to GetProjectMetadata: Request failed. Please analyze the request body for more details. Status code: 404","Path":"/api/v2/get-jira-project-metadata","Method":"GET","query":"instance_id=https%3A%2F%2Fjira.XXXXX.xxx}`

Strange thing here is that it tries to reach '/api/v2/get-jira-project-' which is, as far as I understand it, the wrong path for a jira data center instance. Imho it should be: '/rest/api/2/get-jira-project-'. My data center version is v.9.3.1.

Best regards
Sebastian

**Comment by jprusch** [comment]
Hi,
we upgraded to Jira 9 mid of last year & since then Mattermost cannot connect to Jira anymore.

Please check:
https://github.com/mattermost/mattermost-plugin-jira/issues/864
https://github.com/mattermost/mattermost-plugin-jira/issues/865

I'm sure you hit exactly these problems.

Best regards

JP

**Comment by clanzett** [comment]
Hi JP,

yes i think they are related. I would guess that atlassian has moved several rest endpoints of their API so that the plugin is not able to reach them anymore. Thank you.

**Comment by christiaanvaken** [comment]
Any updates on this?

**Comment by clanzett** [comment]
Still not working :(

**Comment by jprusch** [comment]
Possible missing permissions on Jira projects. The user needs to be able to retrieve the issue types from Jira projects. If he can't do this for a project the error is thrown. If possible, make sure to test with a user can list the issue types in the projects he's allowed to see.

**Comment by clanzett** [comment]
No. I used admin credentials to test it.

**Comment by jprusch** [comment]
I'm also Jira admin. You must make sure that no Jira project uses a permission scheme where your admin account is not allowed to read the issue types using a rest call.
I checked the access log of the Jira Tomcat server. The meta data error is fixed, but afterwards the MM plugin requests the issue types for each project, one by one. This is where it failed for me until changing the permission scheme for in our case archived projects.

**Comment by clanzett** [comment]
so it will also fail, if it just tries to access archived projects, where i do not need access to?

**Comment by jprusch** [comment]
Could be. The devs are aware of the issue & know what to change.
A workaround can only be to either change the permission scheme or use a user who is not allowed to see the project at all. We changed the permission scheme for the user who edits the subscribtions....

**Comment by FlintCA** [comment]
To piggy back off @jprusch for a bit, with his suggestions of looking at the access log (Thank you!), I was able to get subscriptions working on 3.2.3. I am the sys admin for our mattermost and jira servers so that makes these steps easier. 

```
1. logged onto jira server and located my access_log, I use windows so it is program files\atlassian\jira\logs: access_log.YYYY-mm-dd
2. I ran '/jira subscribe edit ' 
3. Looked at the access logs for entries from my account and found the lines for: ' GET /rest/api/2/issue/creatmeta/<projectid>/... HTTP/1.1" 400
4. 400 being bad I then had to find out which projectID was throwing that 400.
5. To find the projectID I did the API call: <jira_URL>/rest/api/latest/project
6. I then went to that project and put myself as a developer/admin or whatever was needed to view project/issues. Or I just deleted the project because it was old and not used. 
7. ran '/jira subscribe edit ' and repeated the other steps until no more 400 errors appeared. Note, only one project at a time will 400 on you as the plugin stops at the first error. 
8. I was then able to create new subscriptions and create jira issues from chats. 
```

I hope this helps anyone else!
10.

**Comment by jprusch** [comment]
Exactly what I did... Thx for documenting!

**Comment by itsmichaelk** [comment]
I'm working in the same company as @clanzett and sadly I cannot confirm a successful approve.
Our Mattermost's log stating the /api/v2/get-jira-project-metadata isn't working on our jira data centre.
Since it's a data centre installation, the correct url should be https://jira.xxxxxx.com/rest/api/2/get-jira-project-metadata but all I get is a 404 with this response:
`{
  "message": "null for uri: https://jira.noscendo.cloud/rest/api/2/get-jira-project-metadata",
  "status-code": 404
}`

**Comment by jprusch** [comment]
I'm not sure about the URL you posted. Have you got a reference from Atlassian on the API being used?

You might want to consider:

https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#createmeta-in-integrations-that-work-across-versions---detect-a-new-api-functionality

**Comment by jprusch** [comment]
Discussion on Mattermost community let to:

> It seems as though the list was loading fine for me so long as both Browse Projects and Create Issues are applied to the target projects. No other permissions are needed to make a project "loadable" by the plugin.
> 
> The Archive status of any Project or the Browse Project Archive seem to have no effect when I created data and tested with this permission. 

So, if you've got access to a project you should make sure, that at least "Browse Project" & "Create Issues" are permitted.

**Comment by itsmichaelk** [comment]
> Discussion on Mattermost community let to:
> 
> > It seems as though the list was loading fine for me so long as both Browse Projects and Create Issues are applied to the target projects. No other permissions are needed to make a project "loadable" by the plugin.
> > The Archive status of any Project or the Browse Project Archive seem to have no effect when I created data and tested with this permission.
> 
> So, if you've got access to a project you should make sure, that at least "Browse Project" & "Create Issues" are permitted.

User is permitted for browsing projects and create issues and I did the createmeta api endpoints, but nothing changed. 
Still the 404 error code.

**Comment by jprusch** [comment]
What Jira Datacenter version are you using? The API change with Jira 9

**Comment by jprusch** [comment]
Please check:

https://confluence.atlassian.com/jiracore/preparing-for-jira-9-0-1115661092.html#:~:text=Restricting%20anonymous%20access%20to%20endpoints

**Comment by itsmichaelk** [comment]
> What Jira Datacenter version are you using? The API change with Jira 9

We're using 9.4.2 as our DataCentre version.

**Comment by jprusch** [comment]
OK, then the /rest/api/2/issue/createmeta request will not work anymore. createmeta will only work in context of a project.
`
The GET /rest/issue/createmeta endpoint removed from the API
The GET /rest/issue/createmeta endpoint allowed you to get metainformation on everything in Jira: projects, issues, etc. This opportunity had a big impact on Jira performance. That's why after a few updates and changes, we decided to remove it completely in Jira 9.0.

Instead, you can use the following endpoint to get metainformation on one project at a time:

GET /rest/api/2/issue/createmeta/{projectIdOrKey}/issuetypes
GET /rest/api/2/issue/createmeta/{projectIdOrKey}/issuetypes/
{issueTypeId}
`

**Comment by itsmichaelk** [comment]
No idea what happened, but now the /jira subscribed edit works.. thanks anyway, @jprusch !

**Comment by jprusch** [comment]
Miracles of Jira... ;-)

**Comment by raghavaggarwal2308** [comment]
> No idea what happened, but now the /jira subscribed edit works

Closing as completed
