### ISSUE TITLE
Clarify instalation instructions for Jira 9.x

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#907]
There is a slight UI change in Jira 9 for creating the application link. This new dialogue was added.
![image](https://user-images.githubusercontent.com/35588783/214913362-864c1651-31a0-494e-8aa9-7d62004c6fc4.png)

To install an instance the user must select Atlassian product. This is very counter intuitive.

I propose we update the instructions to guide people setting up with Jira 9.x

Current step 2.
_Enter https://mattermost-url/plugins/jira as the application link, then click Create new link._

Proposed step 2.
_Click "Create link" and enter https://mattermost-url/plugins/jira as the application link and then click "Continue". 
**note**: For Jira 9.x - Ensure "Atlassian product" is selected as the Application type._

**Comment by DHaussermann** [comment]
@mickmister and @hanzei  Please provide feedback. And possibly some information on why we have to Slect the Atlassian option. I'm a bit confused on this.

**Comment by mickmister** [comment]
@DHaussermann I agree that the docs need to be updated for this

I'm not sure the details of "Application product", though I know that "External application" is not the correct option based on its description. Our integration does not support OAuth 2.0, so that option won't work.

**Comment by mickmister** [comment]
From related comment https://github.com/mattermost/mattermost-plugin-jira/issues/864#issuecomment-1407476027

> * Make sure you created an ATLASSIAN application link
> * Ignore errors on the URL
> * On the "Link application" dialog, just enter the name (Mattermost) and select "Create incoming link". Leave all other fields empty
> * On the next page enter the data (public key...)
> 
> For more context you might want to read
> 
> https://community.mattermost.com/core/pl/pw4gs7imhidaugn4rrjbcgueno
> 
> in the Mattermost community
