### ISSUE TITLE
In the System Console, add Site URL and secret for the generated webhook URL

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#91]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

In Mattermost System Console > Jira settings page, we display a webhook URL for the admin to use when configuring webhooks in Jira.

![image](https://user-images.githubusercontent.com/13119842/58443557-97c72e00-80c0-11e9-90f3-11875d0e0ca2.png)

Proposal is to automatically update the Site URL and Webhook Secret for this URL, which makes it easier for an admin to configure it.

Note that this requires adding the ability for plugins to dynamically display or update text on the System Console settings page: https://mattermost.atlassian.net/browse/MM-11830

**Comment by levb** [comment]
This is now being replaced by the `/jira webhook` command
