### ISSUE TITLE
New command `/jira unassign <issue-key>`

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-plugin-jira#92]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Plugin: Jira" community channel](https://community.mattermost.com/core/channels/jira-plugin).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/) and our [Plugins Guide](https://developers.mattermost.com/extend/plugins/).

----

For a sample PR that added "/jira assign <issue-key> <assignee>" command, see https://github.com/mattermost/mattermost-plugin-jira/pull/60

A) Add "/jira unassign <issue-key>" command. <issue-key> refers to the Jira issue key such as "MM-14151"

When successful, the command does two things:
1. removes the assignee of a Jira issue.
2. sends an ephemeral message back to the channel the user posted their command with text

```
Unassigned Jira issue <issueKey>
```

B) The following is a list of error cases and the returned ephemeral message. The ephemeral message should have the same profile picture and username as other messages posted by the Jira plugin.

1. if user doesn't have permissions for the action, return ephemeral message "You do not have the appropriate permissions to perform this action. Please contact your Jira administrator.
2. if "/jira unassign" is posted, return ephemeral message "Please specify an issue key in the form `/jira unassign <issue-key>`"
3. if <issue-key> is not found, return ephemeral message "We couldn't find the issue key. Please confirm the issue key and try again."

**Comment by imazik** [comment]
hi @levb i would like to take it

**Comment by imazik** [comment]
@levb I am facing issue with make in my local setup. getting this error
```
go: github.com/cpoile/oauth2@v0.0.0-20190717235208-10945bd: invalid pseudo-version: revision is shorter than canonical (10945bd219c7)
rm -rf server/dist;
mkdir -p server/dist;
cd server && env GOOS=linux GOARCH=amd64 /snap/bin/go build  -ldflags '-X "main.BuildDate=Sat Oct 19 21:20:42 UTC 2019" -X "main.BuildHash=8d1a96baeb46dd18eca50511a6cc49b4892be1a8" -X "main.BuildHashShort=8d1a96b"' -o dist/plugin-linux-amd64;
go: github.com/cpoile/oauth2@v0.0.0-20190717235208-10945bd: invalid pseudo-version: revision is shorter than canonical (10945bd219c7)
make: *** [Makefile:91: server] Error 1
```

**Comment by gupsho** [comment]
I can take this.

**Comment by gupsho** [comment]
> I can take this.

Sorry did not see it was assigned already. Please ignore.

**Comment by levb** [comment]
@imazik @cpoile could this be a go version issue?

**Comment by cpoile** [comment]
@levb Yes, it's probably from updating to go 1.13.3. 
@gupsho You can fix that particular problem by replacing:
```
github.com/cpoile/oauth2@v0.0.0-20190717235208-10945bd
```
with
```
github.com/cpoile/oauth2 10945bd
```
And running `go mod tidy`, but then other things will start to break. I'm still figuring out how to get jira working with 1.13.3 -- mine just isn't working yet.

**Comment by imazik** [comment]
with what go version it is working 1.12?

**Comment by levb** [comment]
@imazik Are you interested in finishing this ticket? Or should we put this issue back into "Up for grabs"?

**Comment by jfrerich** [comment]
I've got this one.

**Comment by jfrerich** [comment]
resolved  https://github.com/mattermost/mattermost-plugin-jira/pull/460
