### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by rogerhsu1121** [mattermost/mattermost-plugin-jira#933]
When create a issue from Mattermost  using /jira command
e.g.
/jira issue create this is a test
Can't search or select Assignee/Label/Assigner/Owner/....
It shows  "SyntaxError: Unexpected end of JSON input"

![image](https://user-images.githubusercontent.com/47959538/232007791-03583720-bfa0-4320-9f61-46c68629902c.png)

**Comment by rogerhsu1121** [comment]
no cule

**Comment by m1lt0n** [comment]
@rogerhsu1121 Could you please share some more information:

1. What is the version of the plugin you're using
2. Are you using Jira cloud or Jira server and what version of Jira server if that's the case?
3. Could you please share any console logs from the network tab of the relevant AJAX requests that are unsuccessful with along their responses (to investigate the error)

**Comment by rogerhsu1121** [comment]
> @rogerhsu1121 Could you please share some more information:
> 
> 1. What is the version of the plugin you're using
> 2. Are you using Jira cloud or Jira server and what version of Jira server if that's the case?
> 3. Could you please share any console logs from the network tab of the relevant AJAX requests that are unsuccessful with along their responses (to investigate the error)
Thanks for reply
1. JIRA Plugin Version is Jira (jira - 3.2.4)
2. I use Jira Server (Version v7.2.7)
3. I got some log from Mattermost  ->System console->Server logs
> 
> 
> {"timestamp":"2023-04-19 09:51:22.442 +08:00","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/web_conn.go:830","user_id":"bc4jme54sp8mjmgbhayacnozmc","error":"read tcp 10.156.148.47:8065->10.57.57.196:50854: i/o timeout"}
> {"timestamp":"2023-04-19 10:01:09.442 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"yawhbxm1tjy8dq5rxd1b9oec5o"}
> {"timestamp":"2023-04-19 10:11:09.520 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"674oq6h6hbgfzj65sqew6nxmue"}
> {"timestamp":"2023-04-19 10:13:42.986 +08:00","level":"error","msg":"Received an unknown request as a Jira plugin:\nGET /plugins/jira/plugins/servlet/streams?use-accept-lang=true&streams=user+IS+DennisChen&local=true&maxResults=10 HTTP/1.1\r\nHost: 10.156.148.47:8065\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us, en;q=0.9, en-us;q=0.8, en;q=0.7, *;q=0.5\r\nConnection: Keep-Alive\r\nUser-Agent: Apache-HttpClient/4.4.1 (Java/1.8.0_102)\r\n\r\n","caller":"app/plugin_api.go:974","plugin_id":"jira"}
> {"timestamp":"2023-04-19 10:21:09.599 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"uifswjw4uffrbqegzwujwzj8ac"}
> {"timestamp":"2023-04-19 10:23:26.174 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> {"timestamp":"2023-04-19 10:23:26.197 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"403 Forbidden: : Request failed. Please analyze the request body for more details. Status code: 403","Path":"/api/v2/get-search-autocomplete-fields","Method":"GET","query":"fieldName=Labels&fieldValue=&instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com"}
> {"timestamp":"2023-04-19 10:23:26.221 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"403 Forbidden: : Request failed. Please analyze the request body for more details. Status code: 403","Path":"/api/v2/get-search-autocomplete-fields","Method":"GET","query":"fieldName=Requirement+Version&fieldValue=&instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com"}
> {"timestamp":"2023-04-19 10:23:26.259 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> {"timestamp":"2023-04-19 10:23:26.348 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> {"timestamp":"2023-04-19 10:23:29.417 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ssss"}
> {"timestamp":"2023-04-19 10:23:31.543 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ss"}
> {"timestamp":"2023-04-19 10:23:33.483 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ggg"}
> {"timestamp":"2023-04-19 10:23:35.701 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=s"}
> {"timestamp":"2023-04-19 10:23:37.124 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ssssss"}
> 
>

**Comment by rogerhsu1121** [comment]
> > @rogerhsu1121 Could you please share some more information:
> > 
> > 1. What is the version of the plugin you're using
> > 2. Are you using Jira cloud or Jira server and what version of Jira server if that's the case?
> > 3. Could you please share any console logs from the network tab of the relevant AJAX requests that are unsuccessful with along their responses (to investigate the error)
> >    Thanks for reply
> 
> 1. JIRA Plugin Version is Jira (jira - 3.2.4)
> 2. I use Jira Server (Version v7.2.7)
> 3. I got some log from Mattermost  ->System console->Server logs
> 
> > {"timestamp":"2023-04-19 09:51:22.442 +08:00","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/web_conn.go:830","user_id":"bc4jme54sp8mjmgbhayacnozmc","error":"read tcp 10.156.148.47:8065->10.57.57.196:50854: i/o timeout"}
> > {"timestamp":"2023-04-19 10:01:09.442 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"yawhbxm1tjy8dq5rxd1b9oec5o"}
> > {"timestamp":"2023-04-19 10:11:09.520 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"674oq6h6hbgfzj65sqew6nxmue"}
> > {"timestamp":"2023-04-19 10:13:42.986 +08:00","level":"error","msg":"Received an unknown request as a Jira plugin:\nGET /plugins/jira/plugins/servlet/streams?use-accept-lang=true&streams=user+IS+DennisChen&local=true&maxResults=10 HTTP/1.1\r\nHost: 10.156.148.47:8065\r\nAccept-Encoding: gzip,deflate\r\nAccept-Language: en-us, en;q=0.9, en-us;q=0.8, en;q=0.7, *;q=0.5\r\nConnection: Keep-Alive\r\nUser-Agent: Apache-HttpClient/4.4.1 (Java/1.8.0_102)\r\n\r\n","caller":"app/plugin_api.go:974","plugin_id":"jira"}
> > {"timestamp":"2023-04-19 10:21:09.599 +08:00","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ExpiryNotify","job_id":"uifswjw4uffrbqegzwujwzj8ac"}
> > {"timestamp":"2023-04-19 10:23:26.174 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> > {"timestamp":"2023-04-19 10:23:26.197 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"403 Forbidden: : Request failed. Please analyze the request body for more details. Status code: 403","Path":"/api/v2/get-search-autocomplete-fields","Method":"GET","query":"fieldName=Labels&fieldValue=&instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com"}
> > {"timestamp":"2023-04-19 10:23:26.221 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"403 Forbidden: : Request failed. Please analyze the request body for more details. Status code: 403","Path":"/api/v2/get-search-autocomplete-fields","Method":"GET","query":"fieldName=Requirement+Version&fieldValue=&instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com"}
> > {"timestamp":"2023-04-19 10:23:26.259 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> > {"timestamp":"2023-04-19 10:23:26.348 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}
> > {"timestamp":"2023-04-19 10:23:29.417 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ssss"}
> > {"timestamp":"2023-04-19 10:23:31.543 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ss"}
> > {"timestamp":"2023-04-19 10:23:33.483 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ggg"}
> > {"timestamp":"2023-04-19 10:23:35.701 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=s"}
> > {"timestamp":"2023-04-19 10:23:37.124 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q=ssssss"}
seems can't solve this problem

**Comment by m1lt0n** [comment]
Thanks @rogerhsu1121 for the extra information. We'll investigate the issue and we'll get back as soon as possible.

**Comment by raghavaggarwal2308** [comment]
@m1lt0n I tried to reproduce the error but I was unable to do so. In the server logs shared by @rogerhsu1121, he is getting 403 (forbidden) error responses from the Jira APIs. So, I think it is some permission issue on the Jira side. I tried to change the permission schema, user's groups and project permissions related to the assignee field but the error was not getting reproduced.

@rogerhsu1121 Is there any specific permission you are using on your Jira side that you think might be causing the issue?

**Comment by mickmister** [comment]
@raghavaggarwal2308 One issue I see here is that the frontend is expecting to parse JSON, but is instead parsing a string that does not contain valid JSON. In this case, is the server responding with an error, but not in JSON form? If we can have the server return an error in a structure that the frontend can understand, then we can properly show the error. Even if the error to be shown is "Error fetching data" or something like that

Then there is the issue of "why did this error occur" that we are discussing here. The error isn't specific enough to tell us why it's happening. I don't have any ideas on what about our usage of the API would cause this. It looks like we're doing our best to log the error we get from Jira's API. I don't think there's much we can do about the error itself.

Relevant logs for reference:

`{"timestamp":"2023-04-19 10:23:26.197 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"403 Forbidden: : Request failed. Please analyze the request body for more details. Status code: 403","Path":"/api/v2/get-search-autocomplete-fields","Method":"GET","query":"fieldName=Labels&fieldValue=&instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com"}`

`{"timestamp":"2023-04-19 10:23:26.259 +08:00","level":"error","msg":"ERROR: ","caller":"app/plugin_api.go:974","plugin_id":"jira","Status":"500","Error":"failed to return any results","Path":"/api/v2/get-search-users","Method":"GET","query":"instance_id=https%3A%2F%2Ftpe-jira2.fihtdc.com&project=TIT2&q="}`

I've seen "Please analyze the request body for more details" many times before, though I'm not sure it's always associated with 403. I'm thinking the 403 may even be used incorrectly by Jira in this case, though once again we don't have much insight on the error itself so this is just a guess on my part.
