### ISSUE TITLE
Project List has a limit of 50

### ISSUE THREAD

**Issue by DanTitovTulip** [mattermost/mattermost-plugin-jira#955]
Our Jira instance has hundreds of projects and I am part of a group that has access to all of them.

When I try to use `/jira subscribe` only the first 50 projects are in the list, alphabetically. I am not able to scroll down to see the rest.

**Steps to Reproduce:** 
1. `/Jira connect` in MM channel
2. `/Jira subscribe` in MM channel
3. Select "Project" dropdown
4. Scroll all the way to the end

**Expected Result:** I can see all of the projects I have access to.
**Actual Result:** The project list ends at 50 projects.

**Impact:** Currently the only workaround to this is to create more Jira user groups with specific project access. Most likely won't be using this feature until this is resolved.

Please let me know if there is a better workaround available.

**Comment by ueberBrot** [comment]
It's not only in the subscribe dialogue, it's also in the project dropdown when creating an issue. The limit is 50 here too and the autocomplete can only search through those 50 items.

**Comment by qunabu** [comment]
The Project Dropdown in either attaching message to jira issue or creating subscription is limited to 50 records

Possible solutions 
- typing query should refresh list like in users dropdown 
- more projects should be fetched initially

**Comment by relwell** [comment]
This is biting my team as well. It looks like a related MR has already been merged. Can we get an update on when a fix for this will roll out?

**Comment by MouradHM** [comment]
Hello,

We are having the same issues at my organization. It's becoming quite urgent. Could we have an update on this issue please ?

**Comment by cjonard** [comment]
Hello, do we have any more information? This fix is eagerly awaited by my team too.

**Comment by MouradHM** [comment]
Hello, 

It's can we have an update on that issues ? It's becoming urgent among my organization too.

**Comment by Fburbaud** [comment]
Hi,
Same here. An update or a fix would be nice. Thanks

**Comment by relwell** [comment]
Is this something we can please get taken care of soon? Even a hard-coded bump in the limit of projects would be a big help.

**Comment by qunabu** [comment]
thanks for resolving this much appreciated
