### ISSUE TITLE
Add subscription filter operator "includes or is empty"

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#956]
At the moment, some subscription use cases require you to create two almost identical subscriptions rather than just creating one.

For example, if my Jira instance has a dedicated assignee of `Unassigned`, I may want to have a subscription allow issues such as:

```Assignee = Unassigned OR Assignee IS EMPTY```

The task here is to create a new subscription filter operator to support this use case.

**Comment by Kshitij-Katiyar** [comment]
@mickmister Can you please explain this feature a bit more? Like in the dropdown of the filters, we need to add 1 more option of Assignee and then the user can add multiple filters by selecting the assignee value more than once maybe.

![Screenshot from 2023-08-24 18-58-47](https://github.com/mattermost/mattermost-plugin-jira/assets/90389917/551f2066-e4e2-47e0-bf56-6d22ab799c17)

**Comment by mickmister** [comment]
@Kshitij-Katiyar So in your screenshot, we're effectively creating a big `AND` statement, whereas   here we're wanting an `OR` statement. Today, an admin could achieve what I'm suggesting, by making two subscriptions that are mostly identical, and swapping out either "includes" or "empty" on the Assignee field.

To support this natively, we can make a new Inclusion operator `Include or Empty`. Does this make sense?
