### ISSUE TITLE
UI for the "Create Subscription" button on the "Jira Subscriptions" page is broken on v7.8.2.

### ISSUE THREAD

**Issue by avas27JTG** [mattermost/mattermost-plugin-jira#957]
UI for the "Create Subscription" button on the "Jira Subscriptions" page is broken on `v7.8.2`.
![image](https://github.com/mattermost/mattermost-plugin-jira/assets/72438220/1a638fa0-5003-4aec-9ec9-24df43f27284)

Steps to reproduce:
1. Run command `/jira subscribe edit `.
2. See the "Create Subscription" button.

Expected:
The "Create Subscription" button should be properly aligned with the texts vertically or it should be placed below the texts in centre.

**Comment by mickmister** [comment]
@avas27JTG Thanks for calling this out. Curious if you are interested / planning on solving this issue

@matthewbirtch Thoughts on a low cost UI change we can make here?

**Comment by matthewbirtch** [comment]
> @matthewbirtch Thoughts on a low cost UI change we can make here?

@mickmister does this appear in a full-screen modal? I see no reason why the button should be pushed up against the title so closely, but has it always been that way? For starters, I would suggest the following:

1. Add `margin-left: 24px` to the left of the button 
2. Set the h2 title to have `flex:1; text-align: left`

<img width="1035" alt="image" src="https://github.com/mattermost/mattermost-plugin-jira/assets/2040554/54c6a7d5-4f70-469e-b544-332d5108ff70">

Without testing this in a real environment, that's the best quick stab at it I can make, but can't promise it won't have a negative affect on anything else.

**Comment by mickmister** [comment]
> does this appear in a full-screen modal? 

@matthewbirtch That's correct

> has it always been that way?

I'm not sure, this could be a regression. IIRC the styling is slightly different between when you have 0 subscriptions versus 1 or more subscriptions, so this may be affecting one of those cases.

**Comment by avas27JTG** [comment]
> @avas27JTG Thanks for calling this out. Curious if you are interested / planning on solving this issue
> 
> @matthewbirtch Thoughts on a low cost UI change we can make here?

Yes, we are planning to work on it.
