### ISSUE TITLE
Failed to fetch project metadata for any projects.

### ISSUE THREAD

**Issue by supergeoff** [mattermost/mattermost-plugin-jira#958]
Hello,
I've setup the plugin successfully 8months ago and one channel is properly subscribed to our Jira notifications.
This channel keeps working and receive the notification but I'm now unable to add another channel suscription nor to edit the active one.

I got the same error : Failed to fetch project metadata for any projects.

I've no idea where to look to get additional details on how to solve the issue.

Anyone could point me in the right direction? 

Best regards ;

**Comment by lidoma** [comment]
Same here

**Comment by raghavaggarwal2308** [comment]
@lidoma @supergeoff Have you setup the plugin using cloud or cloud-oauth? If you are using the `cloud`, we recommend you setup your plugin again to using cloud-auth. As the cloud installation is deprecated and can show some weird behaviour.

**Comment by raghavaggarwal2308** [comment]
@lidoma @supergeoff Any update here? If you are not facing the issue anymore can we close it?

**Comment by raghavaggarwal2308** [comment]
Closing for now, can reopen if someone else faces this issue.
