### ISSUE TITLE
Update /jira setup to include specific Jira 9.x step

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jira#960]
We should add specific details for Jira 9.x. The instruction make some mention if you run the install command but, people using the setup command have no indication that anything is different. 

The following things should be added to step 2. of the setup flow:
- **Note**: For Jira 9.x - Ensure "Atlassian product" is selected as the Application type.
- This screen:
![image](https://github.com/mattermost/mattermost-plugin-jira/assets/35588783/692fa5cd-fc1f-4313-92d4-35b2f9ee59e9)

**Comment by raghavaggarwal2308** [comment]
Closing via https://github.com/mattermost/mattermost-plugin-jira/pull/972
