### ISSUE TITLE
Disconnect button after connecting not working for Cloud OAuth

### ISSUE THREAD

**Issue by AayushChaudhary0001** [mattermost/mattermost-plugin-jira#970]
The disconnect button which appears after the user successfully connects to Jira is not working for cloud OAuth.

**Steps to reproduce:-**
1. Run the /jira connect command.
2. Select the instance to be connected and click on accept button.
3. Click on the disconnect button.

![image](https://github.com/mattermost/mattermost-plugin-jira/assets/116162036/f654b055-975d-4d25-b03e-6c79e80d4640)

![image](https://github.com/mattermost/mattermost-plugin-jira/assets/116162036/c9dc8cf8-7206-43cd-ae65-21ebeeacc599)

**Comment by mickmister** [comment]
@AayushChaudhary0001 I think this issue is fine to defer to the next release, in the interests of releasing sooner. It's mainly an inconvenience that the user can't disconnect from this page. For this release, I'm okay with a user receiving this error if they try to disconnect.

**Comment by Kshitij-Katiyar** [comment]
@wiggin77
Hey @AayushChaudhary0001 , I tried reproducing the issue on cloud OAuth but could not. I think this has been fixed in this https://github.com/mattermost/mattermost-plugin-jira/pull/1090. Can you please re-verify that you are still able to reproduce this

**Comment by AayushChaudhary0001** [comment]
@Kshitij-Katiyar This issue is not reproducible now on master branch.
