### ISSUE TITLE
Attachment Size Limit of 10 MB

### ISSUE THREAD

**Issue by pampersrocker** [mattermost/mattermost-plugin-jira#977]
Apparently the plugin has some hardcoded limit for attachments when creating or attaching a message from Mattermost to Jira.
When trying to do so with an attachment bigger than 10MB, the jira bot responded to me with:
> Failed to attach to issue: BER-416, file: Marvin_2023-09-26 18-58-34.mp4. Please notify your system administrator.
Maximum attachment size 10Mb exceeded, file size 17.1Mb

Our Mattermost installation has a configured attachment limit of 100MB and for the Jira Cloud instance it has the default 1GB attachment limit, so I am not sure where this 10 MB limit is coming from.

The file can be attached to the Jira Ticket manually without any problems.

Mattermost Version: 8.0.1
Jira Plugin: 4.0.0

**Comment by raghavaggarwal2308** [comment]
@pampersrocker Are you using a cloud server or a on-prem Matermost instance?

**Comment by pampersrocker** [comment]
This is on a on-prem instance

**Comment by raghavaggarwal2308** [comment]
@pampersrocker There is config setting for the Jira plugin i.e. `MaxAttachmentSize`. You can configure it in the server's config file. Please let me know if you can any issues regarding the same.

```
// Maximum attachment size allowed to be uploaded to Jira, can be a
// number, optionally followed by one of [b, kb, mb, gb, tb]
MaxAttachmentSize string
```

**Comment by pampersrocker** [comment]
Thanks, yes this seems to fix it.
