### ISSUE TITLE
Plugin `v2.x` webhook URL syntax no longer supported

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#982]
#### Summary

When we introduced multiple Jira instance support in `v3.0`, we changed the webhook URL structure to include an identifier of the intended Jira instance. Updating the webhook URL was optional, since there was a check for backwards compatibility for the old webhook URL structure, though this backwards compatibility check regressed in `v4.0.0`.

As mentioned in the `v2.2` tag's [README](https://github.com/mattermost/mattermost-plugin-jira/tree/v2.4.0#step-2-configure-webhooks-in-jira), we previously a supported a syntax like:

```
https://SITEURL/plugins/jira/api/v2/webhook?secret=WEBHOOKSECRET
```

While it looks like this today:

```
https://SITEURL/plugins/jira/instance/INSTANCE_ID/api/v2/webhook?secret=WEBHOOKSECRET
```

The task here is to restore backwards compatibility for the `2.x` webhook URL syntax. This will involve modifying the `mux.Router` to allow the `/webhook` and `api/v2/webhook` endpoints that do not have the `instance/INSTANCE_ID` part of the URL.

The below block which handles this case was in `3.x` but is not in `4.0.0`. Note the `ResolveWebhookInstanceURL` that is called here. This is what normalizes the URL to make the `INSTANCE_ID` optional:
https://github.com/mattermost/mattermost-plugin-jira/blob/acca43d0cf68612c25d5b0e643683c0401eacb42/server/http.go#L100-L110

**Comment by raghavaggarwal2308** [comment]
@mickmister Can we close this as done via https://github.com/mattermost/mattermost-plugin-jira/pull/989
