### ISSUE TITLE
Jira Cloud OAuth installation through Atlassian Marketplace

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#984]
Installing an OAuth app in Jira requires the admin to enable developer mode, and the app is attached to their personal Jira account. The admin then needs to "share" the app, in order to have another Atlassian account connect their MM account to the same OAuth app.

We should instead support installing the plugin through the Atlassian Marketplace https://developer.atlassian.com/platform/marketplace/creating-a-marketplace-listing

**Comment by mickmister** [comment]
@raghavaggarwal2308 Can you or another developer please take a bit of time to determine what it will take to publish our integration to the Atlassian Marketplace? I believe this will involve hardcoding the OAuth redirect URI, which means it will only be supported on Mattermost Cloud servers. This is an expected limitation of the approach.

**Comment by raghavaggarwal2308** [comment]
@mickmister Sure, we will look into this

**Comment by mickmister** [comment]
@raghavaggarwal2308 Curious if you've learned anything about this thus far?

**Comment by raghavaggarwal2308** [comment]
@mickmister I explored quite a bit about this but could not find any proper article about publishing an oauth app to the Atlassian marketplace. Here are a few of them:
https://community.developer.atlassian.com/t/do-i-really-need-to-list-my-oauth-2-0-3lo-app-on-marketplace-to-share-with-other-people/69937
https://developer.atlassian.com/platform/marketplace/knowledge-base/listing-a-third-party-integration-on-the-atlassian-marketplace/
https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/#distributing-your-oauth-2-0--3lo--apps

According to [this](https://developer.atlassian.com/platform/marketplace/knowledge-base/listing-a-third-party-integration-on-the-atlassian-marketplace/) article, I tried publishing an app. However, I could not find any information on Google about what must be filled in the `App file location` field.
Please share if you have any thoughts on this.

**Comment by mickmister** [comment]
@raghavaggarwal2308 Do you know if all this information is for Jira Cloud specifically, or also for Jira Server?

> we have to create a separate cloud app with the Oauth integration and publish that to the marketplace.

@raghavaggarwal2308 Yes this is my understanding as well. We'll need to have the OAuth redirect URIs pointing to our MM Cloud infrastructure, so MM Cloud is the only option for Jira Cloud marketplace apps. Pretty sure that's the case

**Comment by raghavaggarwal2308** [comment]
@mickmister I will investigate more on it and let you know.

**Comment by raghavaggarwal2308** [comment]
Conclusion: After exploration we found that deploying the oauth app to atlassian marketplace is not possible so the user have to enable the distribution in his oauth app only. Refer to `/jira setup` command for more context.
