### ISSUE TITLE
Subtasks are not supported in subscription modal

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-jira#993]
At the moment, we don't support selecting "subtask types" as "issue types" in the subscription modal. It seems this is on purpose based on this line:

https://github.com/mattermost/mattermost-plugin-jira/blob/a86928d1d0c0c2493df5a2690ea8f54f515fd9a5/webapp/src/utils/jira_issue_metadata.tsx#L63

The task here is to look into the feasibility of supporting subtasks in the subscriptions feature. This would also affect the create issue modal if we were to change the line shown above.

**Comment by Kshitij-Katiyar** [comment]
@mickmister I explored a bit on this, removing the filter from the quoted line will make the subscription feature work.
![Screenshot from 2024-06-28 17-16-43](https://github.com/mattermost/mattermost-plugin-jira/assets/90389917/70a64b3c-7bf7-48ec-8083-590488e91241)

For the create issue modal, we would have to add another field of parent issue for the subtask.
![Screenshot from 2024-06-28 17-16-19](https://github.com/mattermost/mattermost-plugin-jira/assets/90389917/c2ba2a54-0132-4994-95e0-a4a93c6244f2)

**Comment by mickmister** [comment]
@Kshitij-Katiyar Okay so subscriptions are working correctly with subtasks after that small change :+1: Though it leaves the "create issue" modal in a partially broken state with no support for subtasks. How much effort do you think it would take to support subtasks in the "create issue" modal? We already have an issue searching thing per project, so maybe we could just reuse that code/component for searching for the parent issue.

Maybe we can split this up into 2 PRs:

- One that makes it so the `!i.subtask` line only runs for the "create issue" modal. This way subscriptions can immediately support subtasks
- One that implements support for the "create issue" modal. I think we can make this one HW

What do you think @Kshitij-Katiyar?

**Comment by raghavaggarwal2308** [comment]
> @Kshitij-Katiyar Okay so subscriptions are working correctly with subtasks after that small change 👍 Though it leaves the "create issue" modal in a partially broken state with no support for subtasks. How much effort do you think it would take to support subtasks in the "create issue" modal? We already have an issue searching thing per project, so maybe we could just reuse that code/component for searching for the parent issue.

@mickmister I think it will take about 10-12 hrs for adding support for sub-tasks in create issue modal.

> Maybe we can split this up into 2 PRs:
> 
> One that makes it so the !i.subtask line only runs for the "create issue" modal. This way subscriptions can immediately support subtasks
> One that implements support for the "create issue" modal. I think we can make this one HW
> What do you think @Kshitij-Katiyar?

@mickmister That sounds good. We can pick up the second task if there are any requests for that.

**Comment by Kshitij-Katiyar** [comment]
@mickmister Created an issue for the second task. https://github.com/mattermost/mattermost-plugin-jira/issues/1093
